// 패시브 15종. perLevel 스탯이 레벨마다 더해진다(최대 maxLevel).
// 각 패시브는 무기 1종의 진화 짝이기도 하다(보유만 하면 조건 충족, 레벨 무관):
//   gym→엔터키 연타, mental→포스트잇 지뢰, lunchbox→아메리카노, shortcut→클립 샷건, busybody→레이저 포인터,
//   multitask→볼펜, grit→명함, speedread→서류철, energy→종이비행기, nunchi→사내 드론,
//   clover→단축키 번개, selfhelp→퇴근 알람, stocks→법인카드, passion→토너 폭탄.
// (vitamin은 진화 짝이 없는 순수 생존 패시브)
// 2차 개정: 적 피해는 판 내내 거의 고정(일반 4~8)이라 방어는 소수점 단위로(철벽 멘탈 최대 -3).
//          속독은 경험치도 조금 줘서 '안 집는 카드'에서 벗어나게, 열정 페이는 설명대로 실제 보상(경험치·월급)을 준다.
import type { PassiveDef } from './types';

export const PASSIVES: PassiveDef[] = [
  {
    id: 'gym',
    name: '헬스장 회원권',
    desc: '피해 +10% / 레벨 · 1년 결제, 출석은 세 번.',
    icon: '💪',
    maxLevel: 5,
    perLevel: { might: 0.1 },
  },
  {
    id: 'mental',
    name: '철벽 멘탈',
    desc: '받는 피해 -0.6 / 레벨(최대 -3) · 부장님 잔소리도 튕겨낸다.',
    icon: '🛡️',
    maxLevel: 5,
    perLevel: { armor: 0.6 },
  },
  {
    id: 'vitamin',
    name: '종합 비타민',
    desc: '최대 체력 +20 / 레벨 · 먹었다는 사실만으로 힘이 난다.',
    icon: '💊',
    maxLevel: 5,
    perLevel: { maxHp: 20 },
  },
  {
    id: 'lunchbox',
    name: '엄마 도시락',
    desc: '초당 체력 회복 +0.2 / 레벨 · 반찬 속에 쪽지가 있다.',
    icon: '🥪',
    maxLevel: 5,
    perLevel: { recovery: 0.2 },
  },
  {
    id: 'shortcut',
    name: '단축키 마스터',
    desc: '쿨타임 -8% / 레벨 · 마우스는 거들 뿐.',
    icon: '⏩',
    maxLevel: 5,
    perLevel: { cooldown: 0.08 },
  },
  {
    id: 'busybody',
    name: '넓은 오지랖',
    desc: '범위 +10% / 레벨 · 남의 일에도 손이 닿는다.',
    icon: '👀',
    maxLevel: 5,
    perLevel: { area: 0.1 },
  },
  {
    id: 'multitask',
    name: '멀티태스킹',
    desc: '투사체 +1 / 레벨 (최대 2) · 회의하면서 메일 쓰기 가능.',
    icon: '🤹',
    maxLevel: 2,
    perLevel: { amount: 1 },
  },
  {
    id: 'grit',
    name: '존버 정신',
    desc: '지속시간 +10% / 레벨 · 버티는 놈이 이긴다.',
    icon: '🧘',
    maxLevel: 5,
    perLevel: { duration: 0.1 },
  },
  {
    id: 'speedread',
    name: '속독 스킬',
    desc: '투사체 속도 +10%, 경험치 +3% / 레벨 · 빨리 읽으니 빨리 배운다.',
    icon: '📖',
    maxLevel: 5,
    perLevel: { projSpeed: 0.1, growth: 0.03 },
  },
  {
    id: 'energy',
    name: '에너지 드링크',
    desc: '이동속도 +8% / 레벨 · 심장이 먼저 출근한다.',
    icon: '🥤',
    maxLevel: 5,
    perLevel: { moveSpeed: 0.08 },
  },
  {
    id: 'nunchi',
    name: '눈치 백단',
    desc: '획득 반경 +25% / 레벨 · 떨어진 건 귀신같이 줍는다.',
    icon: '👂',
    maxLevel: 5,
    perLevel: { magnet: 0.25 },
  },
  {
    id: 'clover',
    name: '사내 인맥',
    desc: '행운 +10% / 레벨 · 아는 사람이 있으면 일이 풀린다.',
    icon: '🍀',
    maxLevel: 5,
    perLevel: { luck: 0.1 },
    unlockedBy: 'u_passive_clover',
  },
  {
    id: 'selfhelp',
    name: '자기계발서',
    desc: '경험치 +8% / 레벨 · 표지만 읽어도 성장한 기분.',
    icon: '📚',
    maxLevel: 5,
    perLevel: { growth: 0.08 },
    unlockedBy: 'u_passive_selfhelp',
  },
  {
    id: 'stocks',
    name: '주식 앱',
    desc: '월급(코인) +15%, 치명타 +1% / 레벨 · 가끔 떡상한다.',
    icon: '📈',
    maxLevel: 5,
    perLevel: { greed: 0.15, crit: 0.01 },
    unlockedBy: 'u_passive_stocks',
  },
  {
    id: 'passion',
    name: '열정 페이',
    desc: '저주 +8%(적 체력·수·속도↑), 피해 +5%, 경험치 +5%, 월급 +10% / 레벨 · 일은 두 배, 보상도 조금 더.',
    icon: '🔥',
    maxLevel: 5,
    perLevel: { curse: 0.08, might: 0.05, growth: 0.05, greed: 0.1 },
    unlockedBy: 'u_passive_passion',
  },
];
