/**
 * 운동 라이브러리 ① 목 · 어깨 · 등 · 가슴 · 호흡 · 손목
 * 문구·용량·대상 이슈는 물리치료 임상 기준으로 작성되었으며, 전문가가 자유롭게 수정할 수 있습니다.
 */
import { both } from '../figure/rig';
import { HOOK, merge, PRONE, QUAD, SIDE_LYING, SIT, STAND, WALL } from '../figure/poses';
import type { Exercise } from './exercise-types';

const HANDS_BEHIND_HEAD = both({ sh: { flex: 150, abd: 42, rot: 10 }, el: 142 });

export const UPPER: Exercise[] = [
  {
    id: 'chin-tuck',
    name: { ko: '턱 당기기', en: 'Chin tuck' },
    phase: 'activate',
    position: 'seated',
    regions: ['neck'],
    targets: { fhp: 1, neckPain: 0.7, headache: 0.5 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 2, holdSec: 5, rest: 15 },
    desk: true,
    steps: {
      ko: ['허리를 펴고 앉아 정면을 봐요.', '턱을 살짝 당기면서 뒤통수를 뒤로 쭉 밀어 “이중턱”을 만들어요.', '5초 버틴 뒤 천천히 풀어요.', '고개를 숙이는 게 아니라 머리 전체를 뒤로 “미는” 느낌이에요.'],
      en: ['Sit tall and look straight ahead.', 'Gently draw your chin in and glide your whole head straight back — make a double chin.', 'Hold for 5 seconds, then relax slowly.', 'Don’t nod down. Think “slide back”.'],
    },
    cues: { ko: ['뒤통수를 뒤로 밀어요', '시선은 정면 그대로', '어깨는 힘을 빼요'], en: ['Slide your head back', 'Keep your eyes level', 'Relax your shoulders'] },
    mistakes: { ko: ['고개를 아래로 숙임', '어깨가 함께 올라감', '숨을 참음'], en: ['Nodding the head down', 'Shrugging the shoulders', 'Holding your breath'] },
    why: { ko: '약해진 심부 목굽힘근을 깨워 앞으로 나온 머리를 어깨 위로 되돌리는, 거북목 교정의 가장 기본 운동이에요.', en: 'Wakes up the weak deep neck flexors to bring your head back over your shoulders — the foundation of fixing tech neck.' },
    muscles: { ko: '심부 목굽힘근(두장근·경장근)', en: 'Deep neck flexors (longus capitis/colli)' },
    caution: { ko: '어지럽거나 팔이 저리면 바로 멈추세요.', en: 'Stop if you feel dizzy or your arms tingle.' },
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      keys: [merge(SIT, { neck: { flex: 12 }, head: { flex: -10 } }), merge(SIT, { neck: { flex: -8 }, head: { flex: 10 } })],
      durations: [1.1, 1.1],
      pauses: [0.8, 2.4],
      zoom: 1.25,
    },
  },
  {
    id: 'supine-chin-lift',
    name: { ko: '누워서 턱 당겨 머리 들기', en: 'Supine chin-tuck head lift' },
    phase: 'activate',
    position: 'supine',
    regions: ['neck'],
    targets: { fhp: 0.9, neckPain: 0.5, headache: 0.3 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 2, holdSec: 5, rest: 20 },
    steps: {
      ko: ['무릎을 세우고 바로 누워요.', '뒤통수를 바닥에 붙인 채 턱을 당겨 목 뒤를 길게 만들어요.', '턱을 당긴 상태 그대로 머리를 1~2cm만 살짝 들어 5초 버텨요.', '천천히 내려놓고 목 힘을 풀어요.'],
      en: ['Lie on your back with knees bent.', 'Keep the back of your head on the floor and tuck your chin to lengthen the neck.', 'Keeping the tuck, lift your head just 1–2 cm and hold for 5 seconds.', 'Lower slowly and relax your neck.'],
    },
    cues: { ko: ['턱을 먼저 당기고', '아주 살짝만 들어요', '목 앞이 떨리면 정상이에요'], en: ['Tuck first', 'Lift only a little', 'A slight shake is normal'] },
    mistakes: { ko: ['턱이 들리며 머리만 번쩍 듦', '너무 높이 듦', '어깨까지 들림'], en: ['Chin poking up as you lift', 'Lifting too high', 'Shoulders coming up too'] },
    why: { ko: '턱 당기기의 다음 단계로, 목 앞 깊은 근육의 지구력을 키워 바른 머리 위치를 오래 유지하게 해 줘요.', en: 'The next step after chin tucks: builds deep-neck endurance so you can hold a good head position all day.' },
    muscles: { ko: '심부 목굽힘근 지구력', en: 'Deep neck flexor endurance' },
    caution: { ko: '목에 날카로운 통증이 있으면 턱 당기기(앉아서)로 대신하세요.', en: 'If you feel sharp neck pain, do seated chin tucks instead.' },
    avoid: ['neckSevere'],
    anim: {
      view: 90,
      elev: 10,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [merge(HOOK, { neck: { flex: -4 }, head: { flex: 4 } }), merge(HOOK, { neck: { flex: 26 }, head: { flex: 6 } })],
      durations: [1, 1],
      pauses: [0.8, 2.6],
      zoom: 1.1,
    },
  },
  {
    id: 'upper-trap-stretch',
    name: { ko: '상부 승모근 스트레칭', en: 'Upper trapezius stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['neck', 'shoulder'],
    targets: { neckPain: 0.9, shoulderTilt: 0.8, fhp: 0.4, headache: 0.6, stiffness: 0.5, headTilt: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자에 앉아 오른손으로 의자 옆을 잡아 오른쪽 어깨를 아래로 고정해요.', '왼손을 머리 위로 넘겨 오른쪽 귀 윗부분에 가볍게 얹어요.', '머리를 왼쪽으로 천천히 기울여 오른쪽 목과 어깨 사이가 늘어나게 해요.', '손은 당기지 말고 무게만 얹은 채 30초 길게 호흡해요.'],
      en: ['Sit and hold the side of the chair with your right hand to anchor your right shoulder down.', 'Reach your left hand over your head and rest it above your right ear.', 'Slowly tilt your head to the left until you feel the right side of your neck lengthen.', 'Don’t pull — let the hand’s weight do the work — and breathe slowly for 30 seconds.'],
    },
    cues: { ko: ['어깨는 아래로 툭', '숨을 내쉬며 조금 더', '당기지 말고 무게만'], en: ['Let the shoulder drop', 'Exhale and sink a little deeper', 'No pulling, just weight'] },
    mistakes: { ko: ['늘리는 쪽 어깨가 따라 올라감', '손으로 세게 잡아당김', '몸통이 함께 기울어짐'], en: ['The stretched shoulder rising', 'Yanking with the hand', 'Leaning the whole trunk'] },
    why: { ko: '어깨 위에서 뭉친 상부 승모근을 늘려 목·어깨 결림과 긴장성 두통을 줄여요. 어깨가 올라간 쪽을 한 세트 더 해 주세요.', en: 'Lengthens the tight upper trapezius to ease neck/shoulder tension and headaches. Add an extra set on the higher shoulder.' },
    muscles: { ko: '상부 승모근', en: 'Upper trapezius' },
    anim: {
      view: 0,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { shL: { flex: 30, abd: 150, rot: 20 }, elL: 120, shR: { flex: -4, abd: 12 }, elR: 4 }),
        merge(SIT, { shL: { flex: 30, abd: 150, rot: 20 }, elL: 120, shR: { flex: -4, abd: 12 }, elR: 4, neck: { side: 26 }, head: { side: 10 }, scapR: { elev: -1.5 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.6, 3],
      zoom: 1.2,
    },
    coach: {
      view: 'front',
      metric: 'headTilt',
      mode: 'hold',
      target: 16,
      dir: 1,
      hint: { ko: '정면에서 상체가 보이게 휴대폰을 세워 주세요', en: 'Prop your phone facing you so your upper body is visible' },
      more: { ko: '머리를 조금 더 기울여요', en: 'Tilt a little more' },
      good: { ko: '좋아요, 그대로 호흡', en: 'Good, breathe here' },
    },
  },
  {
    id: 'levator-stretch',
    name: { ko: '견갑거근 스트레칭', en: 'Levator scapulae stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['neck', 'shoulder'],
    targets: { neckPain: 0.8, fhp: 0.4, shoulderTilt: 0.5, stiffness: 0.5, headache: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['오른손으로 의자 옆을 잡아요.', '고개를 왼쪽으로 45° 돌린 뒤, 코를 왼쪽 겨드랑이 쪽으로 숙여요.', '왼손을 뒤통수에 얹어 무게만 더해요.', '오른쪽 목 뒤~날개뼈 윗부분이 당기면 30초 유지해요.'],
      en: ['Hold the side of the chair with your right hand.', 'Turn your head 45° to the left, then bring your nose toward your left armpit.', 'Rest your left hand on the back of your head for a little extra weight.', 'Hold 30 seconds when you feel the back of the right neck and top of the shoulder blade stretch.'],
    },
    cues: { ko: ['코는 겨드랑이 쪽으로', '반대쪽 어깨는 아래로', '편하게 숨 쉬어요'], en: ['Nose toward the armpit', 'Opposite shoulder down', 'Breathe easy'] },
    mistakes: { ko: ['고개만 숙이고 돌리지 않음', '어깨가 올라감'], en: ['Nodding without turning', 'Shoulder hiking up'] },
    why: { ko: '날개뼈를 목으로 끌어올리는 견갑거근은 거북목·스마트폰 자세에서 가장 먼저 뭉쳐요. 담 결린 느낌에 특히 좋아요.', en: 'The levator scapulae, which pulls the shoulder blade up toward the neck, is the first to tighten with phone posture — great for that “knot” feeling.' },
    muscles: { ko: '견갑거근', en: 'Levator scapulae' },
    anim: {
      view: 25,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { shL: { flex: 125, abd: 40, rot: 10 }, elL: 125, shR: { flex: -4, abd: 12 }, elR: 4 }),
        merge(SIT, { shL: { flex: 125, abd: 40, rot: 10 }, elL: 125, shR: { flex: -4, abd: 12 }, elR: 4, neck: { twist: 38, flex: 26, side: 8 }, head: { flex: 14 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.6, 3],
      zoom: 1.2,
    },
  },
  {
    id: 'scm-stretch',
    name: { ko: '목 앞 근육(흉쇄유돌근) 스트레칭', en: 'SCM stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['neck'],
    targets: { fhp: 0.7, headTilt: 0.5, neckPain: 0.4, headache: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 20, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['양손을 겹쳐 오른쪽 쇄골 바로 아래를 살짝 눌러 고정해요.', '고개를 왼쪽으로 기울인 뒤 턱을 천장 쪽으로 살짝 들어요.', '오른쪽 목 앞쪽이 늘어나는 느낌에서 20초 유지해요.'],
      en: ['Cross your hands and gently press just below your right collarbone.', 'Tilt your head to the left, then lift your chin slightly toward the ceiling.', 'Hold 20 seconds when you feel the front-right of your neck stretch.'],
    },
    cues: { ko: ['쇄골은 아래로 고정', '턱은 살짝만 들어요'], en: ['Anchor the collarbone', 'Lift the chin only slightly'] },
    mistakes: { ko: ['고개를 뒤로 과하게 젖힘', '입을 벌리고 턱에 힘줌'], en: ['Throwing the head far back', 'Clenching or opening the jaw'] },
    why: { ko: '머리가 앞으로 나오면 목 앞의 흉쇄유돌근이 짧아져 머리를 계속 앞으로 끌어당겨요. 짧게, 부드럽게 늘려 주세요.', en: 'With forward head posture the SCM shortens and keeps pulling the head forward. Stretch it briefly and gently.' },
    muscles: { ko: '흉쇄유돌근, 사각근', en: 'Sternocleidomastoid, scalenes' },
    caution: { ko: '어지럼증이나 눈앞이 흐려지면 즉시 멈추세요. 목을 뒤로 젖히는 동작이 불편한 분은 생략하세요.', en: 'Stop immediately if you feel dizzy or your vision blurs. Skip it if tilting your head back is uncomfortable.' },
    avoid: ['dizzy', 'neckSevere'],
    anim: {
      view: 15,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { shL: { flex: 22, hab: -38 }, elL: 118, shR: { flex: 20, hab: -26 }, elR: 112 }),
        merge(SIT, { shL: { flex: 22, hab: -38 }, elL: 118, shR: { flex: 20, hab: -26 }, elR: 112, neck: { side: 22, flex: -14 }, head: { flex: -6, twist: 8 } }),
      ],
      durations: [1.5, 1.5],
      pauses: [0.6, 2.6],
      zoom: 1.25,
    },
  },
  {
    id: 'suboccipital-release',
    name: { ko: '뒤통수 아래 풀기', en: 'Suboccipital release' },
    phase: 'release',
    position: 'seated',
    regions: ['neck'],
    targets: { headache: 0.9, fhp: 0.6, neckPain: 0.6, stress: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'time', sets: 1, value: 60 },
    desk: true,
    steps: {
      ko: ['양손 엄지를 뒤통수 아래 움푹 들어간 곳(머리뼈 바로 아래)에 대요.', '작은 원을 그리며 30초간 지그시 문질러요.', '엄지를 댄 채로 턱을 아주 살짝 끄덕이는 동작을 5번 반복해요.', '시원한 정도의 압력만 주세요.'],
      en: ['Place both thumbs in the hollows just below the base of your skull.', 'Massage in small circles for 30 seconds with steady pressure.', 'Keeping the thumbs there, make 5 tiny nods with your chin.', 'Use pressure that feels relieving, not painful.'],
    },
    cues: { ko: ['작게 원을 그려요', '아주 작게 끄덕끄덕', '어깨 힘 빼고'], en: ['Small circles', 'Tiny nods', 'Relax the shoulders'] },
    mistakes: { ko: ['너무 세게 누름', '목을 크게 움직임'], en: ['Pressing too hard', 'Big neck movements'] },
    why: { ko: '화면을 보느라 턱이 들리면 뒤통수 아래 작은 근육(후두하근)이 짧게 뭉쳐 두통과 눈 피로를 만들어요.', en: 'Poking the chin to look at screens shortens the small suboccipital muscles, a common source of headaches and eye strain.' },
    muscles: { ko: '후두하근', en: 'Suboccipitals' },
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      keys: [merge(SIT, HANDS_BEHIND_HEAD, { neck: { flex: -2 } }), merge(SIT, HANDS_BEHIND_HEAD, { neck: { flex: -6 }, head: { flex: 10 } })],
      durations: [0.9, 0.9],
      pauses: [0.3, 0.3],
      zoom: 1.25,
    },
  },
  {
    id: 'breath-360',
    name: { ko: '360° 복식 호흡', en: '360° breathing' },
    phase: 'breath',
    position: 'seated',
    regions: ['core', 'upperBack'],
    targets: { stress: 1, stiffness: 0.4, lordosis: 0.3, fhp: 0.2, roundShoulder: 0.2 },
    equipment: [],
    level: 1,
    dose: { kind: 'time', sets: 1, value: 60 },
    desk: true,
    steps: {
      ko: ['허리를 세우고 앉아 한 손은 가슴, 한 손은 옆구리에 대요.', '코로 4초간 들이마시며 배·옆구리·등까지 풍선처럼 360° 부풀려요.', '입으로 6초간 길게 내쉬며 갈비뼈를 아래로 내려요.', '가슴과 어깨는 들썩이지 않게 해요.'],
      en: ['Sit tall with one hand on your chest and one on the side of your ribs.', 'Breathe in through the nose for 4 seconds, expanding belly, sides and back like a balloon.', 'Breathe out through the mouth for 6 seconds, letting the ribs drop.', 'Keep your chest and shoulders quiet.'],
    },
    cues: { ko: ['코로 들이마시고', '입으로 길게 내쉬어요', '어깨는 조용히'], en: ['In through the nose', 'Long breath out', 'Shoulders stay quiet'] },
    mistakes: { ko: ['가슴과 어깨로만 숨 쉬기', '배만 내밀기'], en: ['Breathing only into the chest', 'Pushing only the belly out'] },
    why: { ko: '얕은 가슴 호흡은 목·어깨의 보조 호흡근을 혹사시켜요. 횡격막 호흡은 긴장을 낮추고 코어를 안쪽부터 세워 줘요.', en: 'Shallow chest breathing overworks the neck and shoulder muscles. Diaphragm breathing lowers tension and switches on your core from the inside.' },
    muscles: { ko: '횡격막, 복횡근', en: 'Diaphragm, transversus abdominis' },
    anim: {
      view: 30,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { shL: { flex: 24, hab: -30 }, elL: 112, shR: { flex: 6, abd: 16, rot: -40 }, elR: 88 }),
        merge(SIT, { shL: { flex: 24, hab: -30 }, elL: 112, shR: { flex: 6, abd: 20, rot: -40 }, elR: 88, thorax: { flex: -4 }, neck: { flex: 3 } }),
      ],
      durations: [4, 6],
      zoom: 1.2,
    },
  },
  {
    id: 'shoulder-rolls',
    name: { ko: '어깨 뒤로 돌리기', en: 'Backward shoulder rolls' },
    phase: 'mobility',
    position: 'standing',
    regions: ['shoulder', 'neck'],
    targets: { stiffness: 0.8, neckPain: 0.4, roundShoulder: 0.3, stress: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 3, rest: 10 },
    desk: true,
    steps: {
      ko: ['편하게 서거나 앉아서 팔에 힘을 빼요.', '어깨를 귀 쪽으로 끌어올린 뒤', '뒤로 크게 돌리며 날개뼈를 모았다가', '아래로 쭉 내려놓아요. 큰 원을 그리듯 천천히.'],
      en: ['Stand or sit with your arms relaxed.', 'Lift your shoulders up toward your ears,', 'roll them back, squeezing your shoulder blades together,', 'then drop them down. Draw big, slow circles.'],
    },
    cues: { ko: ['크게 원을 그려요', '뒤로 모으고 아래로'], en: ['Big circles', 'Back and down'] },
    mistakes: { ko: ['너무 빠르게 돌림', '목까지 같이 움직임'], en: ['Rolling too fast', 'Moving the neck along'] },
    why: { ko: '굳은 어깨 주변에 혈류를 돌리고, 어깨를 “뒤·아래” 제자리로 돌려놓는 감각을 깨우는 워밍업이에요.', en: 'A warm-up that gets blood moving around stiff shoulders and reminds them where “back and down” is.' },
    muscles: { ko: '승모근, 능형근, 견갑거근', en: 'Trapezius, rhomboids, levator scapulae' },
    anim: {
      view: 90,
      keys: [
        STAND,
        merge(STAND, both({ scap: { elev: 4.5, prot: 1.5 } })),
        merge(STAND, both({ scap: { elev: 2.5, prot: -3 } }), { thorax: { flex: -3 } }),
        merge(STAND, both({ scap: { elev: -1, prot: -2 } })),
      ],
      durations: [0.8, 0.8, 0.7, 0.7],
      zoom: 1.2,
    },
  },
  {
    id: 'chest-opener',
    name: { ko: '앉아서 가슴 열기', en: 'Seated chest opener' },
    phase: 'stretch',
    position: 'seated',
    regions: ['chest', 'shoulder'],
    targets: { roundShoulder: 0.8, kyphosis: 0.5, fhp: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 3, value: 20, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자 앞쪽에 앉아 양손을 등 뒤에서 깍지 껴요.', '날개뼈를 모으며 팔을 뒤로 쭉 뻗어요.', '가슴을 앞으로 활짝 열고 턱은 살짝 당겨요.', '20초 유지하며 호흡해요.'],
      en: ['Sit near the front of the chair and clasp your hands behind your back.', 'Squeeze your shoulder blades together and straighten your arms back.', 'Open your chest forward while keeping your chin gently tucked.', 'Hold for 20 seconds and breathe.'],
    },
    cues: { ko: ['날개뼈를 모아요', '가슴은 앞으로', '턱은 살짝 당겨요'], en: ['Squeeze the shoulder blades', 'Chest forward', 'Chin gently in'] },
    mistakes: { ko: ['허리만 과하게 젖힘', '고개가 앞으로 빠짐'], en: ['Over-arching the low back', 'Head drifting forward'] },
    why: { ko: '말린 어깨의 원인인 짧아진 가슴 근육을 늘리고, 등 근육으로 어깨를 뒤로 모으는 감각을 동시에 익혀요.', en: 'Stretches the shortened chest muscles that round your shoulders while teaching your back muscles to hold them back.' },
    muscles: { ko: '대흉근, 소흉근, 삼각근 앞쪽', en: 'Pecs major & minor, front deltoids' },
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      keys: [merge(SIT, both({ sh: { flex: -20, abd: 8 }, el: 20 })), merge(SIT, both({ sh: { flex: -48, abd: 4 }, el: 0, scap: { prot: -3 } }), { thorax: { flex: -10 }, neck: { flex: 4 } })],
      durations: [1.4, 1.4],
      pauses: [0.4, 2.6],
      zoom: 1.2,
    },
  },
  {
    id: 'wall-pec-stretch',
    name: { ko: '벽 가슴 스트레칭', en: 'Wall pec stretch' },
    phase: 'stretch',
    position: 'wall',
    regions: ['chest', 'shoulder'],
    targets: { roundShoulder: 1, kyphosis: 0.5, fhp: 0.3, shoulderPain: 0.3 },
    equipment: ['wall'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    steps: {
      ko: ['벽 옆에 서서 오른팔을 90°로 굽혀 팔꿈치와 손바닥을 벽에 대요.', '오른발을 반 걸음 앞으로 내딛으며 몸을 왼쪽으로 살짝 돌려요.', '가슴 앞쪽이 늘어나면 멈추고 30초 유지해요.', '어깨가 앞으로 튀어나오지 않게 날개뼈를 살짝 모아요.'],
      en: ['Stand beside a wall and place your right forearm on it with the elbow bent 90°.', 'Step your right foot half a step forward and gently turn your body to the left.', 'Stop when the front of your chest stretches and hold 30 seconds.', 'Keep the shoulder blade gently back so the shoulder doesn’t poke forward.'],
    },
    cues: { ko: ['몸을 천천히 반대로', '어깨는 뒤로', '숨을 길게'], en: ['Turn away slowly', 'Shoulder back', 'Long breaths'] },
    mistakes: { ko: ['어깨가 앞으로 쏠림', '팔을 너무 높이 올림'], en: ['Shoulder rolling forward', 'Arm placed too high'] },
    why: { ko: '라운드숄더의 핵심 원인인 대흉근·소흉근을 가장 효과적으로 늘리는 방법이에요.', en: 'The most effective way to lengthen the pecs — the key driver of rounded shoulders.' },
    muscles: { ko: '대흉근, 소흉근', en: 'Pectoralis major & minor' },
    caution: { ko: '어깨 앞이 찌릿하거나 저리면 팔 높이를 낮추세요.', en: 'Lower the arm if the front of the shoulder pinches or tingles.' },
    avoid: ['shoulderSevere'],
    anim: {
      view: -35,
      props: [{ kind: 'wall', wall: 'right', dist: 1 }],
      keys: [
        merge(STAND, { shR: { abd: 88, rot: 85, flex: -8 }, elR: 92, shL: { abd: 6 }, elL: 8 }),
        merge(STAND, { shR: { abd: 88, rot: 85, flex: -30 }, elR: 92, shL: { abd: 6 }, elL: 8, thorax: { twist: 16 }, lumbar: { twist: 8 }, hipR: { flex: 14 }, knR: 10, hipL: { flex: -8 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.6, 3],
    },
  },
  {
    id: 'chair-tspine-extension',
    name: { ko: '의자 등받이 등 펴기', en: 'Chair thoracic extension' },
    phase: 'mobility',
    position: 'seated',
    regions: ['upperBack'],
    targets: { kyphosis: 1, roundShoulder: 0.6, fhp: 0.4, upperBackPain: 0.7, stiffness: 0.4 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 4, holdSec: 2, rest: 10 },
    desk: true,
    steps: {
      ko: ['등받이 윗부분이 날개뼈 아래에 오도록 깊숙이 앉아요.', '양손을 머리 뒤에 깍지 끼고 팔꿈치를 모아요.', '숨을 내쉬며 등받이를 받침 삼아 가슴을 천장 쪽으로 젖혀요.', '허리가 아닌 등 윗부분이 펴지는 느낌으로 2초 멈췄다 돌아와요.'],
      en: ['Sit back so the top of the chair meets your back just below the shoulder blades.', 'Clasp your hands behind your head, elbows together.', 'Exhale and extend your chest toward the ceiling over the chair back.', 'Feel it in the upper back, not the low back. Pause 2 seconds and return.'],
    },
    cues: { ko: ['가슴을 천장으로', '허리는 그대로', '숨을 내쉬며'], en: ['Chest to the ceiling', 'Low back stays put', 'Exhale as you go'] },
    mistakes: { ko: ['허리를 꺾음', '목만 뒤로 젖힘'], en: ['Arching the low back', 'Only tipping the head back'] },
    why: { ko: '둥글게 굳은 흉추(등뼈)를 펴 주면 어깨와 목이 따라서 제자리를 찾아요. 사무실에서 가장 효율 좋은 동작이에요.', en: 'Unlocking a stiff, rounded upper spine lets your neck and shoulders fall back into place — the best bang-for-buck desk move.' },
    muscles: { ko: '흉추 신전근, 흉추 관절 가동성', en: 'Thoracic extensors & joint mobility' },
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      keys: [merge(SIT, HANDS_BEHIND_HEAD, { thorax: { flex: 6 } }), merge(SIT, HANDS_BEHIND_HEAD, { thorax: { flex: -22 }, lumbar: { flex: -4 }, neck: { flex: -6 } })],
      durations: [1.8, 1.8],
      pauses: [0.3, 1.2],
      zoom: 1.2,
    },
  },
  {
    id: 'wall-angel',
    name: { ko: '벽 천사', en: 'Wall angel' },
    phase: 'activate',
    position: 'wall',
    regions: ['shoulder', 'upperBack'],
    targets: { roundShoulder: 0.9, kyphosis: 0.7, fhp: 0.5, upperBackPain: 0.4 },
    equipment: ['wall'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 4, rest: 20 },
    steps: {
      ko: ['벽에서 발뒤꿈치를 한 뼘 떨어뜨리고 엉덩이·등·뒤통수를 벽에 붙여요.', '팔을 W 모양으로 만들어 팔꿈치와 손등을 벽에 대요.', '허리가 뜨지 않게 배에 살짝 힘을 주고 팔을 위로 천천히 밀어 올려요.', 'Y 모양까지 올렸다가 다시 W로 내려와요.'],
      en: ['Stand with heels a hand-width from the wall; glutes, back and head touch the wall.', 'Make a “W” with your arms, elbows and backs of the hands on the wall.', 'Brace your belly so your low back stays on the wall, then slide your arms up slowly.', 'Go up to a “Y”, then back down to the “W”.'],
    },
    cues: { ko: ['허리는 벽에 붙인 채', '손등이 벽에서 떨어지지 않게', '천천히 내려요'], en: ['Low back stays on the wall', 'Backs of hands on the wall', 'Slow on the way down'] },
    mistakes: { ko: ['허리가 벽에서 뜸', '턱이 들림', '어깨를 으쓱함'], en: ['Low back peeling off the wall', 'Chin poking out', 'Shrugging'] },
    why: { ko: '말린 어깨를 뒤로 모아 주는 중·하부 승모근을 깨우고 가슴을 여는, 라운드숄더 교정의 대표 운동이에요.', en: 'The classic rounded-shoulder fix: activates the middle/lower traps while opening the chest.' },
    muscles: { ko: '중·하부 승모근, 전거근', en: 'Middle/lower trapezius, serratus anterior' },
    caution: { ko: '팔이 벽에 다 닿지 않아도 괜찮아요. 통증 없는 범위까지만.', en: 'It’s fine if your arms don’t touch the wall fully — stay pain-free.' },
    avoid: ['shoulderSevere'],
    anim: {
      view: 0,
      props: [{ kind: 'wall', wall: 'back' }],
      keys: [merge(WALL, both({ sh: { abd: 82, rot: 88 }, el: 96 })), merge(WALL, both({ sh: { abd: 150, rot: 88 }, el: 24 }))],
      durations: [1.8, 1.8],
      pauses: [0.3, 0.4],
    },
    coach: {
      view: 'front',
      metric: 'armRaise',
      mode: 'reps',
      rest: 0.55,
      peak: 0.85,
      dir: 1,
      hint: { ko: '정면에서 팔 끝까지 보이게 2m 거리에 휴대폰을 세워 주세요', en: 'Place the phone about 2 m in front of you so your arms are visible' },
      more: { ko: '팔을 조금 더 위로', en: 'Reach a little higher' },
      good: { ko: '좋아요!', en: 'Nice!' },
    },
  },
  {
    id: 'prone-y-raise',
    name: { ko: '엎드려 Y 들기', en: 'Prone Y raise' },
    phase: 'activate',
    position: 'prone',
    regions: ['upperBack', 'shoulder'],
    targets: { roundShoulder: 1, kyphosis: 0.7, upperBackPain: 0.5, fhp: 0.3 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 3, holdSec: 2, rest: 20 },
    steps: {
      ko: ['엎드려 이마 아래 수건을 받치고 턱을 살짝 당겨요.', '엄지가 천장을 향하게 하고 팔을 Y자로 뻗어요.', '날개뼈를 아래·안쪽으로 모으며 팔을 바닥에서 살짝 들어요.', '2초 버티고 천천히 내려요. 익숙해지면 T·W 모양도 같은 방법으로 해요.'],
      en: ['Lie face down with a towel under your forehead and your chin gently tucked.', 'Stretch your arms into a “Y” with thumbs pointing up.', 'Draw your shoulder blades down and together and lift your arms slightly off the floor.', 'Hold 2 seconds and lower slowly. Progress to “T” and “W” shapes the same way.'],
    },
    cues: { ko: ['날개뼈를 아래로 모아요', '목은 길게', '천천히 내려요'], en: ['Blades down and in', 'Long neck', 'Lower slowly'] },
    mistakes: { ko: ['고개를 들어 올림', '허리를 젖혀 상체를 듦', '어깨를 으쓱'], en: ['Lifting the head', 'Arching the back to lift', 'Shrugging'] },
    why: { ko: '가장 약해지기 쉬운 하부 승모근을 정확히 강화해 어깨를 뒤·아래로 안정시켜요.', en: 'Precisely strengthens the lower trapezius — usually the weakest link — to hold the shoulders back and down.' },
    muscles: { ko: '하부·중부 승모근, 능형근', en: 'Lower & middle trapezius, rhomboids' },
    avoid: ['pregnant', 'shoulderSevere'],
    anim: {
      view: 90,
      elev: 14,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [merge(PRONE, both({ sh: { flex: 176, abd: 28, rot: 30 }, el: 0 })), merge(PRONE, both({ sh: { flex: 196, abd: 28, rot: 30 }, el: 0, scap: { prot: -2, elev: -1 } }), { thorax: { flex: -4 } })],
      durations: [1.3, 1.3],
      pauses: [0.4, 1.8],
    },
  },
  {
    id: 'scap-squeeze',
    name: { ko: '날개뼈 모으며 팔 벌리기', en: 'Scapular squeeze & external rotation' },
    phase: 'activate',
    position: 'standing',
    regions: ['upperBack', 'shoulder'],
    targets: { roundShoulder: 0.8, upperBackPain: 0.6, kyphosis: 0.4, fhp: 0.2 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 12, tempo: 2.5, holdSec: 3, rest: 15 },
    desk: true,
    steps: {
      ko: ['팔꿈치를 90°로 굽혀 옆구리에 붙이고 손바닥은 위로 향해요.', '팔꿈치를 옆구리에 붙인 채 손을 바깥으로 벌려요.', '동시에 날개뼈를 뒤·아래로 모아요.', '3초 버티고 천천히 돌아와요. 어깨가 올라가지 않게.'],
      en: ['Bend your elbows 90° at your sides, palms up.', 'Keeping the elbows tucked, rotate your hands outward.', 'At the same time draw your shoulder blades back and down.', 'Hold 3 seconds and return slowly — no shrugging.'],
    },
    cues: { ko: ['팔꿈치는 옆구리에', '날개뼈를 뒤로 아래로', '가슴을 펴요'], en: ['Elbows stay tucked', 'Blades back and down', 'Open the chest'] },
    mistakes: { ko: ['팔꿈치가 옆구리에서 떨어짐', '허리를 젖힘'], en: ['Elbows drifting away', 'Arching the low back'] },
    why: { ko: '말린 어깨를 바깥으로 돌려 주는 회전근개와 날개뼈 안정근을 함께 깨워요. 틈날 때마다 하기 좋아요.', en: 'Wakes up the rotator cuff and shoulder-blade stabilisers that un-roll your shoulders. Great to sprinkle through the day.' },
    muscles: { ko: '극하근·소원근, 중부 승모근, 능형근', en: 'Infraspinatus, teres minor, middle trap, rhomboids' },
    anim: {
      view: 20,
      elev: 18,
      keys: [merge(STAND, both({ sh: { rot: -10, abd: 8 }, el: 90 })), merge(STAND, both({ sh: { rot: 62, abd: 8, flex: -6 }, el: 90, scap: { prot: -2.8, elev: -0.8 } }), { thorax: { flex: -3 } })],
      durations: [1.2, 1.2],
      pauses: [0.3, 1.8],
      zoom: 1.1,
    },
  },
  {
    id: 'band-pull-apart',
    name: { ko: '밴드 당겨 벌리기', en: 'Band pull-apart' },
    phase: 'activate',
    position: 'standing',
    regions: ['upperBack', 'shoulder'],
    targets: { roundShoulder: 0.9, kyphosis: 0.5, upperBackPain: 0.4 },
    equipment: ['band'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 15, tempo: 2.5, holdSec: 1, rest: 20 },
    steps: {
      ko: ['밴드를 어깨너비로 잡고 팔을 가슴 높이로 앞으로 뻗어요.', '날개뼈를 모으며 밴드가 가슴에 닿을 듯 양옆으로 벌려요.', '1초 버티고 천천히 돌아와요.'],
      en: ['Hold a band shoulder-width apart with arms straight in front at chest height.', 'Squeeze your shoulder blades and pull the band apart toward your chest.', 'Pause 1 second and return slowly.'],
    },
    cues: { ko: ['날개뼈 먼저 모아요', '어깨는 아래로'], en: ['Blades first', 'Shoulders down'] },
    mistakes: { ko: ['어깨가 올라감', '허리를 젖힘'], en: ['Shrugging', 'Arching the back'] },
    why: { ko: '등 뒤쪽 근육을 저항을 이용해 확실히 강화해요. 벽 천사가 쉬워졌다면 다음 단계예요.', en: 'Strengthens the back of the shoulders against resistance — the next step once wall angels feel easy.' },
    muscles: { ko: '후면 삼각근, 능형근, 중부 승모근', en: 'Rear delts, rhomboids, middle trapezius' },
    anim: {
      view: 30,
      elev: 22,
      props: [{ kind: 'band', at: 'wrL', to: 'wrR' }],
      keys: [merge(STAND, both({ sh: { flex: 86, hab: -6 }, el: 4 })), merge(STAND, both({ sh: { flex: 86, hab: 78 }, el: 4, scap: { prot: -3 } }))],
      durations: [1.2, 1.3],
      pauses: [0.2, 0.8],
    },
  },
  {
    id: 'open-book',
    name: { ko: '오픈북 (등 돌리기)', en: 'Open book' },
    phase: 'mobility',
    position: 'sideLying',
    regions: ['upperBack', 'chest'],
    targets: { kyphosis: 0.8, upperBackPain: 0.8, roundShoulder: 0.6, stiffness: 0.5 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 5, perSide: true, rest: 10 },
    steps: {
      ko: ['왼쪽으로 누워 무릎을 90°로 굽히고 양팔을 앞으로 모아요.', '위쪽 팔을 천장 → 반대쪽 바닥으로, 책을 펼치듯 열어요.', '시선은 손을 따라가고 무릎은 서로 붙인 채 유지해요.', '숨을 내쉬며 열고, 들이쉬며 돌아와요.'],
      en: ['Lie on your left side, knees bent 90°, arms together in front.', 'Open your top arm up and over to the floor behind you, like opening a book.', 'Follow your hand with your eyes and keep your knees together.', 'Exhale as you open, inhale as you return.'],
    },
    cues: { ko: ['무릎은 붙인 채', '시선은 손을 따라', '숨을 내쉬며 열어요'], en: ['Knees stay together', 'Eyes follow the hand', 'Exhale to open'] },
    mistakes: { ko: ['무릎이 같이 넘어감', '팔만 억지로 넘김'], en: ['Knees rolling open', 'Forcing just the arm'] },
    why: { ko: '앉아 있는 동안 굳는 흉추의 회전을 되살려 등 뻐근함을 풀고 호흡을 깊게 해요.', en: 'Restores rotation to a stiff upper spine, easing back tightness and deepening your breath.' },
    muscles: { ko: '흉추 회전 가동성, 대흉근', en: 'Thoracic rotation, pecs' },
    anim: {
      view: 0,
      elev: 62,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [
        merge(SIDE_LYING, both({ hip: { flex: 90 }, kn: 90 }), both({ sh: { flex: 88 }, el: 0 }), { neck: { side: -6 } }),
        merge(SIDE_LYING, both({ hip: { flex: 90 }, kn: 90 }), { shL: { flex: 88 }, elL: 0, shR: { flex: 88, hab: 120 }, elR: 5, thorax: { twist: -55 }, lumbar: { twist: -10 }, neck: { twist: -40, side: -6 } }),
      ],
      durations: [2.2, 2.2],
      pauses: [0.3, 1.2],
    },
  },
  {
    id: 'thread-needle',
    name: { ko: '스레드 더 니들', en: 'Thread the needle' },
    phase: 'mobility',
    position: 'quadruped',
    regions: ['upperBack', 'shoulder'],
    targets: { upperBackPain: 0.7, kyphosis: 0.6, stiffness: 0.5, roundShoulder: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 6, tempo: 5, perSide: true, rest: 10 },
    steps: {
      ko: ['네발 자세에서 오른팔을 천장으로 뻗으며 가슴을 오른쪽으로 열어요.', '이번엔 오른팔을 왼팔 아래로 실을 꿰듯 깊숙이 넣어요.', '오른쪽 어깨와 귀를 바닥 가까이 내려 등 윗부분을 비틀어요.', '천천히 열고 닫기를 반복해요.'],
      en: ['From all fours, reach your right arm to the ceiling, opening your chest to the right.', 'Then thread the right arm under your left arm, deep across the floor.', 'Let your right shoulder and ear sink toward the floor to twist the upper back.', 'Open and close slowly.'],
    },
    cues: { ko: ['시선은 손끝을 따라', '골반은 가운데 고정'], en: ['Eyes follow your hand', 'Keep the hips centred'] },
    mistakes: { ko: ['골반이 옆으로 빠짐', '허리로 비틈'], en: ['Hips swaying sideways', 'Twisting from the low back'] },
    why: { ko: '어깨뼈 사이 뻐근함을 풀고 흉추 회전을 되찾아 줘요.', en: 'Releases tension between the shoulder blades and restores upper-back rotation.' },
    muscles: { ko: '능형근, 흉추 회전근', en: 'Rhomboids, thoracic rotators' },
    avoid: ['wristPain', 'kneePain'],
    anim: {
      view: 90,
      elev: 20,
      props: [{ kind: 'mat' }],
      anchor: ['knL', 'knR'],
      keys: [
        merge(QUAD, { shR: { flex: 60, abd: 110 }, elR: 5, thorax: { twist: -42 }, neck: { twist: -30 } }),
        merge(QUAD, { shR: { flex: 95, abd: -70, rot: -20 }, elR: 5, thorax: { twist: 32, flex: 6 }, shL: { flex: 88 }, elL: 20, neck: { twist: 20 } }),
      ],
      durations: [2.4, 2.4],
      pauses: [0.6, 1.2],
    },
  },
  {
    id: 'foam-roller-tspine',
    name: { ko: '폼롤러 등 펴기', en: 'Foam roller thoracic extension' },
    phase: 'mobility',
    position: 'supine',
    regions: ['upperBack'],
    targets: { kyphosis: 1, roundShoulder: 0.6, upperBackPain: 0.7, fhp: 0.3 },
    equipment: ['foamRoller', 'mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 4, holdSec: 2, rest: 15 },
    steps: {
      ko: ['폼롤러를 날개뼈 아래에 가로로 두고 무릎을 세워 누워요.', '양손으로 머리를 받쳐 목에 힘을 빼요.', '숨을 내쉬며 폼롤러를 받침 삼아 등 윗부분을 뒤로 젖혀요.', '2초 멈췄다 돌아와요. 폼롤러를 한 칸씩 위로 옮겨 가며 반복해요.'],
      en: ['Lie with a foam roller across your back just below the shoulder blades, knees bent.', 'Support your head with your hands and relax your neck.', 'Exhale and extend your upper back over the roller.', 'Pause 2 seconds and return. Move the roller up one notch at a time.'],
    },
    cues: { ko: ['엉덩이는 바닥에', '숨을 내쉬며 젖혀요'], en: ['Hips stay down', 'Exhale and extend'] },
    mistakes: { ko: ['허리 아래(요추)에서 굴림', '엉덩이를 듦'], en: ['Rolling under the low back', 'Lifting the hips'] },
    why: { ko: '굳은 흉추 관절을 한 마디씩 펴 주는 가장 확실한 도구 운동이에요.', en: 'The most effective tool-based way to extend the stiff upper spine, segment by segment.' },
    muscles: { ko: '흉추 신전 가동성', en: 'Thoracic extension mobility' },
    caution: { ko: '골다공증이 있거나 등에 날카로운 통증이 있으면 생략하세요.', en: 'Skip if you have osteoporosis or sharp back pain.' },
    avoid: ['pregnant'],
    anim: {
      view: 90,
      elev: 10,
      props: [{ kind: 'mat' }, { kind: 'roller', at: 'backTop', off: [0, -7, 1] }],
      anchor: ['pelvis'],
      keys: [merge(HOOK, HANDS_BEHIND_HEAD, { root: { pitch: -72 }, thorax: { flex: 8 }, neck: { flex: 8 } }), merge(HOOK, HANDS_BEHIND_HEAD, { root: { pitch: -72 }, thorax: { flex: -26 }, neck: { flex: 2 } })],
      durations: [1.8, 1.8],
      pauses: [0.3, 1.2],
    },
  },
  {
    id: 'wrist-stretch',
    name: { ko: '손목 앞뒤 스트레칭', en: 'Wrist flexor & extensor stretch' },
    phase: 'stretch',
    position: 'standing',
    regions: ['wrist'],
    targets: { wristPain: 1, stiffness: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 20, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['오른팔을 앞으로 쭉 펴고 손바닥이 앞을 향하게 손목을 젖혀요.', '왼손으로 오른손 손가락을 몸 쪽으로 부드럽게 당겨 20초.', '이번엔 손등이 앞을 향하게 손목을 구부려 같은 방법으로 20초.'],
      en: ['Straighten your right arm in front, palm facing away, wrist bent back.', 'Gently pull the fingers toward you with your left hand for 20 seconds.', 'Then flip: bend the wrist down, back of the hand forward, and hold 20 seconds.'],
    },
    cues: { ko: ['팔꿈치는 쭉 펴고', '부드럽게 당겨요'], en: ['Keep the elbow straight', 'Gentle pull'] },
    mistakes: { ko: ['세게 꺾음', '팔꿈치를 굽힘'], en: ['Cranking the wrist', 'Bending the elbow'] },
    why: { ko: '마우스·키보드·스마트폰으로 굳은 아래팔 근육을 풀어 손목 통증과 팔꿈치 부담을 줄여요.', en: 'Loosens forearm muscles tightened by mouse, keyboard and phone use, easing wrist and elbow strain.' },
    muscles: { ko: '손목 굽힘근·폄근', en: 'Wrist flexors & extensors' },
    anim: {
      view: 35,
      keys: [
        merge(STAND, { shR: { flex: 88, abd: 4 }, elR: 2, wrR: -10, shL: { flex: 70, abd: -30 }, elL: 40 }),
        merge(STAND, { shR: { flex: 88, abd: 4 }, elR: 2, wrR: -70, shL: { flex: 75, abd: -38 }, elL: 30 }),
      ],
      durations: [1.2, 1.2],
      pauses: [0.4, 2.4],
      zoom: 1.1,
    },
  },
];
