/**
 * 운동 라이브러리 ② 허리 · 코어 · 고관절 · 무릎 · 통합 동작
 */
import { both } from '../figure/rig';
import { HALF_KNEEL, HOOK, merge, QUAD, SIDE_LYING, SIT, STAND, SUPINE, WALL } from '../figure/poses';
import type { Exercise } from './exercise-types';

const HANDS_ON_HIPS = both({ sh: { abd: 38, flex: -10, rot: -20 }, el: 105 });
const ARMS_CROSSED = merge(both({ sh: { flex: 42, abd: -12 }, el: 128 }));

export const LOWER: Exercise[] = [
  {
    id: 'glute-bridge',
    name: { ko: '글루트 브릿지', en: 'Glute bridge' },
    phase: 'activate',
    position: 'supine',
    regions: ['glute', 'core', 'lowBack'],
    targets: { lordosis: 0.8, swayback: 0.6, lowBackPain: 0.6, kneeValgus: 0.4, kneeHyperext: 0.3, hipPain: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 12, tempo: 3, holdSec: 2, rest: 20 },
    steps: {
      ko: ['무릎을 세우고 누워 발을 골반 너비로 벌려요.', '숨을 내쉬며 배에 힘을 주고 꼬리뼈부터 말아 올리듯 엉덩이를 들어요.', '어깨-골반-무릎이 일직선이 되면 엉덩이를 꽉 조이고 2초.', '허리를 과하게 젖히지 말고 천천히 내려요.'],
      en: ['Lie on your back with knees bent and feet hip-width apart.', 'Exhale, brace your belly and peel your hips up, tailbone first.', 'When shoulders, hips and knees form a line, squeeze your glutes for 2 seconds.', 'Don’t over-arch; lower slowly.'],
    },
    cues: { ko: ['엉덩이 꽉!', '허리 말고 엉덩이로', '천천히 내려요'], en: ['Squeeze the glutes!', 'Hips, not low back', 'Lower slowly'] },
    mistakes: { ko: ['허리를 과하게 젖힘', '무릎이 안쪽으로 모임', '햄스트링에 쥐가 남(발을 몸 쪽으로)'], en: ['Over-arching the back', 'Knees caving in', 'Hamstring cramps (bring feet closer)'] },
    why: { ko: '오래 앉아 잠든 엉덩이 근육을 깨워 골반을 바로 세우고 허리 부담을 덜어 줘요. 오리형 교정의 핵심이에요.', en: 'Wakes up glutes switched off by sitting, levelling the pelvis and unloading the low back — the core of the Duck fix.' },
    muscles: { ko: '대둔근, 햄스트링, 복부', en: 'Gluteus maximus, hamstrings, abs' },
    anim: {
      view: 90,
      elev: 10,
      props: [{ kind: 'mat' }],
      anchor: ['heelL', 'heelR'],
      level: { a: ['backTop'], b: ['heelL', 'heelR'] },
      keys: [
        merge(HOOK, both({ sh: { flex: 0, abd: 8 }, el: 0 })),
        merge(HOOK, { root: { pitch: -114 } }, both({ hip: { flex: -2 }, kn: 102, an: 8, sh: { flex: -24, abd: 8 }, el: 0 })),
      ],
      durations: [1.4, 1.4],
      pauses: [0.4, 2],
    },
    coach: {
      view: 'side',
      metric: 'hipAngle',
      mode: 'reps',
      rest: 140,
      peak: 162,
      dir: 1,
      hint: { ko: '옆에서 온몸이 보이도록 휴대폰을 바닥 높이에 두세요', en: 'Place the phone at floor level beside you so your whole body is visible' },
      more: { ko: '엉덩이를 조금 더 높이', en: 'Hips a little higher' },
      good: { ko: '좋아요, 꽉 조여요', en: 'Great, squeeze' },
    },
  },
  {
    id: 'dead-bug',
    name: { ko: '데드버그', en: 'Dead bug' },
    phase: 'activate',
    position: 'supine',
    regions: ['core', 'lowBack'],
    targets: { lordosis: 0.9, lowBackPain: 0.6, swayback: 0.5, lateralShift: 0.2 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 4, perSide: true, rest: 20 },
    steps: {
      ko: ['누워서 팔은 천장으로, 무릎은 90°로 들어 올려 테이블 자세를 만들어요.', '허리를 바닥에 지그시 누른 채 오른팔과 왼다리를 천천히 뻗어요.', '허리가 뜨기 직전까지만 내렸다가 숨을 내쉬며 돌아와요.', '반대쪽(왼팔·오른다리)도 같은 방법으로.'],
      en: ['Lie on your back, arms to the ceiling, hips and knees at 90° (tabletop).', 'Press your low back gently into the floor and slowly extend the right arm and left leg.', 'Go only as low as your back can stay down, then return on an exhale.', 'Repeat with the left arm and right leg.'],
    },
    cues: { ko: ['허리는 바닥에', '천천히 뻗어요', '숨을 내쉬며 돌아와요'], en: ['Back stays down', 'Reach slowly', 'Exhale back in'] },
    mistakes: { ko: ['허리가 바닥에서 뜸', '너무 빠르게 움직임', '숨을 참음'], en: ['Low back arching up', 'Moving too fast', 'Holding the breath'] },
    why: { ko: '팔다리가 움직여도 허리를 중립으로 지키는 깊은 코어 조절력을 길러, 허리 과전만과 요통을 줄여요.', en: 'Builds deep-core control to keep your spine neutral while the limbs move, reducing over-arching and back pain.' },
    muscles: { ko: '복횡근, 복직근, 내·외복사근', en: 'Transversus abdominis, rectus abdominis, obliques' },
    avoid: ['pregnant', 'lowBackSevere'],
    anim: {
      view: 90,
      elev: 12,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [
        merge(SUPINE, both({ hip: { flex: 90 }, kn: 90, an: 0, sh: { flex: 90 }, el: 2 })),
        merge(SUPINE, both({ an: 0 }), { hipL: { flex: 22 }, knL: 12, hipR: { flex: 90 }, knR: 90, shR: { flex: 172 }, elR: 2, shL: { flex: 90 }, elL: 2 }),
      ],
      durations: [2, 2],
      pauses: [0.4, 0.6],
    },
  },
  {
    id: 'bird-dog',
    name: { ko: '버드독', en: 'Bird dog' },
    phase: 'activate',
    position: 'quadruped',
    regions: ['core', 'lowBack', 'glute'],
    targets: { lowBackPain: 0.8, lordosis: 0.5, lateralShift: 0.4, pelvicTilt: 0.3, swayback: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 4, holdSec: 3, perSide: true, rest: 15 },
    steps: {
      ko: ['네발 자세에서 손목은 어깨 아래, 무릎은 골반 아래에 둬요.', '배에 살짝 힘을 주고 오른팔은 앞으로, 왼다리는 뒤로 쭉 뻗어요.', '등 위에 물컵이 있다고 생각하고 골반이 돌아가지 않게 3초 버텨요.', '천천히 돌아와 반대쪽도.'],
      en: ['On all fours, wrists under shoulders, knees under hips.', 'Brace lightly and reach the right arm forward and left leg back.', 'Imagine a glass of water on your back — keep the pelvis level for 3 seconds.', 'Return slowly and switch sides.'],
    },
    cues: { ko: ['골반은 수평', '멀리 뻗어요', '허리가 처지지 않게'], en: ['Pelvis level', 'Reach long', 'Don’t let the back sag'] },
    mistakes: { ko: ['다리를 너무 높이 들어 허리가 꺾임', '골반이 옆으로 기울어짐'], en: ['Lifting the leg too high and arching', 'Hips tipping to the side'] },
    why: { ko: '허리 부담은 최소로, 척추를 지탱하는 등·엉덩이·코어를 함께 강화해요. 요통 재활에서 가장 많이 쓰는 운동 중 하나예요(McGill Big 3).', en: 'Trains the back, glutes and core together with minimal spinal load — one of McGill’s “Big 3” for back pain.' },
    muscles: { ko: '척추기립근, 다열근, 대둔근, 복부', en: 'Erector spinae, multifidus, glutes, abs' },
    avoid: ['wristPain', 'kneePain'],
    anim: {
      view: 90,
      elev: 14,
      props: [{ kind: 'mat' }],
      anchor: ['knL', 'knR'],
      keys: [QUAD, merge(QUAD, { shR: { flex: 168 }, elR: 2, wrR: 0, hipL: { flex: -12 }, knL: 4, anL: -20, neck: { flex: -8 } })],
      durations: [1.8, 1.8],
      pauses: [0.3, 2.4],
    },
  },
  {
    id: 'cat-cow',
    name: { ko: '고양이-소 자세', en: 'Cat-cow' },
    phase: 'mobility',
    position: 'quadruped',
    regions: ['lowBack', 'upperBack'],
    targets: { stiffness: 0.8, lowBackPain: 0.6, kyphosis: 0.4, lordosis: 0.3, stress: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 5, rest: 10 },
    steps: {
      ko: ['네발 자세에서 손목은 어깨 아래, 무릎은 골반 아래에 둬요.', '숨을 내쉬며 배꼽을 당겨 등을 둥글게 말아요(고양이).', '숨을 들이쉬며 가슴을 앞으로 내밀고 꼬리뼈를 들어 등을 오목하게(소).', '통증 없는 범위에서 척추 마디마디를 느끼며 천천히.'],
      en: ['On all fours, wrists under shoulders, knees under hips.', 'Exhale, draw your belly in and round your back (cat).', 'Inhale, lift your chest and tailbone, letting the back dip (cow).', 'Move slowly through a pain-free range, one vertebra at a time.'],
    },
    cues: { ko: ['내쉬며 둥글게', '들이쉬며 오목하게', '천천히'], en: ['Exhale, round', 'Inhale, arch', 'Nice and slow'] },
    mistakes: { ko: ['팔꿈치를 굽혀 움직임', '목만 크게 움직임'], en: ['Bending the elbows', 'Moving only the neck'] },
    why: { ko: '오래 같은 자세로 굳은 척추 전체를 부드럽게 움직여 뻐근함을 풀고 호흡과 움직임을 연결해요.', en: 'Gently moves the whole spine after long static postures, easing stiffness and linking breath with movement.' },
    muscles: { ko: '척추 전체 가동성', en: 'Whole-spine mobility' },
    avoid: ['wristPain', 'kneePain'],
    anim: {
      view: 90,
      elev: 14,
      props: [{ kind: 'mat' }],
      anchor: ['knL', 'knR'],
      keys: [
        merge(QUAD, { lumbar: { flex: 16 }, thorax: { flex: 20 }, neck: { flex: 26 }, root: { pitch: 76 } }, both({ sh: { flex: 112 }, hip: { flex: 76 } })),
        merge(QUAD, { lumbar: { flex: -16 }, thorax: { flex: -8 }, neck: { flex: -30 }, root: { pitch: 84 } }, both({ sh: { flex: 60 }, hip: { flex: 84 } })),
      ],
      durations: [2.4, 2.4],
      pauses: [0.3, 0.3],
    },
  },
  {
    id: 'child-pose',
    name: { ko: '아기 자세', en: 'Child’s pose' },
    phase: 'stretch',
    position: 'kneeling',
    regions: ['lowBack', 'upperBack', 'hip'],
    targets: { lowBackPain: 0.6, stiffness: 0.6, stress: 0.5, kyphosis: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, rest: 5 },
    steps: {
      ko: ['무릎을 꿇고 앉아 엉덩이를 발뒤꿈치 쪽으로 내려요.', '팔을 앞으로 길게 뻗어 이마를 바닥 가까이 내려요.', '숨을 등 쪽으로 불어 넣듯 깊게 쉬며 30초 머물러요.'],
      en: ['Kneel and sink your hips back toward your heels.', 'Reach your arms long in front and let your forehead lower toward the floor.', 'Breathe deeply into your back and rest for 30 seconds.'],
    },
    cues: { ko: ['엉덩이는 뒤꿈치로', '등으로 숨 쉬어요'], en: ['Hips to heels', 'Breathe into your back'] },
    mistakes: { ko: ['무릎 통증을 참음(방석을 받쳐요)'], en: ['Pushing through knee pain (use a cushion)'] },
    why: { ko: '허리와 등을 부드럽게 늘리며 긴장을 내려놓는 휴식 자세예요. 루틴 사이사이 쉬기에도 좋아요.', en: 'A resting stretch that gently lengthens the back and lets tension go — great between harder moves.' },
    muscles: { ko: '광배근, 척추기립근, 둔근', en: 'Lats, spinal erectors, glutes' },
    avoid: ['kneePain', 'kneeSevere'],
    anim: {
      view: 90,
      elev: 12,
      props: [{ kind: 'mat' }],
      anchor: ['knL', 'knR'],
      keys: [
        merge({ root: { pitch: 0 } }, both({ hip: { flex: 70 }, kn: 160, an: -75, sh: { flex: 168 }, el: 5 })),
        merge({ root: { pitch: 80 } }, both({ hip: { flex: 150 }, kn: 160, an: -75, sh: { flex: 192 }, el: 2 }), { lumbar: { flex: 22 }, thorax: { flex: 12 }, neck: { flex: 10 } }),
      ],
      durations: [2, 2],
      pauses: [0.3, 3],
    },
  },
  {
    id: 'half-kneel-hip-flexor',
    name: { ko: '하프 닐링 고관절 앞 스트레칭', en: 'Half-kneeling hip flexor stretch' },
    phase: 'stretch',
    position: 'kneeling',
    regions: ['hip', 'lowBack'],
    targets: { lordosis: 1, swayback: 0.5, lowBackPain: 0.5, kneeHyperext: 0.2 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    steps: {
      ko: ['오른무릎을 바닥에 대고 왼발은 앞에 두는 한쪽 무릎 꿇기 자세를 만들어요.', '꼬리뼈를 아래로 말아 골반을 세우고 오른쪽 엉덩이를 꽉 조여요.', '그대로 몸을 앞으로 살짝 옮겨 오른쪽 고관절 앞이 늘어나면 30초.', '허리를 젖히지 않는 것이 핵심이에요.'],
      en: ['Kneel on your right knee with the left foot in front.', 'Tuck your tailbone under and squeeze your right glute.', 'Shift your body forward slightly until the front of the right hip stretches; hold 30 seconds.', 'The key is not to arch your low back.'],
    },
    cues: { ko: ['꼬리뼈를 아래로', '엉덩이를 조여요', '허리는 젖히지 않게'], en: ['Tailbone down', 'Squeeze the glute', 'No arching'] },
    mistakes: { ko: ['허리를 젖혀 늘리는 척', '앞무릎이 발끝을 한참 넘어감'], en: ['Arching to fake the stretch', 'Front knee far past the toes'] },
    why: { ko: '오래 앉아 짧아진 장요근이 골반을 앞으로 당겨 허리를 휘게 만들어요. 오리궁둥이·요통 교정의 필수 스트레칭이에요.', en: 'Hip flexors shortened by sitting pull the pelvis forward and arch the back — a must-do stretch for anterior tilt and back pain.' },
    muscles: { ko: '장요근, 대퇴직근', en: 'Iliopsoas, rectus femoris' },
    caution: { ko: '무릎이 아프면 수건을 접어 받치거나 ‘서서 고관절 앞 늘리기’로 대신하세요.', en: 'If the knee hurts, pad it with a towel or do the standing version instead.' },
    avoid: ['kneePain', 'kneeSevere'],
    anim: {
      view: 90,
      props: [{ kind: 'mat' }],
      anchor: ['knR'],
      keys: [merge(HALF_KNEEL, HANDS_ON_HIPS), merge(HALF_KNEEL, HANDS_ON_HIPS, { hipL: { flex: 70 }, knL: 102, anL: 30, hipR: { flex: -28 }, knR: 64, lumbar: { flex: 4 } })],
      durations: [1.8, 1.8],
      pauses: [0.5, 3],
    },
  },
  {
    id: 'standing-hip-flexor',
    name: { ko: '서서 고관절 앞 늘리기', en: 'Standing hip flexor stretch' },
    phase: 'stretch',
    position: 'standing',
    regions: ['hip'],
    targets: { lordosis: 0.8, swayback: 0.4, lowBackPain: 0.4 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['왼발을 앞으로 크게 한 걸음 내딛고 오른발 뒤꿈치는 들어요.', '꼬리뼈를 말아 넣고 오른쪽 엉덩이를 조여요.', '앞무릎을 살짝 굽히며 골반을 앞으로 보내요.', '오른쪽 허벅지 앞~사타구니가 당기면 30초.'],
      en: ['Take a big step forward with the left foot; lift the right heel.', 'Tuck your tailbone and squeeze the right glute.', 'Bend the front knee a little and move your pelvis forward.', 'Hold 30 seconds when you feel the front of the right hip stretch.'],
    },
    cues: { ko: ['꼬리뼈를 아래로', '상체는 곧게'], en: ['Tailbone down', 'Upper body tall'] },
    mistakes: { ko: ['허리를 뒤로 젖힘', '골반이 돌아감'], en: ['Leaning back through the spine', 'Rotating the pelvis'] },
    why: { ko: '무릎을 꿇기 어려운 사무실에서도 할 수 있는 고관절 굴곡근 스트레칭이에요.', en: 'A hip-flexor stretch you can do at the office without kneeling.' },
    muscles: { ko: '장요근, 대퇴직근', en: 'Iliopsoas, rectus femoris' },
    anim: {
      view: 90,
      anchor: ['toeR'],
      keys: [
        merge(STAND, HANDS_ON_HIPS, { hipL: { flex: 24 }, knL: 10, hipR: { flex: -18 }, knR: 6, anR: -14 }),
        merge(STAND, HANDS_ON_HIPS, { hipL: { flex: 30 }, knL: 34, anL: 14, hipR: { flex: -30 }, knR: 10, anR: -24, lumbar: { flex: 4 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.5, 3],
    },
  },
  {
    id: 'figure4-stretch',
    name: { ko: '의자 4자 엉덩이 스트레칭', en: 'Seated figure-4 stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['glute', 'hip', 'lowBack'],
    targets: { hipPain: 0.8, lowBackPain: 0.6, pelvicTilt: 0.4, stiffness: 0.4 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자에 앉아 오른발목을 왼무릎 위에 올려 숫자 4 모양을 만들어요.', '허리를 곧게 편 채 가슴을 앞으로 천천히 숙여요.', '오른쪽 엉덩이 깊은 곳이 당기면 30초 유지해요.'],
      en: ['Sit and cross your right ankle over your left knee to make a “4”.', 'Keep your back long and slowly hinge your chest forward.', 'Hold 30 seconds when you feel a stretch deep in the right glute.'],
    },
    cues: { ko: ['등은 곧게', '가슴을 앞으로'], en: ['Long back', 'Chest forward'] },
    mistakes: { ko: ['등을 둥글게 말아 숙임', '무릎을 억지로 누름'], en: ['Rounding the back to fold', 'Forcing the knee down'] },
    why: { ko: '오래 앉으면 굳는 엉덩이 깊은 근육(이상근)을 풀어 골반·허리 긴장과 엉덩이 뻐근함을 줄여요.', en: 'Releases deep hip rotators like the piriformis that stiffen with sitting, easing pelvic and low-back tension.' },
    muscles: { ko: '이상근, 대둔근, 고관절 외회전근', en: 'Piriformis, gluteus maximus, hip external rotators' },
    avoid: ['kneeSevere'],
    anim: {
      view: 30,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { hipR: { flex: 96, abd: 34, rot: 62 }, knR: 104, anR: 0, shR: { flex: 30, abd: 10 }, elR: 50 }),
        merge(SIT, { hipR: { flex: 108, abd: 34, rot: 62 }, knR: 104, anR: 0, hipL: { flex: 100 }, shR: { flex: 40, abd: 10 }, elR: 40, shL: { flex: 40 }, elL: 50, lumbar: { flex: 12 }, thorax: { flex: 6 }, neck: { flex: -8 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.4, 3],
    },
  },
  {
    id: 'seated-hamstring',
    name: { ko: '의자 햄스트링 스트레칭', en: 'Seated hamstring stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['hip', 'knee'],
    targets: { kneeFlexed: 0.8, flatBack: 0.6, lowBackPain: 0.4, swayback: 0.3 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자 끝에 걸터앉아 오른다리를 앞으로 쭉 펴고 발끝을 세워요.', '허리를 편 채 골반부터 앞으로 숙여요(등을 둥글게 말지 않기).', '오른쪽 허벅지 뒤가 당기면 30초 유지해요.'],
      en: ['Sit on the edge of the chair, right leg straight out, toes up.', 'Keeping your back long, hinge forward from the hips (don’t round).', 'Hold 30 seconds when you feel the back of the right thigh stretch.'],
    },
    cues: { ko: ['골반부터 숙여요', '등은 곧게'], en: ['Hinge from the hips', 'Long back'] },
    mistakes: { ko: ['등을 말아서 숙임', '무릎을 굽힘'], en: ['Rounding the back', 'Bending the knee'] },
    why: { ko: '짧은 햄스트링은 골반을 뒤로 당겨 허리를 일자로 만들고 요통을 부를 수 있어요.', en: 'Tight hamstrings tug the pelvis backward, flattening the low back and inviting pain.' },
    muscles: { ko: '햄스트링', en: 'Hamstrings' },
    caution: { ko: '다리 뒤로 저린 느낌(신경 당김)이 나면 발끝을 내리고 강도를 줄이세요.', en: 'If you feel tingling down the leg (nerve tension), point the toes and ease off.' },
    avoid: ['radiating'],
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { hipR: { flex: 70 }, knR: 6, anR: 18 }),
        merge(SIT, { root: { pitch: 20 }, hipR: { flex: 92 }, knR: 6, anR: 18, hipL: { flex: 108 }, knL: 88 }, both({ sh: { flex: 50 }, el: 20 })),
      ],
      durations: [1.8, 1.8],
      pauses: [0.4, 3],
    },
  },
  {
    id: 'quad-stretch',
    name: { ko: '서서 허벅지 앞 스트레칭', en: 'Standing quad stretch' },
    phase: 'stretch',
    position: 'standing',
    regions: ['hip', 'knee'],
    targets: { lordosis: 0.6, kneeHyperext: 0.3, swayback: 0.3 },
    equipment: ['wall'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    steps: {
      ko: ['벽이나 의자를 왼손으로 잡고 서요.', '오른무릎을 굽혀 오른손으로 발등(또는 발목)을 잡아요.', '무릎은 아래를 향하게 하고 꼬리뼈를 말아 넣어요.', '허벅지 앞이 당기면 30초.'],
      en: ['Stand holding a wall or chair with your left hand.', 'Bend your right knee and hold the top of the foot (or ankle) with your right hand.', 'Point the knee down and tuck your tailbone.', 'Hold 30 seconds when the front of the thigh stretches.'],
    },
    cues: { ko: ['무릎은 아래로', '꼬리뼈를 말아요'], en: ['Knee points down', 'Tuck the tailbone'] },
    mistakes: { ko: ['허리를 젖힘', '무릎이 옆으로 벌어짐'], en: ['Arching the back', 'Knee drifting outward'] },
    why: { ko: '골반을 앞으로 당기는 대퇴직근을 늘려 골반 전방경사를 완화해요.', en: 'Lengthens the rectus femoris, which pulls the pelvis into anterior tilt.' },
    muscles: { ko: '대퇴사두근(대퇴직근)', en: 'Quadriceps (rectus femoris)' },
    caution: { ko: '무릎이 아프면 수건을 발목에 걸어 당기세요.', en: 'If your knee hurts, loop a towel around the ankle instead.' },
    avoid: ['kneeSevere', 'balance'],
    anim: {
      view: 90,
      props: [{ kind: 'wall', wall: 'front', dist: 12 }],
      keys: [
        merge(STAND, { shL: { flex: 80 }, elL: 10 }),
        merge(STAND, { shL: { flex: 80 }, elL: 10, hipR: { flex: -8 }, knR: 145, anR: -30, shR: { flex: -42, abd: 10 }, elR: 8, lumbar: { flex: 3 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.4, 3],
    },
  },
  {
    id: 'calf-stretch',
    name: { ko: '벽 종아리 스트레칭', en: 'Wall calf stretch' },
    phase: 'stretch',
    position: 'wall',
    regions: ['ankle', 'knee'],
    targets: { kneeHyperext: 0.4, kneeValgus: 0.3, stiffness: 0.3 },
    equipment: ['wall'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['벽을 마주 보고 두 손을 벽에 대요.', '오른다리를 뒤로 한 걸음 빼고 발뒤꿈치를 바닥에 붙여요.', '앞무릎을 굽히며 몸을 벽 쪽으로 기울여요.', '오른쪽 종아리가 당기면 30초.'],
      en: ['Face a wall with both hands on it.', 'Step your right leg back and keep the heel down.', 'Bend the front knee and lean toward the wall.', 'Hold 30 seconds when the right calf stretches.'],
    },
    cues: { ko: ['뒤꿈치는 바닥에', '뒷무릎은 쭉'], en: ['Heel down', 'Back knee straight'] },
    mistakes: { ko: ['뒤꿈치가 뜸', '발끝이 바깥을 향함'], en: ['Heel lifting', 'Toes turning out'] },
    why: { ko: '종아리가 짧으면 무릎이 안쪽으로 무너지거나 뒤로 꺾이기 쉬워요.', en: 'Tight calves make the knees cave in or lock back more easily.' },
    muscles: { ko: '비복근, 가자미근', en: 'Gastrocnemius, soleus' },
    anim: {
      view: 90,
      props: [{ kind: 'wall', wall: 'front', dist: 2 }],
      anchor: ['heelR'],
      keys: [
        merge({ root: { pitch: 10 } }, both({ sh: { flex: 92 }, el: 18 }), { hipL: { flex: 30 }, knL: 16, anL: 4, hipR: { flex: -10 }, knR: 0, anR: 12 }),
        merge({ root: { pitch: 18 } }, both({ sh: { flex: 96 }, el: 40 }), { hipL: { flex: 44 }, knL: 40, anL: 12, hipR: { flex: -18 }, knR: 0, anR: 24 }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.4, 3],
    },
  },
  {
    id: 'butterfly',
    name: { ko: '나비 자세 (허벅지 안쪽)', en: 'Butterfly stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['hip'],
    targets: { kneeValgus: 0.6, hipPain: 0.4, pelvicTilt: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, rest: 5 },
    steps: {
      ko: ['바닥에 앉아 두 발바닥을 마주 붙이고 무릎을 옆으로 떨어뜨려요.', '발을 두 손으로 잡고 허리를 곧게 세워요.', '숨을 내쉬며 가슴을 앞으로 살짝 숙여요.', '허벅지 안쪽이 당기면 30초.'],
      en: ['Sit with the soles of your feet together, knees falling out.', 'Hold your feet and sit up tall.', 'Exhale and lean your chest forward a little.', 'Hold 30 seconds when your inner thighs stretch.'],
    },
    cues: { ko: ['허리는 곧게', '무릎은 힘을 빼요'], en: ['Tall spine', 'Let the knees relax'] },
    mistakes: { ko: ['무릎을 손으로 억지로 누름', '등을 둥글게 말기'], en: ['Pushing the knees down', 'Rounding the back'] },
    why: { ko: '짧아진 내전근은 무릎을 안쪽으로 끌어 X다리 경향을 키워요.', en: 'Tight adductors pull the knees inward and feed knock-knee alignment.' },
    muscles: { ko: '고관절 내전근', en: 'Hip adductors' },
    avoid: ['kneeSevere'],
    anim: {
      view: 0,
      elev: 34,
      props: [{ kind: 'mat' }],
      anchor: ['sitL', 'sitR'],
      keys: [
        merge({ root: { pitch: -8 } }, both({ hip: { flex: 84, hab: 46, rot: 80 }, kn: 128, an: 10, sh: { flex: 46, hab: -10 }, el: 30 })),
        merge({ root: { pitch: 6 } }, both({ hip: { flex: 84, hab: 56, rot: 84 }, kn: 128, an: 10, sh: { flex: 58, hab: -8 }, el: 22 }), { lumbar: { flex: 10 }, thorax: { flex: 6 } }),
      ],
      durations: [1.8, 1.8],
      pauses: [0.4, 3],
    },
  },
  {
    id: 'standing-side-bend',
    name: { ko: '서서 옆구리 늘리기', en: 'Standing side bend' },
    phase: 'stretch',
    position: 'standing',
    regions: ['lowBack', 'core'],
    targets: { pelvicTilt: 0.8, lateralShift: 0.8, lowBackPain: 0.4, stiffness: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 20, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['발을 골반 너비로 벌리고 서요.', '왼팔을 머리 위로 쭉 뻗어요.', '골반은 제자리에 둔 채 상체를 오른쪽으로 천천히 기울여요.', '왼쪽 옆구리가 길게 늘어나면 20초.'],
      en: ['Stand with feet hip-width apart.', 'Reach your left arm overhead.', 'Keeping the pelvis still, slowly bend your upper body to the right.', 'Hold 20 seconds when the left side lengthens.'],
    },
    cues: { ko: ['위로 길게, 옆으로', '골반은 가운데'], en: ['Up long, then over', 'Pelvis stays centred'] },
    mistakes: { ko: ['몸이 앞으로 숙여짐', '골반이 옆으로 빠짐'], en: ['Leaning forward', 'Hips sliding sideways'] },
    why: { ko: '한쪽 허리 옆(요방형근)이 짧아지면 골반 높이가 달라져요. 높은 쪽 골반과 같은 쪽 옆구리를 더 늘려 주세요.', en: 'A short quadratus lumborum hitches one side of the pelvis. Stretch the side of the higher hip a bit more.' },
    muscles: { ko: '요방형근, 광배근, 복사근', en: 'Quadratus lumborum, lats, obliques' },
    anim: {
      view: 0,
      keys: [merge(STAND, { shL: { abd: 160 }, elL: 12 }), merge(STAND, { shL: { abd: 172 }, elL: 10, lumbar: { side: -12 }, thorax: { side: -15 }, neck: { side: -4 } })],
      durations: [1.6, 1.6],
      pauses: [0.4, 3],
    },
    coach: {
      view: 'front',
      metric: 'trunkSide',
      mode: 'hold',
      target: 10,
      dir: 1,
      hint: { ko: '정면에서 온몸이 보이게 휴대폰을 세워 주세요', en: 'Prop the phone in front so your whole body is visible' },
      more: { ko: '조금 더 옆으로', en: 'A bit further to the side' },
      good: { ko: '좋아요, 그대로', en: 'Great, stay there' },
    },
  },
  {
    id: 'pelvic-tilt',
    name: { ko: '누워서 골반 기울이기', en: 'Supine pelvic tilt' },
    phase: 'mobility',
    position: 'supine',
    regions: ['lowBack', 'core'],
    targets: { lordosis: 0.7, lowBackPain: 0.6, swayback: 0.4, flatBack: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 4, rest: 10 },
    steps: {
      ko: ['무릎을 세우고 누워요.', '숨을 들이쉬며 허리를 살짝 띄워 골반을 앞으로 기울여요.', '숨을 내쉬며 배꼽을 당겨 허리를 바닥에 지그시 붙여요(꼬리뼈가 살짝 들림).', '천천히 시소처럼 반복해요.'],
      en: ['Lie on your back with knees bent.', 'Inhale and gently arch your low back, tipping the pelvis forward.', 'Exhale, draw your belly in and press your low back into the floor (tailbone lifts slightly).', 'Rock slowly back and forth like a seesaw.'],
    },
    cues: { ko: ['들이쉬며 오목', '내쉬며 꾹'], en: ['Inhale, arch', 'Exhale, flatten'] },
    mistakes: { ko: ['엉덩이를 들어 올림', '다리 힘으로 밀기'], en: ['Lifting the hips', 'Pushing with the legs'] },
    why: { ko: '골반 위치를 스스로 조절하는 감각을 되찾는 첫 단계예요. 허리가 뻐근한 날 가장 먼저 해 보세요.', en: 'The first step to feeling and controlling your pelvic position — try it first on a stiff-back day.' },
    muscles: { ko: '복부, 골반 주변 근육 조절', en: 'Abdominal & pelvic control' },
    anim: {
      view: 90,
      elev: 12,
      props: [{ kind: 'mat' }],
      anchor: ['heelL', 'heelR'],
      keys: [merge(HOOK, { root: { pitch: -80 }, lumbar: { flex: -10 } }, both({ hip: { flex: 65 } })), merge(HOOK, { root: { pitch: -99 }, lumbar: { flex: 9 } }, both({ hip: { flex: 46 } }))],
      durations: [2, 2],
      pauses: [0.3, 0.6],
      zoom: 1.15,
    },
  },
  {
    id: 'clamshell',
    name: { ko: '클램쉘', en: 'Clamshell' },
    phase: 'activate',
    position: 'sideLying',
    regions: ['glute', 'hip'],
    targets: { kneeValgus: 1, pelvicTilt: 0.6, hipPain: 0.5, lateralShift: 0.4 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 15, tempo: 2.5, holdSec: 1, perSide: true, rest: 15 },
    steps: {
      ko: ['왼쪽으로 누워 무릎을 45° 굽히고 발뒤꿈치를 모아요.', '골반이 뒤로 넘어가지 않게 위쪽 손으로 골반을 고정해요.', '발은 붙인 채 위쪽 무릎을 조개처럼 벌려요.', '1초 멈췄다 천천히 닫아요.'],
      en: ['Lie on your left side, knees bent 45°, heels together.', 'Keep your top hand on your pelvis so it doesn’t roll back.', 'Keeping the feet together, open the top knee like a clamshell.', 'Pause 1 second and close slowly.'],
    },
    cues: { ko: ['발은 붙인 채', '골반은 그대로', '엉덩이 옆이 뻐근하게'], en: ['Feet together', 'Pelvis still', 'Feel it on the side of the hip'] },
    mistakes: { ko: ['골반이 뒤로 넘어감', '너무 크게 벌림'], en: ['Rolling the pelvis back', 'Opening too far'] },
    why: { ko: '무릎이 안쪽으로 무너지지 않게 잡아 주는 중둔근을 깨워요. X다리 경향과 무릎·골반 통증에 좋아요.', en: 'Wakes up the gluteus medius, which stops the knee caving in — great for knock-knee alignment and knee/hip pain.' },
    muscles: { ko: '중둔근, 고관절 외회전근', en: 'Gluteus medius, hip external rotators' },
    anim: {
      view: 0,
      elev: 25,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [SIDE_LYING, merge(SIDE_LYING, { hipR: { flex: 45, rot: 34, abd: 26 } })],
      durations: [1.1, 1.1],
      pauses: [0.3, 1],
    },
  },
  {
    id: 'side-lying-abduction',
    name: { ko: '옆으로 누워 다리 들기', en: 'Side-lying leg raise' },
    phase: 'activate',
    position: 'sideLying',
    regions: ['glute', 'hip'],
    targets: { pelvicTilt: 0.8, lateralShift: 0.6, kneeValgus: 0.6, hipPain: 0.3 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 12, tempo: 3, holdSec: 1, perSide: true, rest: 15 },
    steps: {
      ko: ['왼쪽으로 누워 아래 다리는 굽히고 위 다리는 쭉 펴요.', '발끝은 정면(또는 살짝 아래)을 향하게 해요.', '뒤꿈치로 밀어내듯 다리를 비스듬히 뒤쪽 위로 들어 올려요.', '1초 멈췄다 천천히 내려요.'],
      en: ['Lie on your left side, bottom leg bent, top leg straight.', 'Point your toes forward (or slightly down).', 'Lead with the heel and lift the leg up and slightly back.', 'Pause 1 second and lower slowly.'],
    },
    cues: { ko: ['뒤꿈치가 먼저', '골반은 앞으로 살짝'], en: ['Lead with the heel', 'Pelvis tipped slightly forward'] },
    mistakes: { ko: ['발끝이 천장을 향함(엉덩이 앞쪽만 씀)', '허리로 들어 올림'], en: ['Toes turning up (using the hip flexor)', 'Hiking with the low back'] },
    why: { ko: '골반의 좌우 균형을 잡는 중둔근을 강화해 짝다리·골반 비대칭을 개선해요.', en: 'Strengthens the gluteus medius that keeps the pelvis level, improving side-to-side asymmetry.' },
    muscles: { ko: '중둔근, 소둔근', en: 'Gluteus medius & minimus' },
    anim: {
      view: 0,
      elev: 20,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [merge(SIDE_LYING, { hipR: { flex: -4 }, knR: 2, anR: 0 }), merge(SIDE_LYING, { hipR: { flex: -8, abd: 36 }, knR: 2, anR: 0 })],
      durations: [1.3, 1.3],
      pauses: [0.3, 1],
    },
  },
  {
    id: 'side-plank-knee',
    name: { ko: '무릎 사이드 플랭크', en: 'Side plank from knees' },
    phase: 'activate',
    position: 'sideLying',
    regions: ['core', 'hip'],
    targets: { lateralShift: 0.8, pelvicTilt: 0.7, lowBackPain: 0.4 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'hold', sets: 2, value: 20, perSide: true, rest: 20 },
    steps: {
      ko: ['왼쪽으로 누워 팔꿈치를 어깨 바로 아래에 두고 무릎을 90°로 굽혀요.', '배에 힘을 주고 골반을 들어 머리~무릎이 일직선이 되게 해요.', '20초 버티며 숨은 계속 쉬어요.'],
      en: ['Lie on your left side, elbow under the shoulder, knees bent 90°.', 'Brace and lift your hips so your head to knees form a straight line.', 'Hold 20 seconds and keep breathing.'],
    },
    cues: { ko: ['골반을 높이', '숨은 계속'], en: ['Hips high', 'Keep breathing'] },
    mistakes: { ko: ['골반이 처짐', '어깨가 귀 쪽으로 올라감'], en: ['Hips sagging', 'Shoulder creeping to the ear'] },
    why: { ko: '몸통 옆 근육(요방형근·복사근)을 강화해 좌우 치우침을 바로잡고 허리를 안정시켜요(McGill Big 3).', en: 'Strengthens the lateral core (QL, obliques) to fix side shifts and stabilise the spine — one of McGill’s Big 3.' },
    muscles: { ko: '요방형근, 복사근, 중둔근', en: 'Quadratus lumborum, obliques, glute med' },
    avoid: ['shoulderSevere', 'pregnant'],
    anim: {
      view: 0,
      elev: 12,
      props: [{ kind: 'mat' }],
      anchor: ['knL'],
      level: { a: ['elL'], b: ['knL'], axis: 'roll' },
      keys: [
        merge({ root: { roll: 86 } }, both({ hip: { flex: 10 }, kn: 90 }), { shL: { abd: 84 }, elL: 90, shR: { abd: 18, rot: -30 }, elR: 95 }),
        merge({ root: { roll: 72 } }, both({ hip: { flex: 0 }, kn: 90 }), { shL: { abd: 74 }, elL: 90, shR: { abd: 18, rot: -30 }, elR: 95 }),
      ],
      durations: [1.4, 1.4],
      pauses: [0.4, 2.6],
    },
  },
  {
    id: 'mcgill-curlup',
    name: { ko: '맥길 컬업', en: 'McGill curl-up' },
    phase: 'activate',
    position: 'supine',
    regions: ['core', 'lowBack'],
    targets: { lowBackPain: 0.8, lordosis: 0.4, swayback: 0.3 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 6, tempo: 2, holdSec: 8, rest: 20 },
    steps: {
      ko: ['한쪽 무릎은 세우고 반대쪽 다리는 쭉 펴고 누워요.', '양손을 허리 아래 오목한 곳에 받쳐 자연스러운 허리 곡선을 유지해요.', '머리·어깨를 한 덩어리로 바닥에서 2~3cm만 살짝 들어 8초 버텨요.', '목을 꺾거나 허리를 바닥에 누르지 않아요.'],
      en: ['Lie with one knee bent and the other leg straight.', 'Slide your hands under the arch of your low back to keep its natural curve.', 'Lift your head and shoulders as one unit just 2–3 cm and hold for 8 seconds.', 'Don’t crank the neck or flatten the back.'],
    },
    cues: { ko: ['머리와 어깨를 한 덩어리로', '아주 살짝만', '8초 버텨요'], en: ['Head and shoulders as one', 'Just a little', 'Hold for 8'] },
    mistakes: { ko: ['윗몸일으키기처럼 크게 들기', '턱을 가슴에 붙임'], en: ['Crunching up high', 'Tucking the chin to the chest'] },
    why: { ko: '척추를 굽히지 않고 복부 앞쪽을 단련하는, 허리에 안전한 복근 운동이에요(McGill Big 3).', en: 'A spine-sparing way to train the front abs without repeated flexion — McGill’s Big 3.' },
    muscles: { ko: '복직근, 복사근', en: 'Rectus abdominis, obliques' },
    avoid: ['pregnant', 'neckSevere'],
    anim: {
      view: 90,
      elev: 10,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [
        merge(SUPINE, { hipR: { flex: 55 }, knR: 105, anR: 10 }, both({ sh: { abd: 24, rot: -80 }, el: 86 })),
        merge(SUPINE, { hipR: { flex: 55 }, knR: 105, anR: 10, thorax: { flex: 14 }, neck: { flex: 2 } }, both({ sh: { abd: 24, rot: -80 }, el: 86 })),
      ],
      durations: [1, 1],
      pauses: [0.8, 3],
      zoom: 1.1,
    },
  },
  {
    id: 'squat',
    name: { ko: '맨몸 스쿼트', en: 'Bodyweight squat' },
    phase: 'integrate',
    position: 'standing',
    regions: ['glute', 'knee', 'hip'],
    targets: { kneeValgus: 0.7, kneeHyperext: 0.4, lordosis: 0.3, hipPain: 0.2 },
    equipment: [],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 4, rest: 30 },
    steps: {
      ko: ['발을 어깨너비로 벌리고 발끝은 살짝 바깥을 향해요.', '엉덩이를 뒤로 빼며 의자에 앉듯 내려가요. 무릎은 발끝 방향으로.', '허벅지가 바닥과 평행해질 때까지(편한 만큼) 내려가요.', '발바닥 전체로 바닥을 밀며 일어나 엉덩이를 조여요.'],
      en: ['Feet shoulder-width, toes slightly out.', 'Push your hips back and sit down as if into a chair; knees track over the toes.', 'Go down until your thighs are about parallel (as far as is comfortable).', 'Drive through the whole foot to stand and squeeze your glutes.'],
    },
    cues: { ko: ['엉덩이를 뒤로', '무릎은 발끝 방향', '발바닥 전체로 밀어요'], en: ['Hips back', 'Knees over toes', 'Push through the whole foot'] },
    mistakes: { ko: ['무릎이 안쪽으로 모임', '발뒤꿈치가 뜸', '허리가 둥글게 말림'], en: ['Knees caving in', 'Heels lifting', 'Back rounding'] },
    why: { ko: '교정한 정렬을 실제 움직임에서 쓰도록 연결하는 통합 운동이에요. 무릎 정렬과 엉덩이 힘을 동시에 길러요.', en: 'Integrates your new alignment into real movement, training knee tracking and glute strength together.' },
    muscles: { ko: '대둔근, 대퇴사두근, 코어', en: 'Glutes, quads, core' },
    caution: { ko: '무릎이 아프면 의자 앉았다 일어서기로 대신하세요.', en: 'If your knees hurt, do sit-to-stands instead.' },
    avoid: ['kneeSevere', 'kneePain'],
    anim: {
      view: 90,
      keys: [merge(STAND, both({ sh: { flex: 20 }, el: 10 })), merge(both({ hip: { flex: 100 }, kn: 108, an: 26, sh: { flex: 88 }, el: 4 }), { lumbar: { flex: 14 }, thorax: { flex: 8 }, neck: { flex: -16 } })],
      durations: [1.8, 1.6],
      pauses: [0.3, 0.3],
    },
    coach: {
      view: 'side',
      metric: 'kneeAngle',
      mode: 'reps',
      rest: 160,
      peak: 115,
      dir: -1,
      hint: { ko: '옆에서 온몸이 보이게 2~3m 떨어진 곳에 휴대폰을 세워 주세요', en: 'Place the phone 2–3 m to your side so your whole body is visible' },
      more: { ko: '조금 더 깊게', en: 'A little deeper' },
      good: { ko: '좋아요!', en: 'Good depth!' },
    },
  },
  {
    id: 'sit-to-stand',
    name: { ko: '의자 앉았다 일어서기', en: 'Sit-to-stand' },
    phase: 'integrate',
    position: 'standing',
    regions: ['glute', 'knee'],
    targets: { kneeValgus: 0.5, kneePain: 0.3, hipPain: 0.3, lowBackPain: 0.2 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 4, rest: 30 },
    desk: true,
    steps: {
      ko: ['의자 앞쪽에 앉아 발을 골반 너비로 두고 팔은 가슴 앞에 모아요.', '코가 발끝 위로 오도록 상체를 숙이며', '발바닥으로 바닥을 밀어 일어서요. 끝에서 엉덩이를 조여요.', '엉덩이를 뒤로 빼며 천천히 앉아요(털썩 금지).'],
      en: ['Sit near the front of a chair, feet hip-width, arms crossed on your chest.', 'Lean forward until your nose is over your toes,', 'then push through your feet to stand, squeezing your glutes at the top.', 'Reach your hips back and sit down slowly — no plopping.'],
    },
    cues: { ko: ['코는 발끝 위로', '천천히 앉아요', '무릎은 발끝 방향'], en: ['Nose over toes', 'Sit down slowly', 'Knees over toes'] },
    mistakes: { ko: ['손으로 짚고 일어남', '무릎이 안으로 모임'], en: ['Pushing up with the hands', 'Knees caving in'] },
    why: { ko: '일상에서 가장 많이 하는 동작으로 엉덩이·허벅지 힘과 무릎 정렬을 훈련해요. 무릎이 불편한 분께 스쿼트 대신 추천해요.', en: 'Trains glute and thigh strength plus knee tracking in the move you do most every day — a knee-friendly squat alternative.' },
    muscles: { ko: '대둔근, 대퇴사두근', en: 'Glutes, quads' },
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      anchor: ['heelL', 'heelR'],
      keys: [merge(SIT, ARMS_CROSSED, { lumbar: { flex: 6 } }), merge(ARMS_CROSSED, { root: { pitch: 0 } })],
      durations: [1.8, 1.8],
      pauses: [0.4, 0.4],
    },
    coach: {
      view: 'side',
      metric: 'kneeAngle',
      mode: 'reps',
      rest: 160,
      peak: 110,
      dir: -1,
      hint: { ko: '옆에서 의자와 온몸이 보이게 휴대폰을 세워 주세요', en: 'Place the phone beside you so you and the chair are visible' },
      more: { ko: '끝까지 앉았다 일어나요', en: 'Sit all the way down' },
      good: { ko: '좋아요!', en: 'Nice!' },
    },
  },
  {
    id: 'hip-hinge',
    name: { ko: '힙 힌지 (인사 동작)', en: 'Hip hinge' },
    phase: 'integrate',
    position: 'standing',
    regions: ['hip', 'lowBack', 'glute'],
    targets: { lowBackPain: 0.5, swayback: 0.4, kneeHyperext: 0.5, flatBack: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 4, rest: 20 },
    steps: {
      ko: ['발을 골반 너비로 벌리고 무릎을 살짝 굽혀요.', '손을 골반에 대고 허리를 곧게 편 채 엉덩이를 뒤로 쭉 빼며 인사하듯 숙여요.', '허벅지 뒤가 당기면 엉덩이를 조이며 일어나요.', '등이 둥글게 말리지 않게 해요.'],
      en: ['Feet hip-width, knees softly bent.', 'Hands on hips, back long, push your hips back and bow forward.', 'When the backs of your thighs pull, squeeze your glutes to stand.', 'Don’t let your back round.'],
    },
    cues: { ko: ['엉덩이를 뒤로', '등은 곧게', '엉덩이 조이며 일어나요'], en: ['Hips back', 'Long back', 'Squeeze up'] },
    mistakes: { ko: ['허리로 숙임', '무릎을 너무 많이 굽힘(스쿼트가 됨)'], en: ['Bending from the back', 'Bending the knees too much (it becomes a squat)'] },
    why: { ko: '물건을 들 때 허리 대신 고관절을 쓰는 패턴을 익혀요. 무릎을 잠그고 서는 습관(과신전) 교정에도 좋아요.', en: 'Teaches you to bend from the hips instead of the spine — also great for breaking the locked-knee habit.' },
    muscles: { ko: '햄스트링, 대둔근, 척추 안정근', en: 'Hamstrings, glutes, spinal stabilisers' },
    avoid: ['lowBackSevere'],
    anim: {
      view: 90,
      keys: [merge(STAND, HANDS_ON_HIPS, both({ kn: 8, hip: { flex: 2 } })), merge(HANDS_ON_HIPS, { root: { pitch: 52 }, neck: { flex: -14 } }, both({ hip: { flex: 64 }, kn: 22, an: 10 }))],
      durations: [1.8, 1.8],
      pauses: [0.3, 0.5],
    },
  },
  {
    id: 'forearm-plank',
    name: { ko: '플랭크', en: 'Forearm plank' },
    phase: 'integrate',
    position: 'prone',
    regions: ['core'],
    targets: { lordosis: 0.5, lowBackPain: 0.3, swayback: 0.3 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'hold', sets: 2, value: 25, rest: 25 },
    steps: {
      ko: ['팔꿈치를 어깨 아래에 두고 엎드려요.', '배와 엉덩이에 힘을 주고 몸을 들어 머리부터 발뒤꿈치까지 일직선.', '허리가 처지거나 엉덩이가 솟지 않게 25초 버텨요.', '힘들면 무릎을 대고 해도 좋아요.'],
      en: ['Lie face down with elbows under your shoulders.', 'Brace your belly and glutes and lift into a straight line from head to heels.', 'Hold 25 seconds without sagging or piking.', 'Drop to your knees if needed.'],
    },
    cues: { ko: ['몸은 일직선', '엉덩이 조이고', '숨은 계속'], en: ['Straight line', 'Squeeze the glutes', 'Keep breathing'] },
    mistakes: { ko: ['허리가 처짐', '엉덩이가 솟음', '숨 참기'], en: ['Sagging hips', 'Piking up', 'Holding the breath'] },
    why: { ko: '교정된 자세를 버텨 내는 전신 코어 지구력을 길러요.', en: 'Builds whole-body core endurance to hold your improved posture.' },
    muscles: { ko: '복횡근, 복직근, 둔근, 어깨 안정근', en: 'Deep & superficial abs, glutes, shoulder stabilisers' },
    avoid: ['pregnant', 'shoulderSevere', 'lowBackSevere'],
    anim: {
      view: 90,
      elev: 10,
      props: [{ kind: 'mat' }],
      anchor: ['toeL', 'toeR'],
      level: { a: ['elL', 'elR'], b: ['toeL', 'toeR'] },
      keys: [
        merge({ root: { pitch: 90 } }, both({ sh: { flex: 90, abd: 6 }, el: 90, an: -10, hip: { flex: 0 }, kn: 60 }), { neck: { flex: -6 } }),
        merge({ root: { pitch: 100 } }, both({ sh: { flex: 90, abd: 6 }, el: 90, an: -8, hip: { flex: 0 }, kn: 0 }), { neck: { flex: -6 } }),
      ],
      durations: [1.4, 1.4],
      pauses: [0.4, 3],
    },
  },
  {
    id: 'split-squat',
    name: { ko: '스플릿 스쿼트', en: 'Split squat' },
    phase: 'integrate',
    position: 'standing',
    regions: ['glute', 'knee', 'hip'],
    targets: { kneeValgus: 0.6, pelvicTilt: 0.5, lateralShift: 0.4 },
    equipment: [],
    level: 3,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 4, perSide: true, rest: 30 },
    steps: {
      ko: ['왼발을 앞으로 크게 한 걸음, 오른발은 뒤에 두고 뒤꿈치를 들어요.', '상체를 곧게 세운 채 뒷무릎을 바닥 가까이 수직으로 내려요.', '앞무릎은 발끝 방향, 골반은 수평을 유지해요.', '앞발 뒤꿈치로 밀며 올라와요.'],
      en: ['Step your left foot forward, right foot back with the heel up.', 'Stay tall and lower the back knee straight down toward the floor.', 'Front knee tracks over the toes; keep the pelvis level.', 'Drive through the front heel to rise.'],
    },
    cues: { ko: ['수직으로 내려가요', '앞무릎은 발끝 방향', '골반 수평'], en: ['Straight down', 'Front knee over toes', 'Level pelvis'] },
    mistakes: { ko: ['앞무릎이 안쪽으로', '상체가 앞으로 쏠림'], en: ['Front knee caving', 'Leaning forward'] },
    why: { ko: '한쪽 다리로 버티며 좌우 근력 차이와 골반 안정성을 동시에 잡는 고급 통합 운동이에요.', en: 'An advanced single-leg move that fixes left–right strength gaps and pelvic stability together.' },
    muscles: { ko: '대둔근, 중둔근, 대퇴사두근', en: 'Glutes, glute med, quads' },
    avoid: ['kneeSevere', 'kneePain', 'balance'],
    anim: {
      view: 90,
      anchor: ['toeL'],
      keys: [
        merge(HANDS_ON_HIPS, { hipL: { flex: 26 }, knL: 6, hipR: { flex: -22 }, knR: 8, anR: -30 }),
        merge(HANDS_ON_HIPS, { hipL: { flex: 82 }, knL: 92, anL: 18, hipR: { flex: -12 }, knR: 100, anR: -40 }),
      ],
      durations: [1.8, 1.6],
      pauses: [0.3, 0.3],
    },
  },
  {
    id: 'single-leg-balance',
    name: { ko: '한 발 서기', en: 'Single-leg balance' },
    phase: 'integrate',
    position: 'standing',
    regions: ['hip', 'ankle', 'core'],
    targets: { lateralShift: 0.6, pelvicTilt: 0.6, kneeValgus: 0.5 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 10 },
    desk: true,
    steps: {
      ko: ['벽이나 의자 옆에 서서 필요하면 한 손을 대요.', '오른발을 살짝 들어 왼발로 서요.', '골반이 한쪽으로 떨어지지 않게 수평을 유지하고, 서 있는 무릎은 살짝 굽혀요.', '30초 버텨요. 쉬우면 눈을 감아 보세요.'],
      en: ['Stand near a wall or chair and touch it if you need to.', 'Lift your right foot and balance on the left.', 'Keep your pelvis level and the standing knee soft.', 'Hold 30 seconds. Too easy? Close your eyes.'],
    },
    cues: { ko: ['골반은 수평', '서 있는 발로 바닥 누르기', '시선은 한 곳에'], en: ['Level pelvis', 'Press the floor away', 'Fix your gaze'] },
    mistakes: { ko: ['골반이 한쪽으로 빠짐', '무릎을 잠금'], en: ['Hip dropping out to the side', 'Locking the knee'] },
    why: { ko: '한쪽 다리로 몸을 지탱하는 능력(고관절·발목 안정성)을 길러 짝다리 습관과 좌우 불균형을 바로잡아요.', en: 'Builds single-leg hip and ankle stability, correcting the one-leg-stance habit and asymmetry.' },
    muscles: { ko: '중둔근, 발목 안정근, 코어', en: 'Glute med, ankle stabilisers, core' },
    caution: { ko: '균형이 불안하면 반드시 벽이나 의자를 잡고 하세요.', en: 'If your balance is shaky, always hold a wall or chair.' },
    anim: {
      view: 0,
      keys: [merge(STAND, both({ sh: { abd: 20 }, el: 10 })), merge(STAND, both({ sh: { abd: 22 }, el: 10 }), { hipR: { flex: 48 }, knR: 70, knL: 6 })],
      durations: [1.4, 1.4],
      pauses: [0.4, 3],
    },
    coach: {
      view: 'front',
      metric: 'footLift',
      mode: 'hold',
      target: 0.04,
      dir: 1,
      hint: { ko: '정면에서 발끝까지 보이게 휴대폰을 세워 주세요', en: 'Prop the phone in front so your feet are visible' },
      more: { ko: '발을 들어 주세요', en: 'Lift your foot' },
      good: { ko: '좋아요, 균형 유지!', en: 'Nice balance!' },
    },
  },
  {
    id: 'wall-posture-reset',
    name: { ko: '벽 자세 리셋', en: 'Wall posture reset' },
    phase: 'integrate',
    position: 'wall',
    regions: ['fullBody', 'neck', 'upperBack'],
    targets: { fhp: 0.8, roundShoulder: 0.7, swayback: 0.5, kyphosis: 0.5, lordosis: 0.3 },
    equipment: ['wall'],
    level: 1,
    dose: { kind: 'hold', sets: 3, value: 30, rest: 10 },
    desk: true,
    steps: {
      ko: ['벽에 뒤꿈치·엉덩이·날개뼈·뒤통수 네 곳을 붙여요.', '허리 뒤 공간은 손바닥 하나 정도만 남기고 배에 살짝 힘을 줘요.', '턱을 당긴 채 정수리를 천장으로 늘이며 30초 호흡해요.', '이 느낌 그대로 벽에서 떨어져 걸어 보세요. 이게 당신의 “바른 자세”예요.'],
      en: ['Touch the wall with four points: heels, glutes, shoulder blades and the back of your head.', 'Leave only a hand’s space behind your low back; brace lightly.', 'Tuck your chin, grow tall through the crown and breathe for 30 seconds.', 'Step away keeping that feeling — that’s your “good posture”.'],
    },
    cues: { ko: ['네 곳을 벽에', '정수리는 위로', '이 느낌을 기억해요'], en: ['Four points on the wall', 'Crown up', 'Remember this feeling'] },
    mistakes: { ko: ['턱이 들림', '허리를 과하게 젖힘'], en: ['Chin lifting', 'Over-arching'] },
    why: { ko: '근육만 풀고 끝내면 자세는 금방 돌아가요. 바른 정렬을 몸에 “저장”하는 마무리 동작이에요.', en: 'Release alone fades fast — this finisher “saves” the good alignment into your body.' },
    muscles: { ko: '자세 유지 근육 전체', en: 'Whole-body postural muscles' },
    anim: {
      view: 90,
      props: [{ kind: 'wall', wall: 'back', dist: 0 }],
      keys: [
        merge(STAND, { neck: { flex: 16 }, head: { flex: -12 }, thorax: { flex: 12 }, lumbar: { flex: -4 } }, both({ scap: { prot: 3 } })),
        merge(WALL, { neck: { flex: -6 }, head: { flex: 6 } }, both({ scap: { prot: -2 } })),
      ],
      durations: [1.8, 1.8],
      pauses: [0.6, 3],
    },
  },
  {
    id: 'calf-raise',
    name: { ko: '까치발 들기', en: 'Calf raise' },
    phase: 'integrate',
    position: 'standing',
    regions: ['ankle', 'knee'],
    targets: { kneeHyperext: 0.3, kneeValgus: 0.3, stiffness: 0.2 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 15, tempo: 2.5, holdSec: 1, rest: 20 },
    desk: true,
    steps: {
      ko: ['벽이나 의자를 가볍게 잡고 발을 골반 너비로 서요.', '엄지발가락 쪽으로 체중을 실으며 뒤꿈치를 높이 들어요.', '1초 멈췄다 천천히 내려요.'],
      en: ['Lightly hold a wall or chair, feet hip-width.', 'Rise high onto the balls of your feet, weight toward the big toes.', 'Pause 1 second and lower slowly.'],
    },
    cues: { ko: ['엄지발가락 쪽으로', '천천히 내려요'], en: ['Toward the big toes', 'Lower slowly'] },
    mistakes: { ko: ['발목이 바깥으로 꺾임', '빠르게 튕김'], en: ['Ankles rolling out', 'Bouncing fast'] },
    why: { ko: '종아리와 발목 안정성을 길러 하체 정렬을 아래에서부터 받쳐 줘요. 오래 앉아 있을 때 혈액순환에도 좋아요.', en: 'Builds calf and ankle stability to support leg alignment from the ground up — and boosts circulation after sitting.' },
    muscles: { ko: '비복근, 가자미근', en: 'Gastrocnemius, soleus' },
    anim: {
      view: 90,
      anchor: ['toeL', 'toeR'],
      keys: [STAND, merge(STAND, both({ an: -34 }))],
      durations: [1, 1],
      pauses: [0.3, 0.8],
    },
    coach: {
      view: 'side',
      metric: 'heelRaise',
      mode: 'reps',
      rest: 0.012,
      peak: 0.03,
      dir: 1,
      hint: { ko: '옆에서 발까지 보이게 휴대폰을 세워 주세요', en: 'Place the phone beside you so your feet are visible' },
      more: { ko: '뒤꿈치를 더 높이', en: 'Heels higher' },
      good: { ko: '좋아요!', en: 'Good!' },
    },
  },
  {
    id: 'standing-abduction',
    name: { ko: '서서 다리 옆으로 들기', en: 'Standing hip abduction' },
    phase: 'activate',
    position: 'standing',
    regions: ['glute', 'hip'],
    targets: { pelvicTilt: 0.6, kneeValgus: 0.6, lateralShift: 0.5 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 12, tempo: 2.5, holdSec: 1, perSide: true, rest: 15 },
    desk: true,
    steps: {
      ko: ['의자나 벽을 한 손으로 잡고 바르게 서요.', '몸통을 곧게 세운 채 오른다리를 옆으로 천천히 들어요.', '발끝은 정면, 상체가 반대로 기울지 않게 해요.', '1초 멈췄다 천천히 내려요.'],
      en: ['Hold a chair or wall with one hand and stand tall.', 'Keeping your trunk upright, slowly lift your right leg out to the side.', 'Toes face forward; don’t lean the other way.', 'Pause 1 second and lower slowly.'],
    },
    cues: { ko: ['상체는 곧게', '발끝은 정면'], en: ['Stay tall', 'Toes forward'] },
    mistakes: { ko: ['상체가 반대쪽으로 기울어짐', '다리를 너무 높이 듦'], en: ['Leaning away', 'Lifting too high'] },
    why: { ko: '서서 하는 중둔근 운동으로 골반 좌우 균형과 무릎 정렬을 잡아요. 사무실에서도 가능해요.', en: 'A standing glute-med exercise for pelvic balance and knee alignment — doable at the office.' },
    muscles: { ko: '중둔근', en: 'Gluteus medius' },
    anim: {
      view: 0,
      keys: [merge(STAND, { shL: { abd: 40 }, elL: 20 }), merge(STAND, { shL: { abd: 40 }, elL: 20, hipR: { abd: 30 }, knR: 2 })],
      durations: [1.2, 1.2],
      pauses: [0.3, 0.8],
    },
    coach: {
      view: 'front',
      metric: 'hipAbduction',
      mode: 'reps',
      rest: 9,
      peak: 20,
      dir: 1,
      hint: { ko: '정면에서 온몸이 보이게 휴대폰을 세워 주세요', en: 'Prop the phone in front so your whole body is visible' },
      more: { ko: '조금 더 옆으로', en: 'A little higher' },
      good: { ko: '좋아요!', en: 'Nice!' },
    },
  },
  {
    id: 'seated-twist',
    name: { ko: '앉아서 척추 비틀기', en: 'Seated spinal twist' },
    phase: 'mobility',
    position: 'seated',
    regions: ['upperBack', 'lowBack'],
    targets: { stiffness: 0.7, upperBackPain: 0.5, lowBackPain: 0.3, kyphosis: 0.3 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 15, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자에 곧게 앉아 발을 바닥에 붙여요.', '숨을 들이쉬며 정수리를 위로 늘이고,', '내쉬며 상체를 왼쪽으로 돌려 오른손은 왼무릎, 왼손은 등받이를 잡아요.', '골반은 정면에 둔 채 15초 유지해요.'],
      en: ['Sit tall with feet flat.', 'Inhale and grow tall through the crown,', 'exhale and turn your upper body left, right hand on the left knee, left hand on the chair back.', 'Keep your pelvis facing forward and hold 15 seconds.'],
    },
    cues: { ko: ['위로 길게, 그리고 돌려요', '골반은 정면'], en: ['Grow tall, then turn', 'Pelvis faces forward'] },
    mistakes: { ko: ['등을 말고 비틈', '목만 돌림'], en: ['Twisting while slumped', 'Turning only the neck'] },
    why: { ko: '앉아서 굳은 척추의 회전을 풀어 등·허리 뻐근함을 줄여요.', en: 'Unlocks spinal rotation stiffened by sitting to ease back tightness.' },
    muscles: { ko: '척추 회전근, 복사근', en: 'Spinal rotators, obliques' },
    anim: {
      view: 0,
      props: [{ kind: 'chair' }],
      keys: [SIT, merge(SIT, { thorax: { twist: 34 }, lumbar: { twist: 10 }, neck: { twist: 18 }, shR: { flex: 40, abd: -30 }, elR: 50, shL: { flex: -10, abd: 30 }, elL: 40 })],
      durations: [1.6, 1.6],
      pauses: [0.4, 2.6],
    },
  },
  {
    id: 'chair-lat-stretch',
    name: { ko: '의자 잡고 등·겨드랑이 늘리기', en: 'Chair lat stretch' },
    phase: 'stretch',
    position: 'standing',
    regions: ['upperBack', 'shoulder'],
    targets: { kyphosis: 0.6, roundShoulder: 0.5, lordosis: 0.3, upperBackPain: 0.4 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자 등받이(또는 책상)를 양손으로 잡고 뒤로 물러나요.', '엉덩이를 뒤로 빼며 상체를 숙여 팔과 몸통이 일직선이 되게 해요.', '가슴을 바닥 쪽으로 지그시 눌러 겨드랑이~등이 늘어나면 30초.'],
      en: ['Hold the back of a chair (or a desk) and step back.', 'Push your hips back and fold until your arms and trunk form a line.', 'Let your chest sink toward the floor and hold 30 seconds as your armpits and back stretch.'],
    },
    cues: { ko: ['엉덩이는 뒤로', '가슴은 아래로'], en: ['Hips back', 'Chest down'] },
    mistakes: { ko: ['허리를 과하게 꺾음', '고개를 떨어뜨림'], en: ['Over-arching the low back', 'Dropping the head'] },
    why: { ko: '짧아진 광배근은 어깨를 말고 허리를 휘게 만들어요. 팔을 머리 위로 들 때 걸리는 느낌도 줄여 줘요.', en: 'Tight lats round the shoulders and arch the back; stretching them also frees overhead reaching.' },
    muscles: { ko: '광배근, 대원근, 흉추', en: 'Latissimus dorsi, teres major, thoracic spine' },
    anim: {
      view: 90,
      keys: [
        merge(STAND, both({ sh: { flex: 70 }, el: 20 }), { root: { pitch: 20 } }, both({ hip: { flex: 20 } })),
        merge(both({ sh: { flex: 168 }, el: 4, hip: { flex: 86 }, kn: 12, an: 6 }), { root: { pitch: 82 }, thorax: { flex: -8 }, neck: { flex: -4 } }),
      ],
      durations: [2, 2],
      pauses: [0.4, 3],
    },
  },
];
