/**
 * 운동 라이브러리 · 발목·발·균형·손목·전신
 * 문구·용량·대상 이슈는 물리치료 임상 기준으로 작성되었으며, 전문가가 자유롭게 수정할 수 있습니다.
 * 작성 규칙: docs/CONTENT_GUIDE.md
 */
import { both } from '../../figure/rig';
import { STAND, WALL, merge } from '../../figure/poses';
import type { Exercise } from '../exercise-types';

export const ANKLE: Exercise[] = [
  {
    id: 'calf-stretch',
    name: { ko: '벽 종아리 스트레칭', en: 'Wall calf stretch' },
    phase: 'stretch',
    position: 'wall',
    regions: ['ankle', 'knee'],
    targets: { kneeHyperext: 0.4, kneeValgus: 0.3, stiffness: 0.3 },
    equipment: ['wall'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['벽을 마주 보고 두 손을 벽에 대요.', '오른다리를 뒤로 한 걸음 빼고 발뒤꿈치를 바닥에 붙여요.', '앞무릎을 굽히며 몸을 벽 쪽으로 기울여요.', '오른쪽 종아리가 당기면 30초.'],
      en: ['Face a wall with both hands on it.', 'Step your right leg back and keep the heel down.', 'Bend the front knee and lean toward the wall.', 'Hold 30 seconds when the right calf stretches.'],
    },
    cues: { ko: ['뒤꿈치는 바닥에', '뒷무릎은 쭉'], en: ['Heel down', 'Back knee straight'] },
    mistakes: { ko: ['뒤꿈치가 뜸', '발끝이 바깥을 향함'], en: ['Heel lifting', 'Toes turning out'] },
    why: { ko: '종아리가 짧으면 무릎이 안쪽으로 무너지거나 뒤로 꺾이기 쉬워요.', en: 'Tight calves make the knees cave in or lock back more easily.' },
    muscles: { ko: '비복근, 가자미근', en: 'Gastrocnemius, soleus' },
    anim: {
      view: 90,
      props: [{ kind: 'wall', wall: 'front', dist: 2 }],
      anchor: ['heelR'],
      keys: [
        merge({ root: { pitch: 10 } }, both({ sh: { flex: 92 }, el: 18 }), { hipL: { flex: 30 }, knL: 16, anL: 4, hipR: { flex: -10 }, knR: 0, anR: 12 }),
        merge({ root: { pitch: 18 } }, both({ sh: { flex: 96 }, el: 40 }), { hipL: { flex: 44 }, knL: 40, anL: 12, hipR: { flex: -18 }, knR: 0, anR: 24 }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.4, 3],
    },
  },
  {
    id: 'calf-raise',
    name: { ko: '까치발 들기', en: 'Calf raise' },
    phase: 'integrate',
    position: 'standing',
    regions: ['ankle', 'knee'],
    targets: { kneeHyperext: 0.3, kneeValgus: 0.3, stiffness: 0.2 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 15, tempo: 2.5, holdSec: 1, rest: 20 },
    desk: true,
    steps: {
      ko: ['벽이나 의자를 가볍게 잡고 발을 골반 너비로 서요.', '엄지발가락 쪽으로 체중을 실으며 뒤꿈치를 높이 들어요.', '1초 멈췄다 천천히 내려요.'],
      en: ['Lightly hold a wall or chair, feet hip-width.', 'Rise high onto the balls of your feet, weight toward the big toes.', 'Pause 1 second and lower slowly.'],
    },
    cues: { ko: ['엄지발가락 쪽으로', '천천히 내려요'], en: ['Toward the big toes', 'Lower slowly'] },
    mistakes: { ko: ['발목이 바깥으로 꺾임', '빠르게 튕김'], en: ['Ankles rolling out', 'Bouncing fast'] },
    why: { ko: '종아리와 발목 안정성을 길러 하체 정렬을 아래에서부터 받쳐 줘요. 오래 앉아 있을 때 혈액순환에도 좋아요.', en: 'Builds calf and ankle stability to support leg alignment from the ground up — and boosts circulation after sitting.' },
    muscles: { ko: '비복근, 가자미근', en: 'Gastrocnemius, soleus' },
    anim: {
      view: 90,
      anchor: ['toeL', 'toeR'],
      keys: [STAND, merge(STAND, both({ an: -34 }))],
      durations: [1, 1],
      pauses: [0.3, 0.8],
    },
    coach: {
      view: 'side',
      metric: 'heelRaise',
      mode: 'reps',
      rest: 0.012,
      peak: 0.03,
      dir: 1,
      hint: { ko: '옆에서 발까지 보이게 휴대폰을 세워 주세요', en: 'Place the phone beside you so your feet are visible' },
      more: { ko: '뒤꿈치를 더 높이', en: 'Heels higher' },
      good: { ko: '좋아요!', en: 'Good!' },
    },
  },
  {
    id: 'single-leg-balance',
    name: { ko: '한 발 서기', en: 'Single-leg balance' },
    phase: 'integrate',
    position: 'standing',
    regions: ['hip', 'ankle', 'core'],
    targets: { lateralShift: 0.6, pelvicTilt: 0.6, kneeValgus: 0.5 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 10 },
    desk: true,
    steps: {
      ko: ['벽이나 의자 옆에 서서 필요하면 한 손을 대요.', '오른발을 살짝 들어 왼발로 서요.', '골반이 한쪽으로 떨어지지 않게 수평을 유지하고, 서 있는 무릎은 살짝 굽혀요.', '30초 버텨요. 쉬우면 눈을 감아 보세요.'],
      en: ['Stand near a wall or chair and touch it if you need to.', 'Lift your right foot and balance on the left.', 'Keep your pelvis level and the standing knee soft.', 'Hold 30 seconds. Too easy? Close your eyes.'],
    },
    cues: { ko: ['골반은 수평', '서 있는 발로 바닥 누르기', '시선은 한 곳에'], en: ['Level pelvis', 'Press the floor away', 'Fix your gaze'] },
    mistakes: { ko: ['골반이 한쪽으로 빠짐', '무릎을 잠금'], en: ['Hip dropping out to the side', 'Locking the knee'] },
    why: { ko: '한쪽 다리로 몸을 지탱하는 능력(고관절·발목 안정성)을 길러 짝다리 습관과 좌우 불균형을 바로잡아요.', en: 'Builds single-leg hip and ankle stability, correcting the one-leg-stance habit and asymmetry.' },
    muscles: { ko: '중둔근, 발목 안정근, 코어', en: 'Glute med, ankle stabilisers, core' },
    caution: { ko: '균형이 불안하면 반드시 벽이나 의자를 잡고 하세요.', en: 'If your balance is shaky, always hold a wall or chair.' },
    anim: {
      view: 0,
      keys: [merge(STAND, both({ sh: { abd: 20 }, el: 10 })), merge(STAND, both({ sh: { abd: 22 }, el: 10 }), { hipR: { flex: 48 }, knR: 70, knL: 6 })],
      durations: [1.4, 1.4],
      pauses: [0.4, 3],
    },
    coach: {
      view: 'front',
      metric: 'footLift',
      mode: 'hold',
      target: 0.04,
      dir: 1,
      hint: { ko: '정면에서 발끝까지 보이게 휴대폰을 세워 주세요', en: 'Prop the phone in front so your feet are visible' },
      more: { ko: '발을 들어 주세요', en: 'Lift your foot' },
      good: { ko: '좋아요, 균형 유지!', en: 'Nice balance!' },
    },
  },
  {
    id: 'wrist-stretch',
    name: { ko: '손목 앞뒤 스트레칭', en: 'Wrist flexor & extensor stretch' },
    phase: 'stretch',
    position: 'standing',
    regions: ['wrist'],
    targets: { wristPain: 1, stiffness: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 20, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['오른팔을 앞으로 쭉 펴고 손바닥이 앞을 향하게 손목을 젖혀요.', '왼손으로 오른손 손가락을 몸 쪽으로 부드럽게 당겨 20초.', '이번엔 손등이 앞을 향하게 손목을 구부려 같은 방법으로 20초.'],
      en: ['Straighten your right arm in front, palm facing away, wrist bent back.', 'Gently pull the fingers toward you with your left hand for 20 seconds.', 'Then flip: bend the wrist down, back of the hand forward, and hold 20 seconds.'],
    },
    cues: { ko: ['팔꿈치는 쭉 펴고', '부드럽게 당겨요'], en: ['Keep the elbow straight', 'Gentle pull'] },
    mistakes: { ko: ['세게 꺾음', '팔꿈치를 굽힘'], en: ['Cranking the wrist', 'Bending the elbow'] },
    why: { ko: '마우스·키보드·스마트폰으로 굳은 아래팔 근육을 풀어 손목 통증과 팔꿈치 부담을 줄여요.', en: 'Loosens forearm muscles tightened by mouse, keyboard and phone use, easing wrist and elbow strain.' },
    muscles: { ko: '손목 굽힘근·폄근', en: 'Wrist flexors & extensors' },
    anim: {
      view: 35,
      keys: [
        merge(STAND, { shR: { flex: 88, abd: 4 }, elR: 2, wrR: -10, shL: { flex: 70, abd: -30 }, elL: 40 }),
        merge(STAND, { shR: { flex: 88, abd: 4 }, elR: 2, wrR: -70, shL: { flex: 75, abd: -38 }, elL: 30 }),
      ],
      durations: [1.2, 1.2],
      pauses: [0.4, 2.4],
      zoom: 1.1,
    },
  },
  {
    id: 'wall-posture-reset',
    name: { ko: '벽 자세 리셋', en: 'Wall posture reset' },
    phase: 'integrate',
    position: 'wall',
    regions: ['fullBody', 'neck', 'upperBack'],
    targets: { fhp: 0.8, roundShoulder: 0.7, swayback: 0.5, kyphosis: 0.5, lordosis: 0.3 },
    equipment: ['wall'],
    level: 1,
    dose: { kind: 'hold', sets: 3, value: 30, rest: 10 },
    desk: true,
    steps: {
      ko: ['벽에 뒤꿈치·엉덩이·날개뼈·뒤통수 네 곳을 붙여요.', '허리 뒤 공간은 손바닥 하나 정도만 남기고 배에 살짝 힘을 줘요.', '턱을 당긴 채 정수리를 천장으로 늘이며 30초 호흡해요.', '이 느낌 그대로 벽에서 떨어져 걸어 보세요. 이게 당신의 “바른 자세”예요.'],
      en: ['Touch the wall with four points: heels, glutes, shoulder blades and the back of your head.', 'Leave only a hand’s space behind your low back; brace lightly.', 'Tuck your chin, grow tall through the crown and breathe for 30 seconds.', 'Step away keeping that feeling — that’s your “good posture”.'],
    },
    cues: { ko: ['네 곳을 벽에', '정수리는 위로', '이 느낌을 기억해요'], en: ['Four points on the wall', 'Crown up', 'Remember this feeling'] },
    mistakes: { ko: ['턱이 들림', '허리를 과하게 젖힘'], en: ['Chin lifting', 'Over-arching'] },
    why: { ko: '근육만 풀고 끝내면 자세는 금방 돌아가요. 바른 정렬을 몸에 “저장”하는 마무리 동작이에요.', en: 'Release alone fades fast — this finisher “saves” the good alignment into your body.' },
    muscles: { ko: '자세 유지 근육 전체', en: 'Whole-body postural muscles' },
    anim: {
      view: 90,
      props: [{ kind: 'wall', wall: 'back', dist: 0 }],
      keys: [
        merge(STAND, { neck: { flex: 16 }, head: { flex: -12 }, thorax: { flex: 12 }, lumbar: { flex: -4 } }, both({ scap: { prot: 3 } })),
        merge(WALL, { neck: { flex: -6 }, head: { flex: 6 } }, both({ scap: { prot: -2 } })),
      ],
      durations: [1.8, 1.8],
      pauses: [0.6, 3],
    },
  },
];
