/**
 * 운동 라이브러리 · 호흡·코어
 * 문구·용량·대상 이슈는 물리치료 임상 기준으로 작성되었으며, 전문가가 자유롭게 수정할 수 있습니다.
 * 작성 규칙: docs/CONTENT_GUIDE.md
 */
import { both } from '../../figure/rig';
import { QUAD, SIT, SUPINE, merge } from '../../figure/poses';
import type { Exercise } from '../exercise-types';

export const CORE: Exercise[] = [
  {
    id: 'breath-360',
    name: { ko: '360° 복식 호흡', en: '360° breathing' },
    phase: 'breath',
    position: 'seated',
    regions: ['core', 'upperBack'],
    targets: { stress: 1, stiffness: 0.4, lordosis: 0.3, fhp: 0.2, roundShoulder: 0.2 },
    equipment: [],
    level: 1,
    dose: { kind: 'time', sets: 1, value: 60 },
    desk: true,
    steps: {
      ko: ['허리를 세우고 앉아 한 손은 가슴, 한 손은 옆구리에 대요.', '코로 4초간 들이마시며 배·옆구리·등까지 풍선처럼 360° 부풀려요.', '입으로 6초간 길게 내쉬며 갈비뼈를 아래로 내려요.', '가슴과 어깨는 들썩이지 않게 해요.'],
      en: ['Sit tall with one hand on your chest and one on the side of your ribs.', 'Breathe in through the nose for 4 seconds, expanding belly, sides and back like a balloon.', 'Breathe out through the mouth for 6 seconds, letting the ribs drop.', 'Keep your chest and shoulders quiet.'],
    },
    cues: { ko: ['코로 들이마시고', '입으로 길게 내쉬어요', '어깨는 조용히'], en: ['In through the nose', 'Long breath out', 'Shoulders stay quiet'] },
    mistakes: { ko: ['가슴과 어깨로만 숨 쉬기', '배만 내밀기'], en: ['Breathing only into the chest', 'Pushing only the belly out'] },
    why: { ko: '얕은 가슴 호흡은 목·어깨의 보조 호흡근을 혹사시켜요. 횡격막 호흡은 긴장을 낮추고 코어를 안쪽부터 세워 줘요.', en: 'Shallow chest breathing overworks the neck and shoulder muscles. Diaphragm breathing lowers tension and switches on your core from the inside.' },
    muscles: { ko: '횡격막, 복횡근', en: 'Diaphragm, transversus abdominis' },
    anim: {
      view: 30,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { shL: { flex: 24, hab: -30 }, elL: 112, shR: { flex: 6, abd: 16, rot: -40 }, elR: 88 }),
        merge(SIT, { shL: { flex: 24, hab: -30 }, elL: 112, shR: { flex: 6, abd: 20, rot: -40 }, elR: 88, thorax: { flex: -4 }, neck: { flex: 3 } }),
      ],
      durations: [4, 6],
      zoom: 1.2,
    },
  },
  {
    id: 'dead-bug',
    name: { ko: '데드버그', en: 'Dead bug' },
    phase: 'activate',
    position: 'supine',
    regions: ['core', 'lowBack'],
    targets: { lordosis: 0.9, lowBackPain: 0.6, swayback: 0.5, lateralShift: 0.2 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 4, perSide: true, rest: 20 },
    steps: {
      ko: ['누워서 팔은 천장으로, 무릎은 90°로 들어 올려 테이블 자세를 만들어요.', '허리를 바닥에 지그시 누른 채 오른팔과 왼다리를 천천히 뻗어요.', '허리가 뜨기 직전까지만 내렸다가 숨을 내쉬며 돌아와요.', '반대쪽(왼팔·오른다리)도 같은 방법으로.'],
      en: ['Lie on your back, arms to the ceiling, hips and knees at 90° (tabletop).', 'Press your low back gently into the floor and slowly extend the right arm and left leg.', 'Go only as low as your back can stay down, then return on an exhale.', 'Repeat with the left arm and right leg.'],
    },
    cues: { ko: ['허리는 바닥에', '천천히 뻗어요', '숨을 내쉬며 돌아와요'], en: ['Back stays down', 'Reach slowly', 'Exhale back in'] },
    mistakes: { ko: ['허리가 바닥에서 뜸', '너무 빠르게 움직임', '숨을 참음'], en: ['Low back arching up', 'Moving too fast', 'Holding the breath'] },
    why: { ko: '팔다리가 움직여도 허리를 중립으로 지키는 깊은 코어 조절력을 길러, 허리 과전만과 요통을 줄여요.', en: 'Builds deep-core control to keep your spine neutral while the limbs move, reducing over-arching and back pain.' },
    muscles: { ko: '복횡근, 복직근, 내·외복사근', en: 'Transversus abdominis, rectus abdominis, obliques' },
    avoid: ['pregnant', 'lowBackSevere'],
    anim: {
      view: 90,
      elev: 12,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [
        merge(SUPINE, both({ hip: { flex: 90 }, kn: 90, an: 0, sh: { flex: 90 }, el: 2 })),
        merge(SUPINE, both({ an: 0 }), { hipL: { flex: 22 }, knL: 12, hipR: { flex: 90 }, knR: 90, shR: { flex: 172 }, elR: 2, shL: { flex: 90 }, elL: 2 }),
      ],
      durations: [2, 2],
      pauses: [0.4, 0.6],
    },
  },
  {
    id: 'bird-dog',
    name: { ko: '버드독', en: 'Bird dog' },
    phase: 'activate',
    position: 'quadruped',
    regions: ['core', 'lowBack', 'glute'],
    targets: { lowBackPain: 0.8, lordosis: 0.5, lateralShift: 0.4, pelvicTilt: 0.3, swayback: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 4, holdSec: 3, perSide: true, rest: 15 },
    steps: {
      ko: ['네발 자세에서 손목은 어깨 아래, 무릎은 골반 아래에 둬요.', '배에 살짝 힘을 주고 오른팔은 앞으로, 왼다리는 뒤로 쭉 뻗어요.', '등 위에 물컵이 있다고 생각하고 골반이 돌아가지 않게 3초 버텨요.', '천천히 돌아와 반대쪽도.'],
      en: ['On all fours, wrists under shoulders, knees under hips.', 'Brace lightly and reach the right arm forward and left leg back.', 'Imagine a glass of water on your back — keep the pelvis level for 3 seconds.', 'Return slowly and switch sides.'],
    },
    cues: { ko: ['골반은 수평', '멀리 뻗어요', '허리가 처지지 않게'], en: ['Pelvis level', 'Reach long', 'Don’t let the back sag'] },
    mistakes: { ko: ['다리를 너무 높이 들어 허리가 꺾임', '골반이 옆으로 기울어짐'], en: ['Lifting the leg too high and arching', 'Hips tipping to the side'] },
    why: { ko: '허리 부담은 최소로, 척추를 지탱하는 등·엉덩이·코어를 함께 강화해요. 요통 재활에서 가장 많이 쓰는 운동 중 하나예요(McGill Big 3).', en: 'Trains the back, glutes and core together with minimal spinal load — one of McGill’s “Big 3” for back pain.' },
    muscles: { ko: '척추기립근, 다열근, 대둔근, 복부', en: 'Erector spinae, multifidus, glutes, abs' },
    avoid: ['wristPain', 'kneePain'],
    anim: {
      view: 90,
      elev: 14,
      props: [{ kind: 'mat' }],
      anchor: ['knL', 'knR'],
      keys: [QUAD, merge(QUAD, { shR: { flex: 168 }, elR: 2, wrR: 0, hipL: { flex: -12 }, knL: 4, anL: -20, neck: { flex: -8 } })],
      durations: [1.8, 1.8],
      pauses: [0.3, 2.4],
    },
  },
  {
    id: 'mcgill-curlup',
    name: { ko: '맥길 컬업', en: 'McGill curl-up' },
    phase: 'activate',
    position: 'supine',
    regions: ['core', 'lowBack'],
    targets: { lowBackPain: 0.8, lordosis: 0.4, swayback: 0.3 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 6, tempo: 2, holdSec: 8, rest: 20 },
    steps: {
      ko: ['한쪽 무릎은 세우고 반대쪽 다리는 쭉 펴고 누워요.', '양손을 허리 아래 오목한 곳에 받쳐 자연스러운 허리 곡선을 유지해요.', '머리·어깨를 한 덩어리로 바닥에서 2~3cm만 살짝 들어 8초 버텨요.', '목을 꺾거나 허리를 바닥에 누르지 않아요.'],
      en: ['Lie with one knee bent and the other leg straight.', 'Slide your hands under the arch of your low back to keep its natural curve.', 'Lift your head and shoulders as one unit just 2–3 cm and hold for 8 seconds.', 'Don’t crank the neck or flatten the back.'],
    },
    cues: { ko: ['머리와 어깨를 한 덩어리로', '아주 살짝만', '8초 버텨요'], en: ['Head and shoulders as one', 'Just a little', 'Hold for 8'] },
    mistakes: { ko: ['윗몸일으키기처럼 크게 들기', '턱을 가슴에 붙임'], en: ['Crunching up high', 'Tucking the chin to the chest'] },
    why: { ko: '척추를 굽히지 않고 복부 앞쪽을 단련하는, 허리에 안전한 복근 운동이에요(McGill Big 3).', en: 'A spine-sparing way to train the front abs without repeated flexion — McGill’s Big 3.' },
    muscles: { ko: '복직근, 복사근', en: 'Rectus abdominis, obliques' },
    avoid: ['pregnant', 'neckSevere'],
    anim: {
      view: 90,
      elev: 10,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [
        merge(SUPINE, { hipR: { flex: 55 }, knR: 105, anR: 10 }, both({ sh: { abd: 24, rot: -80 }, el: 86 })),
        merge(SUPINE, { hipR: { flex: 55 }, knR: 105, anR: 10, thorax: { flex: 14 }, neck: { flex: 2 } }, both({ sh: { abd: 24, rot: -80 }, el: 86 })),
      ],
      durations: [1, 1],
      pauses: [0.8, 3],
      zoom: 1.1,
    },
  },
  {
    id: 'forearm-plank',
    name: { ko: '플랭크', en: 'Forearm plank' },
    phase: 'integrate',
    position: 'prone',
    regions: ['core'],
    targets: { lordosis: 0.5, lowBackPain: 0.3, swayback: 0.3 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'hold', sets: 2, value: 25, rest: 25 },
    steps: {
      ko: ['팔꿈치를 어깨 아래에 두고 엎드려요.', '배와 엉덩이에 힘을 주고 몸을 들어 머리부터 발뒤꿈치까지 일직선.', '허리가 처지거나 엉덩이가 솟지 않게 25초 버텨요.', '힘들면 무릎을 대고 해도 좋아요.'],
      en: ['Lie face down with elbows under your shoulders.', 'Brace your belly and glutes and lift into a straight line from head to heels.', 'Hold 25 seconds without sagging or piking.', 'Drop to your knees if needed.'],
    },
    cues: { ko: ['몸은 일직선', '엉덩이 조이고', '숨은 계속'], en: ['Straight line', 'Squeeze the glutes', 'Keep breathing'] },
    mistakes: { ko: ['허리가 처짐', '엉덩이가 솟음', '숨 참기'], en: ['Sagging hips', 'Piking up', 'Holding the breath'] },
    why: { ko: '교정된 자세를 버텨 내는 전신 코어 지구력을 길러요.', en: 'Builds whole-body core endurance to hold your improved posture.' },
    muscles: { ko: '복횡근, 복직근, 둔근, 어깨 안정근', en: 'Deep & superficial abs, glutes, shoulder stabilisers' },
    avoid: ['pregnant', 'shoulderSevere', 'lowBackSevere'],
    anim: {
      view: 90,
      elev: 10,
      props: [{ kind: 'mat' }],
      anchor: ['toeL', 'toeR'],
      level: { a: ['elL', 'elR'], b: ['toeL', 'toeR'] },
      keys: [
        merge({ root: { pitch: 90 } }, both({ sh: { flex: 90, abd: 6 }, el: 90, an: -10, hip: { flex: 0 }, kn: 60 }), { neck: { flex: -6 } }),
        merge({ root: { pitch: 100 } }, both({ sh: { flex: 90, abd: 6 }, el: 90, an: -8, hip: { flex: 0 }, kn: 0 }), { neck: { flex: -6 } }),
      ],
      durations: [1.4, 1.4],
      pauses: [0.4, 3],
    },
  },
  {
    id: 'side-plank-knee',
    name: { ko: '무릎 사이드 플랭크', en: 'Side plank from knees' },
    phase: 'activate',
    position: 'sideLying',
    regions: ['core', 'hip'],
    targets: { lateralShift: 0.8, pelvicTilt: 0.7, lowBackPain: 0.4 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'hold', sets: 2, value: 20, perSide: true, rest: 20 },
    steps: {
      ko: ['왼쪽으로 누워 팔꿈치를 어깨 바로 아래에 두고 무릎을 90°로 굽혀요.', '배에 힘을 주고 골반을 들어 머리~무릎이 일직선이 되게 해요.', '20초 버티며 숨은 계속 쉬어요.'],
      en: ['Lie on your left side, elbow under the shoulder, knees bent 90°.', 'Brace and lift your hips so your head to knees form a straight line.', 'Hold 20 seconds and keep breathing.'],
    },
    cues: { ko: ['골반을 높이', '숨은 계속'], en: ['Hips high', 'Keep breathing'] },
    mistakes: { ko: ['골반이 처짐', '어깨가 귀 쪽으로 올라감'], en: ['Hips sagging', 'Shoulder creeping to the ear'] },
    why: { ko: '몸통 옆 근육(요방형근·복사근)을 강화해 좌우 치우침을 바로잡고 허리를 안정시켜요(McGill Big 3).', en: 'Strengthens the lateral core (QL, obliques) to fix side shifts and stabilise the spine — one of McGill’s Big 3.' },
    muscles: { ko: '요방형근, 복사근, 중둔근', en: 'Quadratus lumborum, obliques, glute med' },
    avoid: ['shoulderSevere', 'pregnant'],
    anim: {
      view: 0,
      elev: 12,
      props: [{ kind: 'mat' }],
      anchor: ['knL'],
      level: { a: ['elL'], b: ['knL'], axis: 'roll' },
      keys: [
        merge({ root: { roll: 86 } }, both({ hip: { flex: 10 }, kn: 90 }), { shL: { abd: 84 }, elL: 90, shR: { abd: 18, rot: -30 }, elR: 95 }),
        merge({ root: { roll: 72 } }, both({ hip: { flex: 0 }, kn: 90 }), { shL: { abd: 74 }, elL: 90, shR: { abd: 18, rot: -30 }, elR: 95 }),
      ],
      durations: [1.4, 1.4],
      pauses: [0.4, 2.6],
    },
  },
];
