/**
 * 운동 라이브러리 · 고관절·엉덩이
 * 문구·용량·대상 이슈는 물리치료 임상 기준으로 작성되었으며, 전문가가 자유롭게 수정할 수 있습니다.
 * 작성 규칙: docs/CONTENT_GUIDE.md
 */
import { both } from '../../figure/rig';
import { HALF_KNEEL, HANDS_ON_HIPS, HOOK, SIDE_LYING, SIT, STAND, merge } from '../../figure/poses';
import type { Exercise } from '../exercise-types';

export const HIP: Exercise[] = [
  {
    id: 'glute-bridge',
    name: { ko: '글루트 브릿지', en: 'Glute bridge' },
    phase: 'activate',
    position: 'supine',
    regions: ['glute', 'core', 'lowBack'],
    targets: { lordosis: 0.8, swayback: 0.6, lowBackPain: 0.6, kneeValgus: 0.4, kneeHyperext: 0.3, hipPain: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 12, tempo: 3, holdSec: 2, rest: 20 },
    steps: {
      ko: ['무릎을 세우고 누워 발을 골반 너비로 벌려요.', '숨을 내쉬며 배에 힘을 주고 꼬리뼈부터 말아 올리듯 엉덩이를 들어요.', '어깨-골반-무릎이 일직선이 되면 엉덩이를 꽉 조이고 2초.', '허리를 과하게 젖히지 말고 천천히 내려요.'],
      en: ['Lie on your back with knees bent and feet hip-width apart.', 'Exhale, brace your belly and peel your hips up, tailbone first.', 'When shoulders, hips and knees form a line, squeeze your glutes for 2 seconds.', 'Don’t over-arch; lower slowly.'],
    },
    cues: { ko: ['엉덩이 꽉!', '허리 말고 엉덩이로', '천천히 내려요'], en: ['Squeeze the glutes!', 'Hips, not low back', 'Lower slowly'] },
    mistakes: { ko: ['허리를 과하게 젖힘', '무릎이 안쪽으로 모임', '햄스트링에 쥐가 남(발을 몸 쪽으로)'], en: ['Over-arching the back', 'Knees caving in', 'Hamstring cramps (bring feet closer)'] },
    why: { ko: '오래 앉아 잠든 엉덩이 근육을 깨워 골반을 바로 세우고 허리 부담을 덜어 줘요. 오리형 교정의 핵심이에요.', en: 'Wakes up glutes switched off by sitting, levelling the pelvis and unloading the low back — the core of the Duck fix.' },
    muscles: { ko: '대둔근, 햄스트링, 복부', en: 'Gluteus maximus, hamstrings, abs' },
    anim: {
      view: 90,
      elev: 10,
      props: [{ kind: 'mat' }],
      anchor: ['heelL', 'heelR'],
      level: { a: ['backTop'], b: ['heelL', 'heelR'] },
      keys: [
        merge(HOOK, both({ sh: { flex: 0, abd: 8 }, el: 0 })),
        merge(HOOK, { root: { pitch: -114 } }, both({ hip: { flex: -2 }, kn: 102, an: 8, sh: { flex: -24, abd: 8 }, el: 0 })),
      ],
      durations: [1.4, 1.4],
      pauses: [0.4, 2],
    },
    coach: {
      view: 'side',
      metric: 'hipAngle',
      mode: 'reps',
      rest: 140,
      peak: 162,
      dir: 1,
      hint: { ko: '옆에서 온몸이 보이도록 휴대폰을 바닥 높이에 두세요', en: 'Place the phone at floor level beside you so your whole body is visible' },
      more: { ko: '엉덩이를 조금 더 높이', en: 'Hips a little higher' },
      good: { ko: '좋아요, 꽉 조여요', en: 'Great, squeeze' },
    },
  },
  {
    id: 'clamshell',
    name: { ko: '클램쉘', en: 'Clamshell' },
    phase: 'activate',
    position: 'sideLying',
    regions: ['glute', 'hip'],
    targets: { kneeValgus: 1, pelvicTilt: 0.6, hipPain: 0.5, lateralShift: 0.4 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 15, tempo: 2.5, holdSec: 1, perSide: true, rest: 15 },
    steps: {
      ko: ['왼쪽으로 누워 무릎을 45° 굽히고 발뒤꿈치를 모아요.', '골반이 뒤로 넘어가지 않게 위쪽 손으로 골반을 고정해요.', '발은 붙인 채 위쪽 무릎을 조개처럼 벌려요.', '1초 멈췄다 천천히 닫아요.'],
      en: ['Lie on your left side, knees bent 45°, heels together.', 'Keep your top hand on your pelvis so it doesn’t roll back.', 'Keeping the feet together, open the top knee like a clamshell.', 'Pause 1 second and close slowly.'],
    },
    cues: { ko: ['발은 붙인 채', '골반은 그대로', '엉덩이 옆이 뻐근하게'], en: ['Feet together', 'Pelvis still', 'Feel it on the side of the hip'] },
    mistakes: { ko: ['골반이 뒤로 넘어감', '너무 크게 벌림'], en: ['Rolling the pelvis back', 'Opening too far'] },
    why: { ko: '무릎이 안쪽으로 무너지지 않게 잡아 주는 중둔근을 깨워요. X다리 경향과 무릎·골반 통증에 좋아요.', en: 'Wakes up the gluteus medius, which stops the knee caving in — great for knock-knee alignment and knee/hip pain.' },
    muscles: { ko: '중둔근, 고관절 외회전근', en: 'Gluteus medius, hip external rotators' },
    anim: {
      view: 0,
      elev: 25,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [SIDE_LYING, merge(SIDE_LYING, { hipR: { flex: 45, rot: 34, abd: 26 } })],
      durations: [1.1, 1.1],
      pauses: [0.3, 1],
    },
  },
  {
    id: 'side-lying-abduction',
    name: { ko: '옆으로 누워 다리 들기', en: 'Side-lying leg raise' },
    phase: 'activate',
    position: 'sideLying',
    regions: ['glute', 'hip'],
    targets: { pelvicTilt: 0.8, lateralShift: 0.6, kneeValgus: 0.6, hipPain: 0.3 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 12, tempo: 3, holdSec: 1, perSide: true, rest: 15 },
    steps: {
      ko: ['왼쪽으로 누워 아래 다리는 굽히고 위 다리는 쭉 펴요.', '발끝은 정면(또는 살짝 아래)을 향하게 해요.', '뒤꿈치로 밀어내듯 다리를 비스듬히 뒤쪽 위로 들어 올려요.', '1초 멈췄다 천천히 내려요.'],
      en: ['Lie on your left side, bottom leg bent, top leg straight.', 'Point your toes forward (or slightly down).', 'Lead with the heel and lift the leg up and slightly back.', 'Pause 1 second and lower slowly.'],
    },
    cues: { ko: ['뒤꿈치가 먼저', '골반은 앞으로 살짝'], en: ['Lead with the heel', 'Pelvis tipped slightly forward'] },
    mistakes: { ko: ['발끝이 천장을 향함(엉덩이 앞쪽만 씀)', '허리로 들어 올림'], en: ['Toes turning up (using the hip flexor)', 'Hiking with the low back'] },
    why: { ko: '골반의 좌우 균형을 잡는 중둔근을 강화해 짝다리·골반 비대칭을 개선해요.', en: 'Strengthens the gluteus medius that keeps the pelvis level, improving side-to-side asymmetry.' },
    muscles: { ko: '중둔근, 소둔근', en: 'Gluteus medius & minimus' },
    anim: {
      view: 0,
      elev: 20,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [merge(SIDE_LYING, { hipR: { flex: -4 }, knR: 2, anR: 0 }), merge(SIDE_LYING, { hipR: { flex: -8, abd: 36 }, knR: 2, anR: 0 })],
      durations: [1.3, 1.3],
      pauses: [0.3, 1],
    },
  },
  {
    id: 'standing-abduction',
    name: { ko: '서서 다리 옆으로 들기', en: 'Standing hip abduction' },
    phase: 'activate',
    position: 'standing',
    regions: ['glute', 'hip'],
    targets: { pelvicTilt: 0.6, kneeValgus: 0.6, lateralShift: 0.5 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 12, tempo: 2.5, holdSec: 1, perSide: true, rest: 15 },
    desk: true,
    steps: {
      ko: ['의자나 벽을 한 손으로 잡고 바르게 서요.', '몸통을 곧게 세운 채 오른다리를 옆으로 천천히 들어요.', '발끝은 정면, 상체가 반대로 기울지 않게 해요.', '1초 멈췄다 천천히 내려요.'],
      en: ['Hold a chair or wall with one hand and stand tall.', 'Keeping your trunk upright, slowly lift your right leg out to the side.', 'Toes face forward; don’t lean the other way.', 'Pause 1 second and lower slowly.'],
    },
    cues: { ko: ['상체는 곧게', '발끝은 정면'], en: ['Stay tall', 'Toes forward'] },
    mistakes: { ko: ['상체가 반대쪽으로 기울어짐', '다리를 너무 높이 듦'], en: ['Leaning away', 'Lifting too high'] },
    why: { ko: '서서 하는 중둔근 운동으로 골반 좌우 균형과 무릎 정렬을 잡아요. 사무실에서도 가능해요.', en: 'A standing glute-med exercise for pelvic balance and knee alignment — doable at the office.' },
    muscles: { ko: '중둔근', en: 'Gluteus medius' },
    anim: {
      view: 0,
      keys: [merge(STAND, { shL: { abd: 40 }, elL: 20 }), merge(STAND, { shL: { abd: 40 }, elL: 20, hipR: { abd: 30 }, knR: 2 })],
      durations: [1.2, 1.2],
      pauses: [0.3, 0.8],
    },
    coach: {
      view: 'front',
      metric: 'hipAbduction',
      mode: 'reps',
      rest: 9,
      peak: 20,
      dir: 1,
      hint: { ko: '정면에서 온몸이 보이게 휴대폰을 세워 주세요', en: 'Prop the phone in front so your whole body is visible' },
      more: { ko: '조금 더 옆으로', en: 'A little higher' },
      good: { ko: '좋아요!', en: 'Nice!' },
    },
  },
  {
    id: 'half-kneel-hip-flexor',
    name: { ko: '하프 닐링 고관절 앞 스트레칭', en: 'Half-kneeling hip flexor stretch' },
    phase: 'stretch',
    position: 'kneeling',
    regions: ['hip', 'lowBack'],
    targets: { lordosis: 1, swayback: 0.5, lowBackPain: 0.5, kneeHyperext: 0.2 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    steps: {
      ko: ['오른무릎을 바닥에 대고 왼발은 앞에 두는 한쪽 무릎 꿇기 자세를 만들어요.', '꼬리뼈를 아래로 말아 골반을 세우고 오른쪽 엉덩이를 꽉 조여요.', '그대로 몸을 앞으로 살짝 옮겨 오른쪽 고관절 앞이 늘어나면 30초.', '허리를 젖히지 않는 것이 핵심이에요.'],
      en: ['Kneel on your right knee with the left foot in front.', 'Tuck your tailbone under and squeeze your right glute.', 'Shift your body forward slightly until the front of the right hip stretches; hold 30 seconds.', 'The key is not to arch your low back.'],
    },
    cues: { ko: ['꼬리뼈를 아래로', '엉덩이를 조여요', '허리는 젖히지 않게'], en: ['Tailbone down', 'Squeeze the glute', 'No arching'] },
    mistakes: { ko: ['허리를 젖혀 늘리는 척', '앞무릎이 발끝을 한참 넘어감'], en: ['Arching to fake the stretch', 'Front knee far past the toes'] },
    why: { ko: '오래 앉아 짧아진 장요근이 골반을 앞으로 당겨 허리를 휘게 만들어요. 오리궁둥이·요통 교정의 필수 스트레칭이에요.', en: 'Hip flexors shortened by sitting pull the pelvis forward and arch the back — a must-do stretch for anterior tilt and back pain.' },
    muscles: { ko: '장요근, 대퇴직근', en: 'Iliopsoas, rectus femoris' },
    caution: { ko: '무릎이 아프면 수건을 접어 받치거나 ‘서서 고관절 앞 늘리기’로 대신하세요.', en: 'If the knee hurts, pad it with a towel or do the standing version instead.' },
    avoid: ['kneePain', 'kneeSevere'],
    anim: {
      view: 90,
      props: [{ kind: 'mat' }],
      anchor: ['knR'],
      keys: [merge(HALF_KNEEL, HANDS_ON_HIPS), merge(HALF_KNEEL, HANDS_ON_HIPS, { hipL: { flex: 70 }, knL: 102, anL: 30, hipR: { flex: -28 }, knR: 64, lumbar: { flex: 4 } })],
      durations: [1.8, 1.8],
      pauses: [0.5, 3],
    },
  },
  {
    id: 'standing-hip-flexor',
    name: { ko: '서서 고관절 앞 늘리기', en: 'Standing hip flexor stretch' },
    phase: 'stretch',
    position: 'standing',
    regions: ['hip'],
    targets: { lordosis: 0.8, swayback: 0.4, lowBackPain: 0.4 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['왼발을 앞으로 크게 한 걸음 내딛고 오른발 뒤꿈치는 들어요.', '꼬리뼈를 말아 넣고 오른쪽 엉덩이를 조여요.', '앞무릎을 살짝 굽히며 골반을 앞으로 보내요.', '오른쪽 허벅지 앞~사타구니가 당기면 30초.'],
      en: ['Take a big step forward with the left foot; lift the right heel.', 'Tuck your tailbone and squeeze the right glute.', 'Bend the front knee a little and move your pelvis forward.', 'Hold 30 seconds when you feel the front of the right hip stretch.'],
    },
    cues: { ko: ['꼬리뼈를 아래로', '상체는 곧게'], en: ['Tailbone down', 'Upper body tall'] },
    mistakes: { ko: ['허리를 뒤로 젖힘', '골반이 돌아감'], en: ['Leaning back through the spine', 'Rotating the pelvis'] },
    why: { ko: '무릎을 꿇기 어려운 사무실에서도 할 수 있는 고관절 굴곡근 스트레칭이에요.', en: 'A hip-flexor stretch you can do at the office without kneeling.' },
    muscles: { ko: '장요근, 대퇴직근', en: 'Iliopsoas, rectus femoris' },
    anim: {
      view: 90,
      anchor: ['toeR'],
      keys: [
        merge(STAND, HANDS_ON_HIPS, { hipL: { flex: 24 }, knL: 10, hipR: { flex: -18 }, knR: 6, anR: -14 }),
        merge(STAND, HANDS_ON_HIPS, { hipL: { flex: 30 }, knL: 34, anL: 14, hipR: { flex: -30 }, knR: 10, anR: -24, lumbar: { flex: 4 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.5, 3],
    },
  },
  {
    id: 'figure4-stretch',
    name: { ko: '의자 4자 엉덩이 스트레칭', en: 'Seated figure-4 stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['glute', 'hip', 'lowBack'],
    targets: { hipPain: 0.8, lowBackPain: 0.6, pelvicTilt: 0.4, stiffness: 0.4 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자에 앉아 오른발목을 왼무릎 위에 올려 숫자 4 모양을 만들어요.', '허리를 곧게 편 채 가슴을 앞으로 천천히 숙여요.', '오른쪽 엉덩이 깊은 곳이 당기면 30초 유지해요.'],
      en: ['Sit and cross your right ankle over your left knee to make a “4”.', 'Keep your back long and slowly hinge your chest forward.', 'Hold 30 seconds when you feel a stretch deep in the right glute.'],
    },
    cues: { ko: ['등은 곧게', '가슴을 앞으로'], en: ['Long back', 'Chest forward'] },
    mistakes: { ko: ['등을 둥글게 말아 숙임', '무릎을 억지로 누름'], en: ['Rounding the back to fold', 'Forcing the knee down'] },
    why: { ko: '오래 앉으면 굳는 엉덩이 깊은 근육(이상근)을 풀어 골반·허리 긴장과 엉덩이 뻐근함을 줄여요.', en: 'Releases deep hip rotators like the piriformis that stiffen with sitting, easing pelvic and low-back tension.' },
    muscles: { ko: '이상근, 대둔근, 고관절 외회전근', en: 'Piriformis, gluteus maximus, hip external rotators' },
    avoid: ['kneeSevere'],
    anim: {
      view: 30,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { hipR: { flex: 96, abd: 34, rot: 62 }, knR: 104, anR: 0, shR: { flex: 30, abd: 10 }, elR: 50 }),
        merge(SIT, { hipR: { flex: 108, abd: 34, rot: 62 }, knR: 104, anR: 0, hipL: { flex: 100 }, shR: { flex: 40, abd: 10 }, elR: 40, shL: { flex: 40 }, elL: 50, lumbar: { flex: 12 }, thorax: { flex: 6 }, neck: { flex: -8 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.4, 3],
    },
  },
  {
    id: 'butterfly',
    name: { ko: '나비 자세 (허벅지 안쪽)', en: 'Butterfly stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['hip'],
    targets: { kneeValgus: 0.6, hipPain: 0.4, pelvicTilt: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, rest: 5 },
    steps: {
      ko: ['바닥에 앉아 두 발바닥을 마주 붙이고 무릎을 옆으로 떨어뜨려요.', '발을 두 손으로 잡고 허리를 곧게 세워요.', '숨을 내쉬며 가슴을 앞으로 살짝 숙여요.', '허벅지 안쪽이 당기면 30초.'],
      en: ['Sit with the soles of your feet together, knees falling out.', 'Hold your feet and sit up tall.', 'Exhale and lean your chest forward a little.', 'Hold 30 seconds when your inner thighs stretch.'],
    },
    cues: { ko: ['허리는 곧게', '무릎은 힘을 빼요'], en: ['Tall spine', 'Let the knees relax'] },
    mistakes: { ko: ['무릎을 손으로 억지로 누름', '등을 둥글게 말기'], en: ['Pushing the knees down', 'Rounding the back'] },
    why: { ko: '짧아진 내전근은 무릎을 안쪽으로 끌어 X다리 경향을 키워요.', en: 'Tight adductors pull the knees inward and feed knock-knee alignment.' },
    muscles: { ko: '고관절 내전근', en: 'Hip adductors' },
    avoid: ['kneeSevere'],
    anim: {
      view: 0,
      elev: 34,
      props: [{ kind: 'mat' }],
      anchor: ['sitL', 'sitR'],
      keys: [
        merge({ root: { pitch: -8 } }, both({ hip: { flex: 84, hab: 46, rot: 80 }, kn: 128, an: 10, sh: { flex: 46, hab: -10 }, el: 30 })),
        merge({ root: { pitch: 6 } }, both({ hip: { flex: 84, hab: 56, rot: 84 }, kn: 128, an: 10, sh: { flex: 58, hab: -8 }, el: 22 }), { lumbar: { flex: 10 }, thorax: { flex: 6 } }),
      ],
      durations: [1.8, 1.8],
      pauses: [0.4, 3],
    },
  },
];
