/**
 * 운동 라이브러리 · 무릎·하체 근력
 * 문구·용량·대상 이슈는 물리치료 임상 기준으로 작성되었으며, 전문가가 자유롭게 수정할 수 있습니다.
 * 작성 규칙: docs/CONTENT_GUIDE.md
 */
import { both } from '../../figure/rig';
import { ARMS_CROSSED, HANDS_ON_HIPS, SIT, STAND, merge } from '../../figure/poses';
import type { Exercise } from '../exercise-types';

export const LEGS: Exercise[] = [
  {
    id: 'squat',
    name: { ko: '맨몸 스쿼트', en: 'Bodyweight squat' },
    phase: 'integrate',
    position: 'standing',
    regions: ['glute', 'knee', 'hip'],
    targets: { kneeValgus: 0.7, kneeHyperext: 0.4, lordosis: 0.3, hipPain: 0.2 },
    equipment: [],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 4, rest: 30 },
    steps: {
      ko: ['발을 어깨너비로 벌리고 발끝은 살짝 바깥을 향해요.', '엉덩이를 뒤로 빼며 의자에 앉듯 내려가요. 무릎은 발끝 방향으로.', '허벅지가 바닥과 평행해질 때까지(편한 만큼) 내려가요.', '발바닥 전체로 바닥을 밀며 일어나 엉덩이를 조여요.'],
      en: ['Feet shoulder-width, toes slightly out.', 'Push your hips back and sit down as if into a chair; knees track over the toes.', 'Go down until your thighs are about parallel (as far as is comfortable).', 'Drive through the whole foot to stand and squeeze your glutes.'],
    },
    cues: { ko: ['엉덩이를 뒤로', '무릎은 발끝 방향', '발바닥 전체로 밀어요'], en: ['Hips back', 'Knees over toes', 'Push through the whole foot'] },
    mistakes: { ko: ['무릎이 안쪽으로 모임', '발뒤꿈치가 뜸', '허리가 둥글게 말림'], en: ['Knees caving in', 'Heels lifting', 'Back rounding'] },
    why: { ko: '교정한 정렬을 실제 움직임에서 쓰도록 연결하는 통합 운동이에요. 무릎 정렬과 엉덩이 힘을 동시에 길러요.', en: 'Integrates your new alignment into real movement, training knee tracking and glute strength together.' },
    muscles: { ko: '대둔근, 대퇴사두근, 코어', en: 'Glutes, quads, core' },
    caution: { ko: '무릎이 아프면 의자 앉았다 일어서기로 대신하세요.', en: 'If your knees hurt, do sit-to-stands instead.' },
    avoid: ['kneeSevere', 'kneePain'],
    anim: {
      view: 90,
      keys: [merge(STAND, both({ sh: { flex: 20 }, el: 10 })), merge(both({ hip: { flex: 100 }, kn: 108, an: 26, sh: { flex: 88 }, el: 4 }), { lumbar: { flex: 14 }, thorax: { flex: 8 }, neck: { flex: -16 } })],
      durations: [1.8, 1.6],
      pauses: [0.3, 0.3],
    },
    coach: {
      view: 'side',
      metric: 'kneeAngle',
      mode: 'reps',
      rest: 160,
      peak: 115,
      dir: -1,
      hint: { ko: '옆에서 온몸이 보이게 2~3m 떨어진 곳에 휴대폰을 세워 주세요', en: 'Place the phone 2–3 m to your side so your whole body is visible' },
      more: { ko: '조금 더 깊게', en: 'A little deeper' },
      good: { ko: '좋아요!', en: 'Good depth!' },
    },
  },
  {
    id: 'sit-to-stand',
    name: { ko: '의자 앉았다 일어서기', en: 'Sit-to-stand' },
    phase: 'integrate',
    position: 'standing',
    regions: ['glute', 'knee'],
    targets: { kneeValgus: 0.5, kneePain: 0.3, hipPain: 0.3, lowBackPain: 0.2 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 4, rest: 30 },
    desk: true,
    steps: {
      ko: ['의자 앞쪽에 앉아 발을 골반 너비로 두고 팔은 가슴 앞에 모아요.', '코가 발끝 위로 오도록 상체를 숙이며', '발바닥으로 바닥을 밀어 일어서요. 끝에서 엉덩이를 조여요.', '엉덩이를 뒤로 빼며 천천히 앉아요(털썩 금지).'],
      en: ['Sit near the front of a chair, feet hip-width, arms crossed on your chest.', 'Lean forward until your nose is over your toes,', 'then push through your feet to stand, squeezing your glutes at the top.', 'Reach your hips back and sit down slowly — no plopping.'],
    },
    cues: { ko: ['코는 발끝 위로', '천천히 앉아요', '무릎은 발끝 방향'], en: ['Nose over toes', 'Sit down slowly', 'Knees over toes'] },
    mistakes: { ko: ['손으로 짚고 일어남', '무릎이 안으로 모임'], en: ['Pushing up with the hands', 'Knees caving in'] },
    why: { ko: '일상에서 가장 많이 하는 동작으로 엉덩이·허벅지 힘과 무릎 정렬을 훈련해요. 무릎이 불편한 분께 스쿼트 대신 추천해요.', en: 'Trains glute and thigh strength plus knee tracking in the move you do most every day — a knee-friendly squat alternative.' },
    muscles: { ko: '대둔근, 대퇴사두근', en: 'Glutes, quads' },
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      anchor: ['heelL', 'heelR'],
      keys: [merge(SIT, ARMS_CROSSED, { lumbar: { flex: 6 } }), merge(ARMS_CROSSED, { root: { pitch: 0 } })],
      durations: [1.8, 1.8],
      pauses: [0.4, 0.4],
    },
    coach: {
      view: 'side',
      metric: 'kneeAngle',
      mode: 'reps',
      rest: 160,
      peak: 110,
      dir: -1,
      hint: { ko: '옆에서 의자와 온몸이 보이게 휴대폰을 세워 주세요', en: 'Place the phone beside you so you and the chair are visible' },
      more: { ko: '끝까지 앉았다 일어나요', en: 'Sit all the way down' },
      good: { ko: '좋아요!', en: 'Nice!' },
    },
  },
  {
    id: 'split-squat',
    name: { ko: '스플릿 스쿼트', en: 'Split squat' },
    phase: 'integrate',
    position: 'standing',
    regions: ['glute', 'knee', 'hip'],
    targets: { kneeValgus: 0.6, pelvicTilt: 0.5, lateralShift: 0.4 },
    equipment: [],
    level: 3,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 4, perSide: true, rest: 30 },
    steps: {
      ko: ['왼발을 앞으로 크게 한 걸음, 오른발은 뒤에 두고 뒤꿈치를 들어요.', '상체를 곧게 세운 채 뒷무릎을 바닥 가까이 수직으로 내려요.', '앞무릎은 발끝 방향, 골반은 수평을 유지해요.', '앞발 뒤꿈치로 밀며 올라와요.'],
      en: ['Step your left foot forward, right foot back with the heel up.', 'Stay tall and lower the back knee straight down toward the floor.', 'Front knee tracks over the toes; keep the pelvis level.', 'Drive through the front heel to rise.'],
    },
    cues: { ko: ['수직으로 내려가요', '앞무릎은 발끝 방향', '골반 수평'], en: ['Straight down', 'Front knee over toes', 'Level pelvis'] },
    mistakes: { ko: ['앞무릎이 안쪽으로', '상체가 앞으로 쏠림'], en: ['Front knee caving', 'Leaning forward'] },
    why: { ko: '한쪽 다리로 버티며 좌우 근력 차이와 골반 안정성을 동시에 잡는 고급 통합 운동이에요.', en: 'An advanced single-leg move that fixes left–right strength gaps and pelvic stability together.' },
    muscles: { ko: '대둔근, 중둔근, 대퇴사두근', en: 'Glutes, glute med, quads' },
    avoid: ['kneeSevere', 'kneePain', 'balance'],
    anim: {
      view: 90,
      anchor: ['toeL'],
      keys: [
        merge(HANDS_ON_HIPS, { hipL: { flex: 26 }, knL: 6, hipR: { flex: -22 }, knR: 8, anR: -30 }),
        merge(HANDS_ON_HIPS, { hipL: { flex: 82 }, knL: 92, anL: 18, hipR: { flex: -12 }, knR: 100, anR: -40 }),
      ],
      durations: [1.8, 1.6],
      pauses: [0.3, 0.3],
    },
  },
  {
    id: 'hip-hinge',
    name: { ko: '힙 힌지 (인사 동작)', en: 'Hip hinge' },
    phase: 'integrate',
    position: 'standing',
    regions: ['hip', 'lowBack', 'glute'],
    targets: { lowBackPain: 0.5, swayback: 0.4, kneeHyperext: 0.5, flatBack: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 4, rest: 20 },
    steps: {
      ko: ['발을 골반 너비로 벌리고 무릎을 살짝 굽혀요.', '손을 골반에 대고 허리를 곧게 편 채 엉덩이를 뒤로 쭉 빼며 인사하듯 숙여요.', '허벅지 뒤가 당기면 엉덩이를 조이며 일어나요.', '등이 둥글게 말리지 않게 해요.'],
      en: ['Feet hip-width, knees softly bent.', 'Hands on hips, back long, push your hips back and bow forward.', 'When the backs of your thighs pull, squeeze your glutes to stand.', 'Don’t let your back round.'],
    },
    cues: { ko: ['엉덩이를 뒤로', '등은 곧게', '엉덩이 조이며 일어나요'], en: ['Hips back', 'Long back', 'Squeeze up'] },
    mistakes: { ko: ['허리로 숙임', '무릎을 너무 많이 굽힘(스쿼트가 됨)'], en: ['Bending from the back', 'Bending the knees too much (it becomes a squat)'] },
    why: { ko: '물건을 들 때 허리 대신 고관절을 쓰는 패턴을 익혀요. 무릎을 잠그고 서는 습관(과신전) 교정에도 좋아요.', en: 'Teaches you to bend from the hips instead of the spine — also great for breaking the locked-knee habit.' },
    muscles: { ko: '햄스트링, 대둔근, 척추 안정근', en: 'Hamstrings, glutes, spinal stabilisers' },
    avoid: ['lowBackSevere'],
    anim: {
      view: 90,
      keys: [merge(STAND, HANDS_ON_HIPS, both({ kn: 8, hip: { flex: 2 } })), merge(HANDS_ON_HIPS, { root: { pitch: 52 }, neck: { flex: -14 } }, both({ hip: { flex: 64 }, kn: 22, an: 10 }))],
      durations: [1.8, 1.8],
      pauses: [0.3, 0.5],
    },
  },
  {
    id: 'seated-hamstring',
    name: { ko: '의자 햄스트링 스트레칭', en: 'Seated hamstring stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['hip', 'knee'],
    targets: { kneeFlexed: 0.8, flatBack: 0.6, lowBackPain: 0.4, swayback: 0.3 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자 끝에 걸터앉아 오른다리를 앞으로 쭉 펴고 발끝을 세워요.', '허리를 편 채 골반부터 앞으로 숙여요(등을 둥글게 말지 않기).', '오른쪽 허벅지 뒤가 당기면 30초 유지해요.'],
      en: ['Sit on the edge of the chair, right leg straight out, toes up.', 'Keeping your back long, hinge forward from the hips (don’t round).', 'Hold 30 seconds when you feel the back of the right thigh stretch.'],
    },
    cues: { ko: ['골반부터 숙여요', '등은 곧게'], en: ['Hinge from the hips', 'Long back'] },
    mistakes: { ko: ['등을 말아서 숙임', '무릎을 굽힘'], en: ['Rounding the back', 'Bending the knee'] },
    why: { ko: '짧은 햄스트링은 골반을 뒤로 당겨 허리를 일자로 만들고 요통을 부를 수 있어요.', en: 'Tight hamstrings tug the pelvis backward, flattening the low back and inviting pain.' },
    muscles: { ko: '햄스트링', en: 'Hamstrings' },
    caution: { ko: '다리 뒤로 저린 느낌(신경 당김)이 나면 발끝을 내리고 강도를 줄이세요.', en: 'If you feel tingling down the leg (nerve tension), point the toes and ease off.' },
    avoid: ['radiating'],
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { hipR: { flex: 70 }, knR: 6, anR: 18 }),
        merge(SIT, { root: { pitch: 20 }, hipR: { flex: 92 }, knR: 6, anR: 18, hipL: { flex: 108 }, knL: 88 }, both({ sh: { flex: 50 }, el: 20 })),
      ],
      durations: [1.8, 1.8],
      pauses: [0.4, 3],
    },
  },
  {
    id: 'quad-stretch',
    name: { ko: '서서 허벅지 앞 스트레칭', en: 'Standing quad stretch' },
    phase: 'stretch',
    position: 'standing',
    regions: ['hip', 'knee'],
    targets: { lordosis: 0.6, kneeHyperext: 0.3, swayback: 0.3 },
    equipment: ['wall'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    steps: {
      ko: ['벽이나 의자를 왼손으로 잡고 서요.', '오른무릎을 굽혀 오른손으로 발등(또는 발목)을 잡아요.', '무릎은 아래를 향하게 하고 꼬리뼈를 말아 넣어요.', '허벅지 앞이 당기면 30초.'],
      en: ['Stand holding a wall or chair with your left hand.', 'Bend your right knee and hold the top of the foot (or ankle) with your right hand.', 'Point the knee down and tuck your tailbone.', 'Hold 30 seconds when the front of the thigh stretches.'],
    },
    cues: { ko: ['무릎은 아래로', '꼬리뼈를 말아요'], en: ['Knee points down', 'Tuck the tailbone'] },
    mistakes: { ko: ['허리를 젖힘', '무릎이 옆으로 벌어짐'], en: ['Arching the back', 'Knee drifting outward'] },
    why: { ko: '골반을 앞으로 당기는 대퇴직근을 늘려 골반 전방경사를 완화해요.', en: 'Lengthens the rectus femoris, which pulls the pelvis into anterior tilt.' },
    muscles: { ko: '대퇴사두근(대퇴직근)', en: 'Quadriceps (rectus femoris)' },
    caution: { ko: '무릎이 아프면 수건을 발목에 걸어 당기세요.', en: 'If your knee hurts, loop a towel around the ankle instead.' },
    avoid: ['kneeSevere', 'balance'],
    anim: {
      view: 90,
      props: [{ kind: 'wall', wall: 'front', dist: 12 }],
      keys: [
        merge(STAND, { shL: { flex: 80 }, elL: 10 }),
        merge(STAND, { shL: { flex: 80 }, elL: 10, hipR: { flex: -8 }, knR: 145, anR: -30, shR: { flex: -42, abd: 10 }, elR: 8, lumbar: { flex: 3 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.4, 3],
    },
  },
];
