/**
 * 운동 라이브러리 · 허리
 * 문구·용량·대상 이슈는 물리치료 임상 기준으로 작성되었으며, 전문가가 자유롭게 수정할 수 있습니다.
 * 작성 규칙: docs/CONTENT_GUIDE.md
 */
import { both } from '../../figure/rig';
import { HOOK, QUAD, STAND, merge } from '../../figure/poses';
import type { Exercise } from '../exercise-types';

export const LOWBACK: Exercise[] = [
  {
    id: 'cat-cow',
    name: { ko: '고양이-소 자세', en: 'Cat-cow' },
    phase: 'mobility',
    position: 'quadruped',
    regions: ['lowBack', 'upperBack'],
    targets: { stiffness: 0.8, lowBackPain: 0.6, kyphosis: 0.4, lordosis: 0.3, stress: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 5, rest: 10 },
    steps: {
      ko: ['네발 자세에서 손목은 어깨 아래, 무릎은 골반 아래에 둬요.', '숨을 내쉬며 배꼽을 당겨 등을 둥글게 말아요(고양이).', '숨을 들이쉬며 가슴을 앞으로 내밀고 꼬리뼈를 들어 등을 오목하게(소).', '통증 없는 범위에서 척추 마디마디를 느끼며 천천히.'],
      en: ['On all fours, wrists under shoulders, knees under hips.', 'Exhale, draw your belly in and round your back (cat).', 'Inhale, lift your chest and tailbone, letting the back dip (cow).', 'Move slowly through a pain-free range, one vertebra at a time.'],
    },
    cues: { ko: ['내쉬며 둥글게', '들이쉬며 오목하게', '천천히'], en: ['Exhale, round', 'Inhale, arch', 'Nice and slow'] },
    mistakes: { ko: ['팔꿈치를 굽혀 움직임', '목만 크게 움직임'], en: ['Bending the elbows', 'Moving only the neck'] },
    why: { ko: '오래 같은 자세로 굳은 척추 전체를 부드럽게 움직여 뻐근함을 풀고 호흡과 움직임을 연결해요.', en: 'Gently moves the whole spine after long static postures, easing stiffness and linking breath with movement.' },
    muscles: { ko: '척추 전체 가동성', en: 'Whole-spine mobility' },
    avoid: ['wristPain', 'kneePain'],
    anim: {
      view: 90,
      elev: 14,
      props: [{ kind: 'mat' }],
      anchor: ['knL', 'knR'],
      keys: [
        merge(QUAD, { lumbar: { flex: 16 }, thorax: { flex: 20 }, neck: { flex: 26 }, root: { pitch: 76 } }, both({ sh: { flex: 112 }, hip: { flex: 76 } })),
        merge(QUAD, { lumbar: { flex: -16 }, thorax: { flex: -8 }, neck: { flex: -30 }, root: { pitch: 84 } }, both({ sh: { flex: 60 }, hip: { flex: 84 } })),
      ],
      durations: [2.4, 2.4],
      pauses: [0.3, 0.3],
    },
  },
  {
    id: 'child-pose',
    name: { ko: '아기 자세', en: 'Child’s pose' },
    phase: 'stretch',
    position: 'kneeling',
    regions: ['lowBack', 'upperBack', 'hip'],
    targets: { lowBackPain: 0.6, stiffness: 0.6, stress: 0.5, kyphosis: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, rest: 5 },
    steps: {
      ko: ['무릎을 꿇고 앉아 엉덩이를 발뒤꿈치 쪽으로 내려요.', '팔을 앞으로 길게 뻗어 이마를 바닥 가까이 내려요.', '숨을 등 쪽으로 불어 넣듯 깊게 쉬며 30초 머물러요.'],
      en: ['Kneel and sink your hips back toward your heels.', 'Reach your arms long in front and let your forehead lower toward the floor.', 'Breathe deeply into your back and rest for 30 seconds.'],
    },
    cues: { ko: ['엉덩이는 뒤꿈치로', '등으로 숨 쉬어요'], en: ['Hips to heels', 'Breathe into your back'] },
    mistakes: { ko: ['무릎 통증을 참음(방석을 받쳐요)'], en: ['Pushing through knee pain (use a cushion)'] },
    why: { ko: '허리와 등을 부드럽게 늘리며 긴장을 내려놓는 휴식 자세예요. 루틴 사이사이 쉬기에도 좋아요.', en: 'A resting stretch that gently lengthens the back and lets tension go — great between harder moves.' },
    muscles: { ko: '광배근, 척추기립근, 둔근', en: 'Lats, spinal erectors, glutes' },
    avoid: ['kneePain', 'kneeSevere'],
    anim: {
      view: 90,
      elev: 12,
      props: [{ kind: 'mat' }],
      anchor: ['knL', 'knR'],
      keys: [
        merge({ root: { pitch: 0 } }, both({ hip: { flex: 70 }, kn: 160, an: -75, sh: { flex: 168 }, el: 5 })),
        merge({ root: { pitch: 80 } }, both({ hip: { flex: 150 }, kn: 160, an: -75, sh: { flex: 192 }, el: 2 }), { lumbar: { flex: 22 }, thorax: { flex: 12 }, neck: { flex: 10 } }),
      ],
      durations: [2, 2],
      pauses: [0.3, 3],
    },
  },
  {
    id: 'pelvic-tilt',
    name: { ko: '누워서 골반 기울이기', en: 'Supine pelvic tilt' },
    phase: 'mobility',
    position: 'supine',
    regions: ['lowBack', 'core'],
    targets: { lordosis: 0.7, lowBackPain: 0.6, swayback: 0.4, flatBack: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 4, rest: 10 },
    steps: {
      ko: ['무릎을 세우고 누워요.', '숨을 들이쉬며 허리를 살짝 띄워 골반을 앞으로 기울여요.', '숨을 내쉬며 배꼽을 당겨 허리를 바닥에 지그시 붙여요(꼬리뼈가 살짝 들림).', '천천히 시소처럼 반복해요.'],
      en: ['Lie on your back with knees bent.', 'Inhale and gently arch your low back, tipping the pelvis forward.', 'Exhale, draw your belly in and press your low back into the floor (tailbone lifts slightly).', 'Rock slowly back and forth like a seesaw.'],
    },
    cues: { ko: ['들이쉬며 오목', '내쉬며 꾹'], en: ['Inhale, arch', 'Exhale, flatten'] },
    mistakes: { ko: ['엉덩이를 들어 올림', '다리 힘으로 밀기'], en: ['Lifting the hips', 'Pushing with the legs'] },
    why: { ko: '골반 위치를 스스로 조절하는 감각을 되찾는 첫 단계예요. 허리가 뻐근한 날 가장 먼저 해 보세요.', en: 'The first step to feeling and controlling your pelvic position — try it first on a stiff-back day.' },
    muscles: { ko: '복부, 골반 주변 근육 조절', en: 'Abdominal & pelvic control' },
    anim: {
      view: 90,
      elev: 12,
      props: [{ kind: 'mat' }],
      anchor: ['heelL', 'heelR'],
      keys: [merge(HOOK, { root: { pitch: -80 }, lumbar: { flex: -10 } }, both({ hip: { flex: 65 } })), merge(HOOK, { root: { pitch: -99 }, lumbar: { flex: 9 } }, both({ hip: { flex: 46 } }))],
      durations: [2, 2],
      pauses: [0.3, 0.6],
      zoom: 1.15,
    },
  },
  {
    id: 'standing-side-bend',
    name: { ko: '서서 옆구리 늘리기', en: 'Standing side bend' },
    phase: 'stretch',
    position: 'standing',
    regions: ['lowBack', 'core'],
    targets: { pelvicTilt: 0.8, lateralShift: 0.8, lowBackPain: 0.4, stiffness: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 20, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['발을 골반 너비로 벌리고 서요.', '왼팔을 머리 위로 쭉 뻗어요.', '골반은 제자리에 둔 채 상체를 오른쪽으로 천천히 기울여요.', '왼쪽 옆구리가 길게 늘어나면 20초.'],
      en: ['Stand with feet hip-width apart.', 'Reach your left arm overhead.', 'Keeping the pelvis still, slowly bend your upper body to the right.', 'Hold 20 seconds when the left side lengthens.'],
    },
    cues: { ko: ['위로 길게, 옆으로', '골반은 가운데'], en: ['Up long, then over', 'Pelvis stays centred'] },
    mistakes: { ko: ['몸이 앞으로 숙여짐', '골반이 옆으로 빠짐'], en: ['Leaning forward', 'Hips sliding sideways'] },
    why: { ko: '한쪽 허리 옆(요방형근)이 짧아지면 골반 높이가 달라져요. 높은 쪽 골반과 같은 쪽 옆구리를 더 늘려 주세요.', en: 'A short quadratus lumborum hitches one side of the pelvis. Stretch the side of the higher hip a bit more.' },
    muscles: { ko: '요방형근, 광배근, 복사근', en: 'Quadratus lumborum, lats, obliques' },
    anim: {
      view: 0,
      keys: [merge(STAND, { shL: { abd: 160 }, elL: 12 }), merge(STAND, { shL: { abd: 172 }, elL: 10, lumbar: { side: -12 }, thorax: { side: -15 }, neck: { side: -4 } })],
      durations: [1.6, 1.6],
      pauses: [0.4, 3],
    },
    coach: {
      view: 'front',
      metric: 'trunkSide',
      mode: 'hold',
      target: 10,
      dir: 1,
      hint: { ko: '정면에서 온몸이 보이게 휴대폰을 세워 주세요', en: 'Prop the phone in front so your whole body is visible' },
      more: { ko: '조금 더 옆으로', en: 'A bit further to the side' },
      good: { ko: '좋아요, 그대로', en: 'Great, stay there' },
    },
  },
];
