/**
 * 운동 라이브러리 · 목
 * 문구·용량·대상 이슈는 물리치료 임상 기준으로 작성되었으며, 전문가가 자유롭게 수정할 수 있습니다.
 * 작성 규칙: docs/CONTENT_GUIDE.md
 */
import { HANDS_BEHIND_HEAD, HOOK, SIT, merge } from '../../figure/poses';
import type { Exercise } from '../exercise-types';

export const NECK: Exercise[] = [
  {
    id: 'chin-tuck',
    name: { ko: '턱 당기기', en: 'Chin tuck' },
    phase: 'activate',
    position: 'seated',
    regions: ['neck'],
    targets: { fhp: 1, neckPain: 0.7, headache: 0.5 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 2, holdSec: 5, rest: 15 },
    desk: true,
    setup: {
      ko: [
        '의자 앞쪽 1/3에 앉아 두 발을 골반 너비로 벌려 바닥에 평평하게 둬요.',
        '골반을 세워 허리를 곧게 펴고, 어깨는 한 번 으쓱했다가 툭 떨어뜨려 힘을 빼요.',
        '시선은 정면 눈높이의 한 점에 두고, 턱 밑이 바닥과 평행하게 해요.',
      ],
      en: [
        'Sit on the front third of the chair, feet flat and hip-width apart.',
        'Stack your pelvis upright so your low back is tall; shrug once and let your shoulders drop.',
        'Fix your eyes on a point at eye level so the underside of your chin is parallel to the floor.',
      ],
    },
    steps: {
      ko: [
        '시선은 그대로 둔 채, 머리 전체를 수평으로 뒤로 천천히 밀어요. 턱이 목 쪽으로 따라 들어오며 “이중턱”이 생겨요.',
        '뒤통수가 위로 길어지는 느낌이 드는 지점(1~2cm)까지 밀고 멈춰요.',
        '그 자리에서 5초 버텨요.',
        '2초에 걸쳐 천천히 처음 자리로 돌아와요.',
        '10회 반복해요. 매 회 시선과 어깨 높이는 그대로예요.',
      ],
      en: [
        'Keeping your eyes level, slowly glide your whole head straight back. Your chin follows in and you make a “double chin”.',
        'Stop when the back of your head feels long and lifted — about 1–2 cm of movement.',
        'Hold there for 5 seconds.',
        'Take 2 seconds to return slowly to the start.',
        'Repeat 10 times, keeping your gaze and shoulder height unchanged.',
      ],
    },
    breathing: { ko: '머리를 뒤로 밀면서 입으로 “후—” 내쉬고, 버티는 5초 동안은 코로 편하게 숨 쉬어요. 숨을 참지 마세요.', en: 'Exhale through your mouth as you glide back, then breathe easily through your nose during the 5-second hold. Don’t hold your breath.' },
    feel: { ko: '목 앞쪽 깊은 곳이 은은하게 조이고, 뒷목과 머리 뒤쪽이 위로 길게 늘어나는 느낌이면 정답이에요. 목 앞 표면(굵은 근육)이 불룩 튀어나오면 너무 세게 한 거예요.', en: 'A gentle tightening deep in the front of your neck and a long, lifted feeling at the back of your neck. If the big cords at the front of your neck pop out, you’re pushing too hard.' },
    easier: { ko: '벽에 등과 뒤통수를 대고 서서, 뒤통수로 벽을 살짝 누르듯이 해 보세요. 움직임이 작아도 괜찮아요.', en: 'Stand with your back and head against a wall and gently press the back of your head into it. A tiny movement is fine.' },
    harder: { ko: '버티는 시간을 10초로 늘리거나, ‘누워서 턱 당겨 머리 들기’로 넘어가세요.', en: 'Increase the hold to 10 seconds, or progress to the supine chin-tuck head lift.' },
    cues: { ko: ['뒤통수를 뒤로 쭉', '시선은 정면 그대로', '어깨는 툭 내려요', '5초 버텨요'], en: ['Slide your head back', 'Eyes stay level', 'Let your shoulders drop', 'Hold for five'] },
    mistakes: {
      ko: [
        '고개를 아래로 끄덕임 → 턱을 가슴으로 숙이지 말고, 시선을 정면에 둔 채 머리를 수평으로 뒤로 밀어요.',
        '어깨가 함께 올라감 → 시작 전에 어깨를 으쓱했다가 툭 떨어뜨리고, 목만 움직여요.',
        '허리가 구부정해짐 → 골반을 세워 앉고 정수리를 천장으로 길게 뻗은 상태에서 해요.',
        '숨을 참음 → 밀 때 내쉬고, 버티는 동안 코로 숨 쉬어요.',
      ],
      en: [
        'Nodding the head down → Don’t drop your chin to your chest; keep your eyes level and glide straight back.',
        'Shoulders creeping up → Shrug and drop them before you start, then move only your neck.',
        'Slumping the low back → Sit on your sit bones and reach the crown of your head toward the ceiling.',
        'Holding your breath → Exhale as you glide, breathe through your nose while holding.',
      ],
    },
    why: { ko: '약해진 심부 목굽힘근을 깨워 앞으로 나온 머리를 어깨 위로 되돌리는, 거북목 교정의 가장 기본 운동이에요.', en: 'Wakes up the weak deep neck flexors to bring your head back over your shoulders — the foundation of fixing tech neck.' },
    muscles: { ko: '심부 목굽힘근(두장근·경장근)', en: 'Deep neck flexors (longus capitis/colli)' },
    caution: { ko: '어지럽거나 팔이 저리면 바로 멈추세요.', en: 'Stop if you feel dizzy or your arms tingle.' },
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      keys: [merge(SIT, { neck: { flex: 12 }, head: { flex: -10 } }), merge(SIT, { neck: { flex: -8 }, head: { flex: 10 } })],
      labels: [
        { ko: '바르게 앉아 정면 보기', en: 'Sit tall, eyes level' },
        { ko: '머리를 뒤로 밀어 5초', en: 'Glide back, hold 5 s' },
      ],
      durations: [1.1, 1.1],
      pauses: [0.8, 2.4],
      focus: [
        { a: 'chest', b: 'neckTop', side: 'front', kind: 'work', r: 2.2 },
        { a: 'neckTop', b: 'head', side: 'back', kind: 'stretch', r: 2, from: 0, to: 0.7 },
      ],
      trace: ['nose'],
      zoom: 1.25,
    },
  },
  {
    id: 'supine-chin-lift',
    name: { ko: '누워서 턱 당겨 머리 들기', en: 'Supine chin-tuck head lift' },
    phase: 'activate',
    position: 'supine',
    regions: ['neck'],
    targets: { fhp: 0.9, neckPain: 0.5, headache: 0.3 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 2, holdSec: 5, rest: 20 },
    steps: {
      ko: ['무릎을 세우고 바로 누워요.', '뒤통수를 바닥에 붙인 채 턱을 당겨 목 뒤를 길게 만들어요.', '턱을 당긴 상태 그대로 머리를 1~2cm만 살짝 들어 5초 버텨요.', '천천히 내려놓고 목 힘을 풀어요.'],
      en: ['Lie on your back with knees bent.', 'Keep the back of your head on the floor and tuck your chin to lengthen the neck.', 'Keeping the tuck, lift your head just 1–2 cm and hold for 5 seconds.', 'Lower slowly and relax your neck.'],
    },
    cues: { ko: ['턱을 먼저 당기고', '아주 살짝만 들어요', '목 앞이 떨리면 정상이에요'], en: ['Tuck first', 'Lift only a little', 'A slight shake is normal'] },
    mistakes: { ko: ['턱이 들리며 머리만 번쩍 듦', '너무 높이 듦', '어깨까지 들림'], en: ['Chin poking up as you lift', 'Lifting too high', 'Shoulders coming up too'] },
    why: { ko: '턱 당기기의 다음 단계로, 목 앞 깊은 근육의 지구력을 키워 바른 머리 위치를 오래 유지하게 해 줘요.', en: 'The next step after chin tucks: builds deep-neck endurance so you can hold a good head position all day.' },
    muscles: { ko: '심부 목굽힘근 지구력', en: 'Deep neck flexor endurance' },
    caution: { ko: '목에 날카로운 통증이 있으면 턱 당기기(앉아서)로 대신하세요.', en: 'If you feel sharp neck pain, do seated chin tucks instead.' },
    avoid: ['neckSevere'],
    anim: {
      view: 90,
      elev: 10,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [merge(HOOK, { neck: { flex: -4 }, head: { flex: 4 } }), merge(HOOK, { neck: { flex: 26 }, head: { flex: 6 } })],
      durations: [1, 1],
      pauses: [0.8, 2.6],
      zoom: 1.1,
    },
  },
  {
    id: 'upper-trap-stretch',
    name: { ko: '상부 승모근 스트레칭', en: 'Upper trapezius stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['neck', 'shoulder'],
    targets: { neckPain: 0.9, shoulderTilt: 0.8, fhp: 0.4, headache: 0.6, stiffness: 0.5, headTilt: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자에 앉아 오른손으로 의자 옆을 잡아 오른쪽 어깨를 아래로 고정해요.', '왼손을 머리 위로 넘겨 오른쪽 귀 윗부분에 가볍게 얹어요.', '머리를 왼쪽으로 천천히 기울여 오른쪽 목과 어깨 사이가 늘어나게 해요.', '손은 당기지 말고 무게만 얹은 채 30초 길게 호흡해요.'],
      en: ['Sit and hold the side of the chair with your right hand to anchor your right shoulder down.', 'Reach your left hand over your head and rest it above your right ear.', 'Slowly tilt your head to the left until you feel the right side of your neck lengthen.', 'Don’t pull — let the hand’s weight do the work — and breathe slowly for 30 seconds.'],
    },
    cues: { ko: ['어깨는 아래로 툭', '숨을 내쉬며 조금 더', '당기지 말고 무게만'], en: ['Let the shoulder drop', 'Exhale and sink a little deeper', 'No pulling, just weight'] },
    mistakes: { ko: ['늘리는 쪽 어깨가 따라 올라감', '손으로 세게 잡아당김', '몸통이 함께 기울어짐'], en: ['The stretched shoulder rising', 'Yanking with the hand', 'Leaning the whole trunk'] },
    why: { ko: '어깨 위에서 뭉친 상부 승모근을 늘려 목·어깨 결림과 긴장성 두통을 줄여요. 어깨가 올라간 쪽을 한 세트 더 해 주세요.', en: 'Lengthens the tight upper trapezius to ease neck/shoulder tension and headaches. Add an extra set on the higher shoulder.' },
    muscles: { ko: '상부 승모근', en: 'Upper trapezius' },
    anim: {
      view: 0,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { shL: { flex: 30, abd: 150, rot: 20 }, elL: 120, shR: { flex: -4, abd: 12 }, elR: 4 }),
        merge(SIT, { shL: { flex: 30, abd: 150, rot: 20 }, elL: 120, shR: { flex: -4, abd: 12 }, elR: 4, neck: { side: 26 }, head: { side: 10 }, scapR: { elev: -1.5 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.6, 3],
      zoom: 1.2,
    },
    coach: {
      view: 'front',
      metric: 'headTilt',
      mode: 'hold',
      target: 16,
      dir: 1,
      hint: { ko: '정면에서 상체가 보이게 휴대폰을 세워 주세요', en: 'Prop your phone facing you so your upper body is visible' },
      more: { ko: '머리를 조금 더 기울여요', en: 'Tilt a little more' },
      good: { ko: '좋아요, 그대로 호흡', en: 'Good, breathe here' },
    },
  },
  {
    id: 'levator-stretch',
    name: { ko: '견갑거근 스트레칭', en: 'Levator scapulae stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['neck', 'shoulder'],
    targets: { neckPain: 0.8, fhp: 0.4, shoulderTilt: 0.5, stiffness: 0.5, headache: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['오른손으로 의자 옆을 잡아요.', '고개를 왼쪽으로 45° 돌린 뒤, 코를 왼쪽 겨드랑이 쪽으로 숙여요.', '왼손을 뒤통수에 얹어 무게만 더해요.', '오른쪽 목 뒤~날개뼈 윗부분이 당기면 30초 유지해요.'],
      en: ['Hold the side of the chair with your right hand.', 'Turn your head 45° to the left, then bring your nose toward your left armpit.', 'Rest your left hand on the back of your head for a little extra weight.', 'Hold 30 seconds when you feel the back of the right neck and top of the shoulder blade stretch.'],
    },
    cues: { ko: ['코는 겨드랑이 쪽으로', '반대쪽 어깨는 아래로', '편하게 숨 쉬어요'], en: ['Nose toward the armpit', 'Opposite shoulder down', 'Breathe easy'] },
    mistakes: { ko: ['고개만 숙이고 돌리지 않음', '어깨가 올라감'], en: ['Nodding without turning', 'Shoulder hiking up'] },
    why: { ko: '날개뼈를 목으로 끌어올리는 견갑거근은 거북목·스마트폰 자세에서 가장 먼저 뭉쳐요. 담 결린 느낌에 특히 좋아요.', en: 'The levator scapulae, which pulls the shoulder blade up toward the neck, is the first to tighten with phone posture — great for that “knot” feeling.' },
    muscles: { ko: '견갑거근', en: 'Levator scapulae' },
    anim: {
      view: 25,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { shL: { flex: 125, abd: 40, rot: 10 }, elL: 125, shR: { flex: -4, abd: 12 }, elR: 4 }),
        merge(SIT, { shL: { flex: 125, abd: 40, rot: 10 }, elL: 125, shR: { flex: -4, abd: 12 }, elR: 4, neck: { twist: 38, flex: 26, side: 8 }, head: { flex: 14 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.6, 3],
      zoom: 1.2,
    },
  },
  {
    id: 'scm-stretch',
    name: { ko: '목 앞 근육(흉쇄유돌근) 스트레칭', en: 'SCM stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['neck'],
    targets: { fhp: 0.7, headTilt: 0.5, neckPain: 0.4, headache: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 20, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['양손을 겹쳐 오른쪽 쇄골 바로 아래를 살짝 눌러 고정해요.', '고개를 왼쪽으로 기울인 뒤 턱을 천장 쪽으로 살짝 들어요.', '오른쪽 목 앞쪽이 늘어나는 느낌에서 20초 유지해요.'],
      en: ['Cross your hands and gently press just below your right collarbone.', 'Tilt your head to the left, then lift your chin slightly toward the ceiling.', 'Hold 20 seconds when you feel the front-right of your neck stretch.'],
    },
    cues: { ko: ['쇄골은 아래로 고정', '턱은 살짝만 들어요'], en: ['Anchor the collarbone', 'Lift the chin only slightly'] },
    mistakes: { ko: ['고개를 뒤로 과하게 젖힘', '입을 벌리고 턱에 힘줌'], en: ['Throwing the head far back', 'Clenching or opening the jaw'] },
    why: { ko: '머리가 앞으로 나오면 목 앞의 흉쇄유돌근이 짧아져 머리를 계속 앞으로 끌어당겨요. 짧게, 부드럽게 늘려 주세요.', en: 'With forward head posture the SCM shortens and keeps pulling the head forward. Stretch it briefly and gently.' },
    muscles: { ko: '흉쇄유돌근, 사각근', en: 'Sternocleidomastoid, scalenes' },
    caution: { ko: '어지럼증이나 눈앞이 흐려지면 즉시 멈추세요. 목을 뒤로 젖히는 동작이 불편한 분은 생략하세요.', en: 'Stop immediately if you feel dizzy or your vision blurs. Skip it if tilting your head back is uncomfortable.' },
    avoid: ['dizzy', 'neckSevere'],
    anim: {
      view: 15,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { shL: { flex: 22, hab: -38 }, elL: 118, shR: { flex: 20, hab: -26 }, elR: 112 }),
        merge(SIT, { shL: { flex: 22, hab: -38 }, elL: 118, shR: { flex: 20, hab: -26 }, elR: 112, neck: { side: 22, flex: -14 }, head: { flex: -6, twist: 8 } }),
      ],
      durations: [1.5, 1.5],
      pauses: [0.6, 2.6],
      zoom: 1.25,
    },
  },
  {
    id: 'suboccipital-release',
    name: { ko: '뒤통수 아래 풀기', en: 'Suboccipital release' },
    phase: 'release',
    position: 'seated',
    regions: ['neck'],
    targets: { headache: 0.9, fhp: 0.6, neckPain: 0.6, stress: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'time', sets: 1, value: 60 },
    desk: true,
    steps: {
      ko: ['양손 엄지를 뒤통수 아래 움푹 들어간 곳(머리뼈 바로 아래)에 대요.', '작은 원을 그리며 30초간 지그시 문질러요.', '엄지를 댄 채로 턱을 아주 살짝 끄덕이는 동작을 5번 반복해요.', '시원한 정도의 압력만 주세요.'],
      en: ['Place both thumbs in the hollows just below the base of your skull.', 'Massage in small circles for 30 seconds with steady pressure.', 'Keeping the thumbs there, make 5 tiny nods with your chin.', 'Use pressure that feels relieving, not painful.'],
    },
    cues: { ko: ['작게 원을 그려요', '아주 작게 끄덕끄덕', '어깨 힘 빼고'], en: ['Small circles', 'Tiny nods', 'Relax the shoulders'] },
    mistakes: { ko: ['너무 세게 누름', '목을 크게 움직임'], en: ['Pressing too hard', 'Big neck movements'] },
    why: { ko: '화면을 보느라 턱이 들리면 뒤통수 아래 작은 근육(후두하근)이 짧게 뭉쳐 두통과 눈 피로를 만들어요.', en: 'Poking the chin to look at screens shortens the small suboccipital muscles, a common source of headaches and eye strain.' },
    muscles: { ko: '후두하근', en: 'Suboccipitals' },
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      keys: [merge(SIT, HANDS_BEHIND_HEAD, { neck: { flex: -2 } }), merge(SIT, HANDS_BEHIND_HEAD, { neck: { flex: -6 }, head: { flex: 10 } })],
      durations: [0.9, 0.9],
      pauses: [0.3, 0.3],
      zoom: 1.25,
    },
  },
];
