/**
 * 운동 라이브러리 · 목 (추가 동작)
 * 문구·용량·대상 이슈는 물리치료 임상 기준으로 작성되었으며, 전문가가 자유롭게 수정할 수 있습니다.
 * 작성 규칙: docs/CONTENT_GUIDE.md
 */
import { both, type Pose } from '../../figure/rig';
import { PRONE, SIT, WALL, merge } from '../../figure/poses';
import type { Exercise } from '../exercise-types';

// ── 이 파일에서 쓰는 자세 ───────────────────────
/** 바르게 앉아 턱을 살짝 당긴 자세 */
const SIT_TALL: Pose = merge(SIT, { neck: { flex: -3 }, head: { flex: 4 } });
/** 바르게 앉아 턱을 당긴 자세(이중턱) */
const SIT_TUCK: Pose = merge(SIT, { neck: { flex: -8 }, head: { flex: 10 } });
/** 오른손바닥을 오른쪽 귀 위 머리 옆면에 */
const HAND_SIDE_R: Pose = { shR: { flex: -20, abd: 123, rot: 68, hab: -67 }, elR: 131, wrR: -52 };
/** 오른손바닥을 이마에 */
const HAND_FOREHEAD_R: Pose = { shR: { flex: 130, abd: -26, rot: -76, hab: 1 }, elR: 101, wrR: -6 };
/** 엎드린 자세: 가슴 두께만큼 상체가 살짝 높음, 팔은 몸 옆 */
const PRONE_TOWEL: Pose = merge(PRONE, { root: { pitch: 86 } }, both({ sh: { abd: 10, flex: -4 }, el: 6 }));

export const NECK_PLUS: Exercise[] = [
  {
    id: 'neck-rotation-mobility',
    name: { ko: '목 좌우 돌리기', en: 'Neck rotation' },
    phase: 'mobility',
    position: 'seated',
    regions: ['neck'],
    targets: { neckPain: 0.8, stiffness: 0.8, fhp: 0.3, headache: 0.3, stress: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 1, value: 8, tempo: 8, holdSec: 2, rest: 15 },
    desk: true,
    setup: {
      ko: [
        '의자 앞쪽 1/3에 앉아 두 발을 골반 너비로 벌리고, 무릎은 90도로 둬요.',
        '골반을 세워 정수리를 천장 쪽으로 길게 뻗고, 어깨는 한 번 으쓱했다가 툭 떨어뜨려요.',
        '턱을 1cm쯤 살짝 당겨 뒷목을 길게 하고, 시선은 정면 눈높이에 둬요. 두 손은 허벅지 위에 편하게 얹어요.',
      ],
      en: [
        'Sit on the front third of the chair, feet hip-width apart, knees at 90°.',
        'Stack your pelvis upright and reach the crown of your head toward the ceiling; shrug once and let your shoulders drop.',
        'Draw your chin back about 1 cm to lengthen the back of your neck, eyes level. Rest both hands on your thighs.',
      ],
    },
    steps: {
      ko: [
        '코끝으로 수평선을 그리듯, 2초에 걸쳐 고개를 오른쪽으로 천천히 돌려요. 시선이 먼저 가고 머리가 따라가요.',
        '당김이 살짝 느껴지는 편안한 끝(보통 턱이 어깨 가까이 오는 지점)에서 멈추고 2초 머물러요.',
        '3초쯤에 걸쳐 정면을 지나 왼쪽 끝까지 돌리고, 끝에서 2초 머물러요.',
        '정면으로 돌아오면 1회예요. 8회 반복해요.',
        '매 회 어깨와 가슴은 정면을 본 채, 목만 돌아가게 해요.',
      ],
      en: [
        'As if drawing a level line with your nose, take 2 seconds to turn your head slowly to the right. Let your eyes lead and your head follow.',
        'Stop at a comfortable end where you feel a light pull (usually with your chin near your shoulder) and pause for 2 seconds.',
        'Take about 3 seconds to turn back through the centre to your left end range, and pause 2 seconds there.',
        'Coming back to centre counts as 1 rep. Do 8.',
        'Keep your shoulders and chest facing forward the whole time — only your neck turns.',
      ],
    },
    breathing: { ko: '한쪽 끝으로 돌아갈 때마다 입으로 “후—” 길게 내쉬고, 정면을 지날 때 코로 들이마셔요. 끝에서 머무는 동안에도 숨을 참지 마세요.', en: 'Breathe out slowly through your mouth each time you turn toward an end, and breathe in through your nose as you pass the centre. Keep breathing during the pauses.' },
    feel: { ko: '돌리는 방향의 반대쪽 목 옆과 뒤가 부드럽게 늘어나고, 움직임이 매 회 조금씩 매끄러워지면 정답이에요. 어지럽거나, 눈앞이 흐려지거나, 팔이 저리면 바로 멈추세요.', en: 'A gentle stretch along the side and back of the neck opposite the turn, with the movement getting a little smoother each rep. Stop right away if you feel dizzy, your vision blurs or your arms tingle.' },
    easier: { ko: '돌리는 범위를 절반(정면에서 45도쯤)으로 줄이고, 등받이에 등을 기대 몸통을 고정해 보세요. 한쪽이 더 뻣뻣하면 그쪽은 아프기 전까지만 가요.', en: 'Halve the range (about 45° from centre) and lean against the backrest to keep your trunk still. If one side is stiffer, stop that side before it hurts.' },
    harder: { ko: '끝에서 머무는 시간을 5초로 늘리거나, ‘턱 당긴 채 좌우 보기’로 턱 당김을 유지하며 돌리는 연습을 해 보세요.', en: 'Stretch the end-range pause to 5 seconds, or move on to the chin-tuck rotation to turn while holding a tuck.' },
    cues: { ko: ['코끝으로 수평선 그리기', '어깨는 정면 그대로', '끝에서 2초 머물러요', '천천히 돌아와요'], en: ['Draw a level line with your nose', 'Shoulders face forward', 'Pause for two', 'Come back slowly'] },
    mistakes: {
      ko: [
        '어깨와 몸통이 같이 돌아감 → 손을 허벅지에 얹고 가슴은 정면에 둔 채 목만 돌려요.',
        '돌리면서 턱이 들리거나 고개가 기울어짐 → 코끝이 눈높이의 수평선을 따라가게 해요.',
        '끝에서 반동을 주거나 빠르게 돌림 → 2초에 걸쳐 천천히 돌리고, 끝에서는 멈춰서 머물러요.',
        '아픈 끝까지 억지로 밀어붙임 → 당김이 살짝 느껴지는 곳에서 멈춰요. 범위는 매일 조금씩 늘어나요.',
      ],
      en: [
        'Shoulders and trunk turning too → Rest your hands on your thighs, keep your chest facing forward and turn only your neck.',
        'Chin lifting or head tilting as you turn → Let your nose travel along a level line at eye height.',
        'Bouncing or whipping at the end → Take 2 seconds to turn and pause, still, at the end.',
        'Forcing into pain → Stop where you feel a light pull; your range improves a little each day.',
      ],
    },
    why: { ko: '오래 화면을 보면 목이 한 자세로 굳어 돌아가는 범위가 줄어들어요. 끝 범위까지 천천히 움직여 주면 목 관절과 근육이 부드러워져 뻐근함이 줄어요.', en: 'Hours at a screen freeze the neck in one position and shrink how far it turns. Slow, end-range turns keep the neck joints and muscles supple and ease stiffness.' },
    muscles: { ko: '흉쇄유돌근, 판상근(두판상근·경판상근), 후두하근, 상부 승모근', en: 'Sternocleidomastoid, splenius capitis/cervicis, suboccipitals, upper trapezius' },
    caution: { ko: '어지럼, 눈앞 흐려짐, 메스꺼움, 팔 저림이 생기면 즉시 멈추세요. 최근 목을 다쳤다면 먼저 전문가와 상의하세요.', en: 'Stop immediately if you feel dizzy, your vision blurs, you feel sick or your arms tingle. If you recently injured your neck, check with a professional first.' },
    avoid: ['dizzy'],
    anim: {
      view: 0,
      elev: 10,
      props: [{ kind: 'chair' }],
      keys: [
        SIT_TALL,
        merge(SIT_TALL, { neck: { flex: -3, twist: -48 }, head: { flex: 4, twist: -24 } }),
        merge(SIT_TALL, { neck: { flex: -3, twist: 48 }, head: { flex: 4, twist: 24 } }),
      ],
      labels: [
        { ko: '턱 살짝 당기고 정면', en: 'Chin in, face forward' },
        { ko: '오른쪽 끝에서 2초', en: 'Turn right, pause 2 s' },
        { ko: '왼쪽 끝에서 2초', en: 'Turn left, pause 2 s' },
      ],
      durations: [1.5, 3, 1.5],
      pauses: [0.4, 1.8, 1.8],
      focus: [
        { a: 'neckTop', b: 'shL', kind: 'stretch', r: 1.6, from: 0.2, to: 0.55 },
        { a: 'neckTop', b: 'shR', kind: 'stretch', r: 1.6, from: 0.2, to: 0.55 },
      ],
      trace: ['nose'],
      zoom: 1.1,
    },
  },
  {
    id: 'chin-tuck-rotation',
    name: { ko: '턱 당긴 채 좌우 보기', en: 'Chin-tuck rotation' },
    phase: 'activate',
    position: 'seated',
    regions: ['neck'],
    targets: { fhp: 0.8, neckPain: 0.6, stiffness: 0.4, headache: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 6, tempo: 8, holdSec: 2, rest: 15 },
    desk: true,
    setup: {
      ko: [
        '의자 앞쪽 1/3에 앉아 두 발을 골반 너비로 벌리고, 무릎은 90도로 둬요.',
        '골반을 세워 허리를 곧게 펴고, 어깨는 으쓱했다가 툭 떨어뜨려요. 두 손은 허벅지 위에 둬요.',
        '시선은 정면 눈높이의 한 점에 두고, 턱 밑이 바닥과 평행하게 해요.',
      ],
      en: [
        'Sit on the front third of the chair, feet hip-width apart, knees at 90°.',
        'Stack your pelvis upright so your low back is tall; shrug once and let your shoulders drop. Hands rest on your thighs.',
        'Fix your eyes on a point at eye level so the underside of your chin is parallel to the floor.',
      ],
    },
    steps: {
      ko: [
        '시선은 그대로 둔 채 머리를 수평으로 1~2cm 뒤로 밀어 턱을 당겨요(이중턱).',
        '힘을 절반쯤으로 풀어, 편하게 계속 유지할 수 있는 정도로만 턱을 당겨 둬요.',
        '턱을 당긴 채 2초에 걸쳐 고개를 오른쪽으로 45도(코가 어깨 중간을 향할 때까지) 돌리고 2초 머물러요.',
        '정면을 지나 왼쪽으로 같은 방법으로 돌리고 2초 머물러요.',
        '정면으로 돌아와 턱을 풀면 1회예요. 6회 반복해요.',
      ],
      en: [
        'Keeping your eyes level, glide your head straight back 1–2 cm to tuck your chin (double chin).',
        'Ease off to about half effort — a tuck you could hold comfortably for a while.',
        'Holding the tuck, take 2 seconds to turn your head 45° to the right (nose toward the middle of your shoulder) and pause 2 seconds.',
        'Turn back through the centre to the left the same way and pause 2 seconds.',
        'Return to centre and relax the tuck — that’s 1 rep. Do 6.',
      ],
    },
    breathing: { ko: '턱을 당기며 입으로 내쉬고, 좌우로 돌리는 동안에는 코로 편하게 숨 쉬어요. 턱 당김을 지키려고 숨을 참지 마세요.', en: 'Exhale as you tuck, then breathe easily through your nose while you turn. Don’t hold your breath to keep the tuck.' },
    feel: { ko: '목 앞쪽 깊은 곳이 은은하게 계속 조이고, 돌리는 동안 뒷목이 길게 유지되면 정답이에요. 돌리다 턱이 앞으로 빠지는 지점이 지금의 한계예요. 목 앞 굵은 근육이 튀어나오거나 어지러우면 멈추세요.', en: 'A steady, gentle tightening deep in the front of your neck and a long back of the neck while you turn. The point where your chin starts to poke forward is your current limit. Stop if the big front neck cords pop out or you feel dizzy.' },
    easier: { ko: '돌리는 범위를 20~30도로 줄이거나, 벽에 뒤통수를 댄 채 벽을 따라 굴리듯 돌려 보세요. ‘턱 당기기’만 먼저 익혀도 좋아요.', en: 'Turn only 20–30°, or stand with the back of your head on a wall and roll it along the wall as you turn. Practising plain chin tucks first is fine too.' },
    harder: { ko: '끝에서 머무는 시간을 5초로 늘리고, 익숙해지면 ‘누워서 턱 당겨 머리 들기’로 넘어가세요.', en: 'Pause 5 seconds at each end; once that’s easy, progress to the supine chin-tuck head lift.' },
    cues: { ko: ['턱 당긴 채 그대로', '코가 어깨 중간까지', '턱이 빠지지 않게', '천천히 정면으로'], en: ['Keep the tuck', 'Nose to mid-shoulder', 'Don’t let the chin poke', 'Slowly back to centre'] },
    mistakes: {
      ko: [
        '돌리는 순간 턱이 앞으로 빠짐 → 범위를 줄이고, 턱 당김이 유지되는 곳까지만 돌려요.',
        '턱을 너무 세게 당겨 목 앞이 불룩해짐 → 힘을 절반으로 줄여 편하게 유지할 수 있을 만큼만 당겨요.',
        '돌리면서 고개가 옆으로 기울어짐 → 두 눈을 수평으로 두고 코끝이 수평선을 따라가게 해요.',
        '어깨가 따라 돌거나 올라감 → 손을 허벅지에 얹고 어깨를 툭 떨어뜨린 채 목만 돌려요.',
      ],
      en: [
        'Chin poking forward as you turn → Shrink the range and only turn as far as you can keep the tuck.',
        'Tucking so hard the front of the neck bulges → Use about half effort, just enough to hold comfortably.',
        'Head tilting sideways during the turn → Keep both eyes level and let your nose trace a level line.',
        'Shoulders turning or rising with you → Rest your hands on your thighs, drop your shoulders and turn only the neck.',
      ],
    },
    why: { ko: '거북목은 가만히 있을 때보다 고개를 돌리는 순간 턱이 앞으로 빠지기 쉬워요. 턱 당김을 유지하며 돌리는 연습은 심부 목굽힘근이 움직이는 중에도 머리 위치를 지키도록 길러 줘요.', en: 'With tech neck the chin tends to poke forward the moment you turn your head. Turning with a held tuck trains the deep neck flexors to control head position while you move, not only when you’re still.' },
    muscles: { ko: '심부 목굽힘근(두장근·경장근), 후두하근, 판상근', en: 'Deep neck flexors (longus capitis/colli), suboccipitals, splenius' },
    caution: { ko: '어지럽거나 팔이 저리면 바로 멈추세요.', en: 'Stop if you feel dizzy or your arms tingle.' },
    avoid: ['dizzy'],
    anim: {
      view: 25,
      elev: 14,
      props: [{ kind: 'chair' }],
      keys: [
        merge(SIT, { neck: { flex: 10 }, head: { flex: -8 } }),
        SIT_TUCK,
        merge(SIT_TUCK, { neck: { twist: -32 }, head: { twist: -13 } }),
        merge(SIT_TUCK, { neck: { twist: 32 }, head: { twist: 13 } }),
      ],
      labels: [
        { ko: '바르게 앉기', en: 'Sit tall' },
        { ko: '턱 당기기', en: 'Tuck the chin' },
        { ko: '당긴 채 오른쪽 2초', en: 'Keep it, look right 2 s' },
        { ko: '당긴 채 왼쪽 2초', en: 'Keep it, look left 2 s' },
      ],
      durations: [0.8, 1.6, 2.4, 1.2],
      pauses: [0.3, 0.3, 1.7, 1.7],
      holdKey: 2,
      focus: [{ a: 'chest', b: 'neckTop', side: 'front', kind: 'work', r: 2.2 }],
      trace: ['nose'],
      zoom: 1.25,
    },
  },
  {
    id: 'neck-isometric-side',
    name: { ko: '목 옆으로 버티기(손 등척성)', en: 'Side neck isometric' },
    phase: 'activate',
    position: 'seated',
    regions: ['neck'],
    targets: { neckPain: 0.8, headTilt: 0.4, fhp: 0.3, stiffness: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 5, tempo: 2, holdSec: 5, perSide: true, rest: 10 },
    desk: true,
    setup: {
      ko: [
        '의자 앞쪽 1/3에 앉아 두 발을 골반 너비로 벌리고, 무릎은 90도로 둬요. 골반을 세워 허리를 곧게 펴요.',
        '턱을 살짝 당겨 뒷목을 길게 하고, 시선은 정면 눈높이에 둬요.',
        '오른손 손바닥을 오른쪽 귀 바로 위, 머리 옆면에 대요. 팔꿈치는 옆으로 편하게 벌려요.',
      ],
      en: [
        'Sit on the front third of the chair, feet hip-width apart, knees at 90°, pelvis upright and low back tall.',
        'Tuck your chin slightly to lengthen the back of your neck, eyes level.',
        'Place your right palm on the side of your head just above your right ear, elbow relaxed out to the side.',
      ],
    },
    steps: {
      ko: [
        '머리를 오른쪽으로 기울이려는 듯 손바닥 쪽으로 밀어요. 손은 같은 힘으로 버텨 머리가 움직이지 않게 해요.',
        '힘은 최대의 30% 정도(손바닥이 살짝 눌리는 정도)로, 2초에 걸쳐 서서히 올려요.',
        '그 힘을 5초 유지해요. 머리·시선·어깨 높이는 그대로예요.',
        '2초에 걸쳐 천천히 힘을 풀고 잠깐 쉬어요.',
        '5회 반복한 뒤 왼손을 왼쪽 머리에 대고 같은 방법으로 해요.',
      ],
      en: [
        'Press your head into your palm as if tilting it to the right, while your hand pushes back just as hard so nothing moves.',
        'Use about 30% of your maximum effort (a light press into the palm), building up over 2 seconds.',
        'Hold that effort for 5 seconds; your head, gaze and shoulder height stay the same.',
        'Release slowly over 2 seconds and rest briefly.',
        'Repeat 5 times, then place your left hand on the left side of your head and do the same.',
      ],
    },
    breathing: { ko: '힘을 주는 5초 동안 입으로 가늘게 “스—” 내쉬거나 코로 편하게 숨 쉬어요. 숨을 참으면 목에 힘이 과하게 들어가요.', en: 'During the 5-second press, breathe out slowly through pursed lips or breathe easily through your nose. Holding your breath makes the neck over-tense.' },
    feel: { ko: '미는 쪽 목 옆면이 은은하게 단단해지면 정답이에요. 머리가 흔들리거나 얼굴이 빨개질 만큼 세면 힘을 줄이고, 통증·저림·어지럼이 생기면 멈추세요.', en: 'A gentle firmness along the side of the neck you’re pressing with. If your head wobbles or your face flushes, ease off; stop if you feel pain, tingling or dizziness.' },
    easier: { ko: '힘을 10~20%로 줄이고 3초만 버텨요. 팔을 올리기 불편하면 손 대신 머리 옆면을 벽에 대고 살짝 눌러도 돼요.', en: 'Drop to 10–20% effort and hold only 3 seconds. If lifting your arm is uncomfortable, lean the side of your head lightly into a wall instead.' },
    harder: { ko: '버티는 시간을 10초로 늘리고, 같은 방법으로 이마(앞)·뒤통수(뒤)까지 네 방향을 모두 해 보세요. 힘은 50%를 넘기지 않아요.', en: 'Build the hold to 10 seconds and work all four directions the same way — both sides, forehead and back of the head — staying at or below 50% effort.' },
    cues: { ko: ['손과 머리가 팽팽하게', '30%만 밀어요', '머리는 제자리', '숨 참지 마세요'], en: ['Head and hand in balance', 'Only 30% effort', 'Head stays still', 'Keep breathing'] },
    mistakes: {
      ko: [
        '머리가 손을 밀고 옆으로 기울어짐 → 손이 같은 힘으로 버티게 해 머리 위치가 전혀 변하지 않게 해요.',
        '힘을 너무 세게 줌 → 최대의 30% 정도, 손바닥이 살짝 눌리는 느낌이면 충분해요.',
        '미는 쪽 어깨가 으쓱 올라감 → 어깨를 툭 떨어뜨리고 목 옆에만 힘이 들어가게 해요.',
        '숨을 참음 → 버티는 동안 가늘게 내쉬거나 코로 편하게 숨 쉬어요.',
      ],
      en: [
        'Head pushing the hand and tilting → Let the hand match the effort so your head doesn’t move at all.',
        'Pushing too hard → About 30% of maximum — a light press into the palm — is enough.',
        'Shrugging the working shoulder → Drop the shoulder so only the side of the neck works.',
        'Holding your breath → Breathe out slowly or breathe easily through your nose while you hold.',
      ],
    },
    why: { ko: '관절을 움직이지 않고 근육에만 힘을 넣는 등척성 운동이라 목이 뻐근하거나 예민할 때도 부담이 적어요. 목을 옆에서 받쳐 주는 근육의 지구력을 길러 머리를 반듯하게 세우기 쉬워져요.', en: 'An isometric — the muscles work while the joint stays still — so it’s gentle even on a stiff, sensitive neck. It builds endurance in the muscles that brace the neck from the side, making it easier to hold your head level.' },
    muscles: { ko: '목 옆 근육(사각근·흉쇄유돌근), 상부 승모근, 견갑거근', en: 'Lateral neck muscles (scalenes, sternocleidomastoid), upper trapezius, levator scapulae' },
    caution: { ko: '누르는 동안 팔이나 손이 저리거나, 두통·어지럼이 생기면 바로 멈추세요.', en: 'Stop straight away if your arm or hand tingles, or you get a headache or feel dizzy while pressing.' },
    avoid: ['neckSevere', 'shoulderSevere'],
    anim: {
      view: 0,
      props: [{ kind: 'chair' }],
      // 등척성: 머리는 움직이지 않아요 — 준비(힘 뺌)와 밀기(30%)는 같은 자세, 자막과 근육 강조로 구분
      keys: [merge(SIT_TALL, HAND_SIDE_R), merge(SIT_TALL, HAND_SIDE_R)],
      labels: [
        { ko: '손바닥을 귀 위에', en: 'Palm above the ear' },
        { ko: '30%로 밀어 5초', en: 'Press 30%, hold 5 s' },
      ],
      durations: [1, 1],
      pauses: [1.2, 3.8],
      focus: [
        { a: 'neckTop', b: 'shR', kind: 'work', r: 2, from: 0.12, to: 0.6 },
      ],
      zoom: 1.2,
    },
  },
  {
    id: 'neck-isometric-front',
    name: { ko: '이마 누르기 버티기', en: 'Forehead press isometric' },
    phase: 'activate',
    position: 'seated',
    regions: ['neck'],
    targets: { fhp: 0.7, neckPain: 0.8, headache: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 2, holdSec: 5, rest: 15 },
    desk: true,
    setup: {
      ko: [
        '의자 앞쪽 1/3에 앉아 두 발을 골반 너비로 벌리고, 무릎은 90도로 둬요. 골반을 세워 허리를 곧게 펴요.',
        '어깨를 으쓱했다가 툭 떨어뜨리고, 시선은 정면 눈높이에 둬요.',
        '편한 손의 손바닥을 이마 가운데(눈썹과 머리카락 선 사이)에 대고, 손가락은 반대쪽 관자놀이를 향하게 해요. 팔꿈치는 앞쪽 옆으로 편하게 둬요.',
      ],
      en: [
        'Sit on the front third of the chair, feet hip-width apart, knees at 90°, pelvis upright and low back tall.',
        'Shrug once and let your shoulders drop; eyes level.',
        'Lay the palm of whichever hand is comfortable across the middle of your forehead (between brows and hairline), fingers toward the opposite temple, elbow relaxed forward and slightly out.',
      ],
    },
    steps: {
      ko: [
        '먼저 턱을 1cm쯤 살짝 당겨 뒷목을 길게 해요.',
        '이마로 손바닥을 앞으로 밀되, 손이 같은 힘으로 버텨 머리가 움직이지 않게 해요.',
        '힘은 최대의 30% 정도로, 2초에 걸쳐 서서히 올려요.',
        '턱을 당긴 채 그 힘을 5초 유지해요.',
        '2초에 걸쳐 천천히 풀어요. 8회 반복해요.',
      ],
      en: [
        'First tuck your chin about 1 cm to lengthen the back of your neck.',
        'Press your forehead forward into your palm while the hand pushes back equally, so your head doesn’t move.',
        'Use about 30% of your maximum effort, building up over 2 seconds.',
        'Keep the chin tucked and hold that effort for 5 seconds.',
        'Release slowly over 2 seconds. Repeat 8 times.',
      ],
    },
    breathing: { ko: '힘을 주는 5초 동안 입으로 가늘게 “스—” 내쉬거나 코로 편하게 숨 쉬어요. 숨을 참으면 목과 얼굴에 힘이 과하게 들어가요.', en: 'During the 5-second press, breathe out slowly through pursed lips or breathe easily through your nose. Holding your breath over-tenses the neck and face.' },
    feel: { ko: '목 앞쪽 깊은 곳과 턱 아래가 은은하게 단단해지면 정답이에요. 턱이 들리거나 목 앞 굵은 근육이 불룩 솟으면 너무 센 거예요. 통증·저림·어지럼이 생기면 멈추세요.', en: 'A gentle firmness deep in the front of your neck and under your chin. If your chin lifts or the big cords at the front of your neck bulge, you’re pressing too hard. Stop if you feel pain, tingling or dizziness.' },
    easier: { ko: '힘을 10~20%로 줄이고 3초만 버텨요. 그래도 불편하면 ‘턱 당기기’나 ‘벽에 기대 턱 당기기’만 해도 좋아요.', en: 'Drop to 10–20% effort and hold only 3 seconds. If it still bothers you, plain or wall chin tucks are fine.' },
    harder: { ko: '버티는 시간을 10초로 늘리거나, ‘누워서 턱 당겨 머리 들기’로 넘어가세요. 힘은 50%를 넘기지 않아요.', en: 'Build the hold to 10 seconds, or progress to the supine chin-tuck head lift. Stay at or below 50% effort.' },
    cues: { ko: ['턱 먼저 살짝 당기고', '이마로 30%만 밀어요', '머리는 제자리', '숨은 편하게'], en: ['Tuck the chin first', 'Press only 30%', 'Head stays still', 'Breathe easy'] },
    mistakes: {
      ko: [
        '미는 순간 턱이 들림 → 턱을 먼저 당긴 뒤, 이마 가운데로 손을 밀어요.',
        '머리가 손을 밀고 앞으로 숙여짐 → 손이 같은 힘으로 버티게 해 머리 위치를 그대로 지켜요.',
        '힘을 너무 세게 줘 목 앞이 불룩해짐 → 30% 정도, 손바닥이 살짝 눌리는 정도면 충분해요.',
        '어깨가 올라가고 등이 구부정해짐 → 어깨를 툭 떨어뜨리고 골반을 세워 앉은 채 해요.',
      ],
      en: [
        'Chin lifting as you press → Tuck the chin first, then press through the middle of your forehead.',
        'Head pushing the hand and nodding forward → Let the hand match the effort so your head stays put.',
        'Pressing so hard the front of the neck bulges → About 30% — a light press into the palm — is enough.',
        'Shoulders rising and back slumping → Drop your shoulders and sit up on your sit bones.',
      ],
    },
    why: { ko: '머리를 움직이지 않고 목 앞 근육에만 힘을 넣는 등척성 운동이라 목이 예민할 때도 부담이 적어요. 턱을 당긴 채 버티면 거북목에서 약해진 심부 목굽힘근을 깨우는 데 좋아요.', en: 'An isometric that works the front of the neck without moving it, so it’s gentle on a sensitive neck. Holding a chin tuck while you press helps wake up the deep neck flexors that weaken with tech neck.' },
    muscles: { ko: '심부 목굽힘근(두장근·경장근), 흉쇄유돌근', en: 'Deep neck flexors (longus capitis/colli), sternocleidomastoid' },
    caution: { ko: '어지럽거나 두통·팔 저림이 생기면 바로 멈추세요. 한쪽 어깨가 불편하면 반대 손을 써요.', en: 'Stop straight away if you feel dizzy or get a headache or tingling arms. If one shoulder is sore, use the other hand.' },
    avoid: ['neckSevere'],
    anim: {
      view: -45,
      props: [{ kind: 'chair' }],
      // 등척성: 준비(힘 뺌)와 밀기(30%)는 같은 자세, 자막과 근육 강조로 구분
      keys: [merge(SIT_TUCK, HAND_FOREHEAD_R), merge(SIT_TUCK, HAND_FOREHEAD_R)],
      labels: [
        { ko: '턱 당기고 이마에 손', en: 'Tuck, palm on forehead' },
        { ko: '이마로 30% 밀어 5초', en: 'Press 30%, hold 5 s' },
      ],
      durations: [1, 1],
      pauses: [1.2, 3.8],
      focus: [{ a: 'chest', b: 'neckTop', side: 'front', kind: 'work', r: 2.2 }],
      zoom: 1.25,
    },
  },
  {
    id: 'wall-chin-tuck',
    name: { ko: '벽에 기대 턱 당기기', en: 'Wall chin tuck' },
    phase: 'activate',
    position: 'wall',
    regions: ['neck'],
    targets: { fhp: 0.9, neckPain: 0.6, headache: 0.4 },
    equipment: ['wall'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 2, holdSec: 5, rest: 15 },
    desk: true,
    setup: {
      ko: [
        '벽을 등지고 서서 발뒤꿈치를 벽에서 5~10cm(손가락 3~4개 너비) 떼고, 두 발은 골반 너비로 벌려요.',
        '엉덩이와 두 날개뼈를 벽에 붙이고, 무릎은 살짝 풀어 뒤로 잠그지 않아요.',
        '허리 뒤에는 손바닥 하나 들어갈 공간만 남기고, 시선은 정면 눈높이에 둬요. 지금은 뒤통수가 벽에서 떨어져 있어도 괜찮아요.',
      ],
      en: [
        'Stand with your back to a wall, heels 5–10 cm (3–4 finger-widths) away from it, feet hip-width apart.',
        'Rest your buttocks and both shoulder blades on the wall; keep your knees soft, not locked back.',
        'Leave just a palm’s space behind your low back and look straight ahead. It’s fine if your head doesn’t touch the wall yet.',
      ],
    },
    steps: {
      ko: [
        '시선을 정면에 둔 채 머리를 수평으로 천천히 뒤로 밀어 턱을 당겨요(이중턱).',
        '뒤통수가 벽에 닿으면 벽을 아주 살짝(10~20% 힘) 눌러요.',
        '정수리를 천장 쪽으로 길게 뻗은 채 5초 버텨요.',
        '2초에 걸쳐 힘을 풀고 머리를 처음 자리로 돌려요.',
        '10회 반복해요. 매 회 턱이 들리지 않게, 뒤통수가 벽을 타고 살짝 위로 미끄러지는 느낌으로 해요.',
      ],
      en: [
        'Keeping your eyes level, slowly glide your head straight back, tucking your chin (double chin).',
        'When the back of your head reaches the wall, press into it very lightly (10–20% effort).',
        'Reach the crown of your head toward the ceiling and hold for 5 seconds.',
        'Take 2 seconds to relax and let your head return to the start.',
        'Repeat 10 times. Keep the chin from lifting — feel the back of your head slide slightly up the wall.',
      ],
    },
    breathing: { ko: '머리를 뒤로 밀면서 입으로 “후—” 내쉬고, 버티는 5초 동안은 코로 편하게 숨 쉬어요.', en: 'Exhale through your mouth as you glide back, then breathe easily through your nose during the 5-second hold.' },
    feel: { ko: '목 앞쪽 깊은 곳이 은은하게 조이고 뒷목이 위로 길어지는 느낌이면 정답이에요. 벽을 세게 눌러 목 앞 굵은 근육이 튀어나오면 힘을 줄이세요. 어지럽거나 팔이 저리면 멈추세요.', en: 'A gentle tightening deep in the front of your neck and a long, lifted back of the neck. If pressing makes the big front neck cords pop out, ease off. Stop if you feel dizzy or your arms tingle.' },
    easier: { ko: '뒤통수가 벽에 닿지 않으면 고개를 젖혀 억지로 닿게 하지 말고, 접은 수건을 뒤통수 뒤에 대고 그 수건을 살짝 눌러요. 누워서 뒤통수로 베개를 지그시 누르는 방법도 좋아요.', en: 'If your head doesn’t reach the wall, don’t tip it back to force contact — hold a folded towel behind your head and press into that. Lying down and gently pressing the back of your head into a pillow also works.' },
    harder: { ko: '버티는 시간을 10초로 늘리거나, 벽 없이 앉아서 하는 ‘턱 당기기’로 넘어가세요.', en: 'Build the hold to 10 seconds, or move on to seated chin tucks without the wall.' },
    cues: { ko: ['시선은 정면 그대로', '뒤통수로 벽을 살짝', '정수리는 위로 길게', '5초 버텨요'], en: ['Eyes stay level', 'Head back to the wall', 'Crown reaches up', 'Hold for five'] },
    mistakes: {
      ko: [
        '턱을 들어 뒤통수를 벽에 붙임 → 고개를 젖히지 말고, 턱을 당겨 머리 전체를 수평으로 뒤로 밀어요.',
        '벽을 세게 밀어 목 앞이 불룩해짐 → 벽에 닿기만 하거나 10~20% 힘으로 살짝만 눌러요.',
        '허리가 벽에서 크게 뜸 → 배꼽을 살짝 당겨 허리 뒤 공간을 손바닥 하나 정도로 유지해요.',
        '고개를 아래로 끄덕임 → 시선을 정면 눈높이에 고정하고 수평으로 밀어요.',
      ],
      en: [
        'Lifting the chin to get your head onto the wall → Don’t tip your head back; tuck the chin and glide the whole head straight back.',
        'Pushing hard so the front of the neck bulges → Just touch the wall, or press at 10–20% effort.',
        'Low back arching far off the wall → Draw your navel in slightly and keep a palm’s space behind your low back.',
        'Nodding the head down → Fix your gaze at eye level and glide straight back.',
      ],
    },
    why: { ko: '벽이 기준점이 되어 머리를 어느 방향으로 얼마나 움직일지 알기 쉬운, 가장 쉬운 턱 당기기예요. 심부 목굽힘근을 깨우며 앞으로 나온 머리를 어깨 위로 되돌리는 감각을 익혀요.', en: 'The easiest chin tuck: the wall gives you a clear target for which way and how far to move. It wakes the deep neck flexors and teaches the feel of bringing your head back over your shoulders.' },
    muscles: { ko: '심부 목굽힘근(두장근·경장근)', en: 'Deep neck flexors (longus capitis/colli)' },
    caution: { ko: '어지럽거나 팔이 저리면 바로 멈추세요.', en: 'Stop if you feel dizzy or your arms tingle.' },
    anim: {
      view: 90,
      props: [{ kind: 'wall', wall: 'back', dist: 0 }],
      keys: [merge(WALL, { neck: { flex: 18 }, head: { flex: -15 } }), merge(WALL, { neck: { flex: -8 }, head: { flex: 9 } })],
      labels: [
        { ko: '벽에 등 대고 서기', en: 'Back against the wall' },
        { ko: '뒤통수로 벽 눌러 5초', en: 'Head to wall, hold 5 s' },
      ],
      durations: [1.1, 1.1],
      pauses: [0.6, 4.2],
      focus: [
        { a: 'chest', b: 'neckTop', side: 'front', kind: 'work', r: 2.2 },
        { a: 'neckTop', b: 'head', side: 'back', kind: 'stretch', r: 2, from: 0, to: 0.7 },
      ],
      trace: ['nose'],
      zoom: 1.1,
    },
  },
  {
    id: 'prone-chin-tuck-lift',
    name: { ko: '엎드려 턱 당기고 머리 들기', en: 'Prone chin-tuck head lift' },
    phase: 'activate',
    position: 'prone',
    regions: ['neck', 'upperBack'],
    targets: { fhp: 0.9, neckPain: 0.5, kyphosis: 0.3, headache: 0.3 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 2, holdSec: 5, rest: 20 },
    setup: {
      ko: [
        '매트에 엎드려 이마 밑에 접은 수건(두께 2~3cm)을 받쳐요. 코가 바닥에 눌리지 않을 높이면 돼요.',
        '팔은 몸 옆에 편하게 두고 손바닥은 바닥을 향해요. 다리는 골반 너비로 쭉 뻗어요.',
        '어깨를 귀에서 멀리 내리고, 날개뼈를 살짝 뒤·아래로 모아요.',
      ],
      en: [
        'Lie face down on a mat with a folded towel (2–3 cm thick) under your forehead — just high enough that your nose isn’t squashed.',
        'Rest your arms by your sides, palms down, and stretch your legs out hip-width apart.',
        'Draw your shoulders away from your ears and set your shoulder blades gently back and down.',
      ],
    },
    steps: {
      ko: [
        '이마를 수건에 댄 채 턱을 목 쪽으로 살짝 당겨요(바닥을 향해 작게 끄덕이는 느낌).',
        '턱 당김을 유지하며 머리를 수건에서 1~2cm만 들어요. 시선은 수건(바닥)을 봐요.',
        '뒷목이 길고 머리와 등이 일직선인 상태로 5초 버텨요.',
        '2초에 걸쳐 천천히 이마를 수건에 내려놓고 목 힘을 풀어요.',
        '8회 반복해요. 매 회 턱부터 당긴 뒤 들어요.',
      ],
      en: [
        'With your forehead on the towel, draw your chin gently toward your throat (a small nod toward the floor).',
        'Keeping the tuck, lift your head just 1–2 cm off the towel, eyes on the floor.',
        'Hold 5 seconds with the back of your neck long and your head in line with your back.',
        'Take 2 seconds to lower your forehead to the towel and relax your neck.',
        'Repeat 8 times, tucking the chin first every time.',
      ],
    },
    breathing: { ko: '머리를 들며 입으로 “후—” 내쉬고, 버티는 5초 동안 코로 편하게 숨 쉬어요. 내려놓으며 들이마셔요.', en: 'Exhale through your mouth as you lift, breathe easily through your nose during the 5-second hold, and inhale as you lower.' },
    feel: { ko: '뒷목과 날개뼈 사이가 은은하게 단단해지고, 목 앞 깊은 곳도 살짝 조이면 정답이에요. 뒷목이 접히거나 뒤통수 아래가 조이면 턱이 들린 거예요. 팔 저림이나 어지럼이 생기면 멈추세요.', en: 'A gentle firmness at the back of your neck and between your shoulder blades, plus a light tightening deep in the front of the neck. If the back of your neck creases or the base of your skull pinches, your chin has lifted. Stop if your arms tingle or you feel dizzy.' },
    easier: { ko: '머리를 들지 말고 이마를 수건에 댄 채 턱 당기기만 5초씩 해요. 엎드리기 불편하면 ‘벽에 기대 턱 당기기’로 대신하세요. 허리가 불편하면 배 밑에 얇은 베개를 받쳐요.', en: 'Skip the lift and simply tuck your chin with your forehead on the towel for 5-second holds. If lying face down is uncomfortable, do the wall chin tuck instead. If your low back complains, put a thin pillow under your belly.' },
    harder: { ko: '버티는 시간을 10초로 늘리고, 익숙해지면 ‘엎드려 Y 들기’를 할 때도 같은 턱 당김을 유지해 보세요.', en: 'Build the hold to 10 seconds; once that’s easy, keep the same chin tuck while doing prone Y raises.' },
    cues: { ko: ['턱 먼저 당기고', '1~2cm만 들어요', '시선은 바닥', '뒷목은 길게'], en: ['Tuck first', 'Lift only 1–2 cm', 'Eyes on the floor', 'Long back of the neck'] },
    mistakes: {
      ko: [
        '턱을 들며 고개를 뒤로 젖힘 → 시선을 바닥에 두고, 턱을 당긴 채 머리 전체를 들어요.',
        '너무 높이 듦 → 수건에서 1~2cm, 종이 한 장이 빠질 정도면 충분해요.',
        '어깨가 귀 쪽으로 올라감 → 어깨를 발 쪽으로 내리고 날개뼈를 살짝 모은 채 해요.',
        '허리를 젖혀 가슴까지 들림 → 가슴과 배는 바닥에 둔 채 머리만 들어요.',
      ],
      en: [
        'Lifting the chin and tipping the head back → Keep your eyes on the floor and lift the whole head with the chin tucked.',
        'Lifting too high → 1–2 cm off the towel — enough to slide a sheet of paper under — is plenty.',
        'Shoulders creeping toward the ears → Slide your shoulders toward your feet and keep the blades gently set.',
        'Arching the low back and lifting the chest → Keep your chest and belly on the floor; only the head lifts.',
      ],
    },
    why: { ko: '거북목에서는 목 뒤 깊은 근육이 늘어난 채 약해져요. 턱을 당긴 채 머리 무게를 버티면 목 앞·뒤 깊은 근육이 함께 일해, 머리를 몸통과 일직선으로 오래 받치는 힘이 길러져요.', en: 'With tech neck the deep muscles at the back of the neck are overstretched and weak. Holding your head’s weight with a chin tuck makes the deep front and back neck muscles work together, building the endurance to carry your head in line with your trunk.' },
    muscles: { ko: '목 뒤 깊은 폄근(두반극근·경반극근·다열근), 심부 목굽힘근, 하부 승모근(보조)', en: 'Deep neck extensors (semispinalis capitis/cervicis, multifidus), deep neck flexors, lower trapezius (assisting)' },
    caution: { ko: '임신 중이거나 엎드리기 불편하면 ‘벽에 기대 턱 당기기’로 대신하세요. 팔 저림, 어지럼, 목의 날카로운 통증이 생기면 멈추세요.', en: 'If you’re pregnant or lying face down is uncomfortable, do the wall chin tuck instead. Stop if your arms tingle, you feel dizzy or you get sharp neck pain.' },
    avoid: ['pregnant', 'neckSevere'],
    anim: {
      view: 60,
      elev: 15,
      props: [{ kind: 'mat' }, { kind: 'step', at: 'head', key: 0, size: [16, 0, 9] }],
      anchor: ['pelvis'],
      keys: [
        merge(PRONE_TOWEL, { neck: { flex: 8 }, head: { flex: 0 } }),
        merge(PRONE_TOWEL, { neck: { flex: 3 }, head: { flex: 12 } }),
        merge(PRONE_TOWEL, { neck: { flex: -4 }, head: { flex: 12 } }, both({ scap: { prot: -1, elev: -0.6 } })),
      ],
      labels: [
        { ko: '이마를 수건에 대기', en: 'Forehead on the towel' },
        { ko: '턱 당기기', en: 'Tuck the chin' },
        { ko: '1~2cm 들어 5초', en: 'Lift 1–2 cm, hold 5 s' },
      ],
      durations: [0.9, 1.1, 1.2],
      pauses: [0.4, 0.4, 3],
      holdKey: 2,
      focus: [
        { a: 'backTop', b: 'neckTop', side: 'back', kind: 'work', r: 2.4 },
        { a: 'chest', b: 'neckTop', side: 'front', kind: 'work', r: 1.8 },
      ],
      trace: ['nose'],
      zoom: 1.2,
    },
  },
  {
    id: 'neck-flexion-stretch',
    name: { ko: '뒷목 길게 늘리기', en: 'Back-of-neck stretch' },
    phase: 'stretch',
    position: 'seated',
    regions: ['neck', 'upperBack'],
    targets: { neckPain: 0.8, headache: 0.6, stiffness: 0.6, fhp: 0.5, stress: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, rest: 10 },
    desk: true,
    setup: {
      ko: [
        '의자 앞쪽 1/3에 앉아 두 발을 골반 너비로 벌리고, 무릎은 90도로 둬요.',
        '골반을 세워 허리와 등을 곧게 펴고, 어깨는 으쓱했다가 툭 떨어뜨려요.',
        '시선은 정면 눈높이에 두고, 두 손은 허벅지 위에 둬요.',
      ],
      en: [
        'Sit on the front third of the chair, feet hip-width apart, knees at 90°.',
        'Stack your pelvis upright so your low and upper back are tall; shrug once and let your shoulders drop.',
        'Look straight ahead with your hands resting on your thighs.',
      ],
    },
    steps: {
      ko: [
        '시선을 정면에 둔 채 머리를 뒤로 1~2cm 밀어 턱을 당겨요(이중턱).',
        '턱을 당긴 채 양손 깍지를 껴 뒤통수 윗부분에 가볍게 얹고, 팔꿈치는 아래로 떨어뜨려요.',
        '3초에 걸쳐 턱을 가슴 쪽으로 천천히 숙여요. 등은 곧게 세운 채 목만 숙여요.',
        '손은 당기지 말고 팔 무게만 얹은 채, 뒷목이 당기는 지점에서 30초 호흡해요.',
        '손을 먼저 내리고, 3초에 걸쳐 고개를 천천히 들어 올려요.',
      ],
      en: [
        'Keeping your eyes level, glide your head back 1–2 cm to tuck your chin (double chin).',
        'Holding the tuck, interlace your fingers and rest them lightly on the upper back of your head, elbows dropping down.',
        'Take 3 seconds to slowly lower your chin toward your chest. Keep your back tall — only your neck bends.',
        'Don’t pull; let just the weight of your arms rest there, and breathe for 30 seconds where the back of your neck feels a stretch.',
        'Lower your hands first, then take 3 seconds to lift your head back up.',
      ],
    },
    breathing: { ko: '고개를 숙이며 입으로 길게 내쉬고, 버티는 동안 코로 들이마시고 입으로 내쉬어요. 내쉴 때마다 턱이 가슴 쪽으로 조금 더 내려가게 둬요.', en: 'Exhale slowly as you bow your head, then breathe in through your nose and out through your mouth. Let your chin sink a little lower with each exhale.' },
    feel: { ko: '뒤통수 아래에서 뒷목을 따라 날개뼈 위쪽까지 길게 늘어나면 정답이에요. 팔이나 손이 저리거나 찌릿하면, 또는 등을 따라 전기가 오는 느낌이 들면 바로 고개를 들고 멈추세요.', en: 'A long stretch from the base of your skull down the back of your neck toward the tops of your shoulder blades. If your arms or hands tingle or buzz, or you feel an electric sensation down your back, lift your head and stop right away.' },
    easier: { ko: '손을 얹지 말고 머리 무게만으로 숙여요. 범위도 절반만, 당김이 살짝 느껴지는 곳까지만 가요.', en: 'Skip the hands and let just the weight of your head do the work, going only halfway — to the first gentle pull.' },
    harder: { ko: '버티는 시간을 45초로 늘리거나, 숙인 채 코를 한쪽 겨드랑이 쪽으로 돌려 ‘견갑거근 스트레칭’으로 이어 가세요.', en: 'Build the hold to 45 seconds, or turn your nose toward one armpit from the bowed position to flow into the levator scapulae stretch.' },
    cues: { ko: ['턱 먼저 당기고', '등은 곧게 세워요', '손은 무게만 얹어요', '내쉬며 조금 더'], en: ['Tuck first', 'Keep your back tall', 'Hands just rest', 'Exhale and sink a little'] },
    mistakes: {
      ko: [
        '손으로 머리를 잡아당김 → 깍지 낀 손은 무게만 얹고, 팔꿈치를 아래로 떨어뜨려요.',
        '등까지 둥글게 말림 → 골반을 세우고 가슴을 편 채 목만 숙여요.',
        '턱이 앞으로 빠진 채 숙임 → 먼저 이중턱을 만든 뒤, 그 상태로 턱을 가슴 쪽으로 내려요.',
        '어깨가 귀 쪽으로 올라감 → 어깨를 툭 떨어뜨리고 팔꿈치 무게를 아래로 늘어뜨려요.',
      ],
      en: [
        'Pulling the head down with your hands → Let the clasped hands simply rest and drop your elbows.',
        'Rounding the whole back → Sit up on your sit bones, keep the chest open and bend only the neck.',
        'Bowing with the chin poking forward → Make the double chin first, then lower the chin toward your chest.',
        'Shoulders creeping up to the ears → Drop your shoulders and let your elbows hang heavy.',
      ],
    },
    why: { ko: '머리가 앞으로 나오고 턱이 들리면 뒤통수 아래와 뒷목 근육이 짧게 뭉쳐 뻐근함과 두통을 만들어요. 턱을 먼저 당기고 숙이면 목 아랫부분뿐 아니라 윗부분까지 고르게 늘어나요.', en: 'When the head juts forward and the chin lifts, the muscles at the base of the skull and back of the neck shorten and knot, feeding stiffness and headaches. Tucking before you bow stretches the upper neck too, not just the base.' },
    muscles: { ko: '후두하근, 뒷목 근육(두반극근·판상근), 상부 승모근', en: 'Suboccipitals, posterior neck muscles (semispinalis, splenius), upper trapezius' },
    caution: { ko: '팔·손 저림이나 찌릿함, 등을 타고 내려가는 전기 같은 느낌이 들면 바로 멈추고, 계속되면 전문가와 상의하세요. 숙일 때 어지러워도 멈추세요.', en: 'Stop immediately if your arms or hands tingle or buzz, or you feel an electric sensation down your spine, and see a professional if it persists. Stop as well if bowing your head makes you dizzy.' },
    avoid: ['neckSevere', 'radiating'],
    anim: {
      view: 125,
      elev: 12,
      props: [{ kind: 'chair' }],
      keys: [
        SIT_TALL,
        merge(SIT_TUCK, both({ sh: { flex: 147, abd: -15, rot: -61, hab: -27 }, el: 114, wr: -64 })),
        merge(SIT, { neck: { flex: 36 }, head: { flex: 14 } }, both({ sh: { flex: 105, abd: 16, rot: -9, hab: -8 }, el: 112, wr: -66 })),
      ],
      labels: [
        { ko: '바르게 앉기', en: 'Sit tall' },
        { ko: '턱 당기고 손 얹기', en: 'Tuck, hands on head' },
        { ko: '고개 숙여 30초', en: 'Bow the head, 30 s' },
      ],
      durations: [1.2, 1.8, 1.8],
      pauses: [0.4, 0.5, 3],
      holdKey: 2,
      focus: [
        { a: 'chest', b: 'head', side: 'back', kind: 'stretch', r: 2.2, from: 0.05, to: 0.85 },
        { a: 'neckTop', b: 'shL', kind: 'stretch', r: 1.6, from: 0.15, to: 0.55 },
        { a: 'neckTop', b: 'shR', kind: 'stretch', r: 1.6, from: 0.15, to: 0.55 },
      ],
      trace: ['headTop'],
      zoom: 1.2,
    },
  },
];
