/**
 * 운동 라이브러리 · 어깨·견갑
 * 문구·용량·대상 이슈는 물리치료 임상 기준으로 작성되었으며, 전문가가 자유롭게 수정할 수 있습니다.
 * 작성 규칙: docs/CONTENT_GUIDE.md
 */
import { both } from '../../figure/rig';
import { PRONE, STAND, WALL, merge } from '../../figure/poses';
import type { Exercise } from '../exercise-types';

export const SHOULDER: Exercise[] = [
  {
    id: 'shoulder-rolls',
    name: { ko: '어깨 뒤로 돌리기', en: 'Backward shoulder rolls' },
    phase: 'mobility',
    position: 'standing',
    regions: ['shoulder', 'neck'],
    targets: { stiffness: 0.8, neckPain: 0.4, roundShoulder: 0.3, stress: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 3, rest: 10 },
    desk: true,
    steps: {
      ko: ['편하게 서거나 앉아서 팔에 힘을 빼요.', '어깨를 귀 쪽으로 끌어올린 뒤', '뒤로 크게 돌리며 날개뼈를 모았다가', '아래로 쭉 내려놓아요. 큰 원을 그리듯 천천히.'],
      en: ['Stand or sit with your arms relaxed.', 'Lift your shoulders up toward your ears,', 'roll them back, squeezing your shoulder blades together,', 'then drop them down. Draw big, slow circles.'],
    },
    cues: { ko: ['크게 원을 그려요', '뒤로 모으고 아래로'], en: ['Big circles', 'Back and down'] },
    mistakes: { ko: ['너무 빠르게 돌림', '목까지 같이 움직임'], en: ['Rolling too fast', 'Moving the neck along'] },
    why: { ko: '굳은 어깨 주변에 혈류를 돌리고, 어깨를 “뒤·아래” 제자리로 돌려놓는 감각을 깨우는 워밍업이에요.', en: 'A warm-up that gets blood moving around stiff shoulders and reminds them where “back and down” is.' },
    muscles: { ko: '승모근, 능형근, 견갑거근', en: 'Trapezius, rhomboids, levator scapulae' },
    anim: {
      view: 90,
      keys: [
        STAND,
        merge(STAND, both({ scap: { elev: 4.5, prot: 1.5 } })),
        merge(STAND, both({ scap: { elev: 2.5, prot: -3 } }), { thorax: { flex: -3 } }),
        merge(STAND, both({ scap: { elev: -1, prot: -2 } })),
      ],
      durations: [0.8, 0.8, 0.7, 0.7],
      zoom: 1.2,
    },
  },
  {
    id: 'wall-angel',
    name: { ko: '벽 천사', en: 'Wall angel' },
    phase: 'activate',
    position: 'wall',
    regions: ['shoulder', 'upperBack'],
    targets: { roundShoulder: 0.9, kyphosis: 0.7, fhp: 0.5, upperBackPain: 0.4 },
    equipment: ['wall'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 10, tempo: 4, rest: 20 },
    steps: {
      ko: ['벽에서 발뒤꿈치를 한 뼘 떨어뜨리고 엉덩이·등·뒤통수를 벽에 붙여요.', '팔을 W 모양으로 만들어 팔꿈치와 손등을 벽에 대요.', '허리가 뜨지 않게 배에 살짝 힘을 주고 팔을 위로 천천히 밀어 올려요.', 'Y 모양까지 올렸다가 다시 W로 내려와요.'],
      en: ['Stand with heels a hand-width from the wall; glutes, back and head touch the wall.', 'Make a “W” with your arms, elbows and backs of the hands on the wall.', 'Brace your belly so your low back stays on the wall, then slide your arms up slowly.', 'Go up to a “Y”, then back down to the “W”.'],
    },
    cues: { ko: ['허리는 벽에 붙인 채', '손등이 벽에서 떨어지지 않게', '천천히 내려요'], en: ['Low back stays on the wall', 'Backs of hands on the wall', 'Slow on the way down'] },
    mistakes: { ko: ['허리가 벽에서 뜸', '턱이 들림', '어깨를 으쓱함'], en: ['Low back peeling off the wall', 'Chin poking out', 'Shrugging'] },
    why: { ko: '말린 어깨를 뒤로 모아 주는 중·하부 승모근을 깨우고 가슴을 여는, 라운드숄더 교정의 대표 운동이에요.', en: 'The classic rounded-shoulder fix: activates the middle/lower traps while opening the chest.' },
    muscles: { ko: '중·하부 승모근, 전거근', en: 'Middle/lower trapezius, serratus anterior' },
    caution: { ko: '팔이 벽에 다 닿지 않아도 괜찮아요. 통증 없는 범위까지만.', en: 'It’s fine if your arms don’t touch the wall fully — stay pain-free.' },
    avoid: ['shoulderSevere'],
    anim: {
      view: 0,
      props: [{ kind: 'wall', wall: 'back' }],
      keys: [merge(WALL, both({ sh: { abd: 82, rot: 88 }, el: 96 })), merge(WALL, both({ sh: { abd: 150, rot: 88 }, el: 24 }))],
      durations: [1.8, 1.8],
      pauses: [0.3, 0.4],
    },
    coach: {
      view: 'front',
      metric: 'armRaise',
      mode: 'reps',
      rest: 0.55,
      peak: 0.85,
      dir: 1,
      hint: { ko: '정면에서 팔 끝까지 보이게 2m 거리에 휴대폰을 세워 주세요', en: 'Place the phone about 2 m in front of you so your arms are visible' },
      more: { ko: '팔을 조금 더 위로', en: 'Reach a little higher' },
      good: { ko: '좋아요!', en: 'Nice!' },
    },
  },
  {
    id: 'prone-y-raise',
    name: { ko: '엎드려 Y 들기', en: 'Prone Y raise' },
    phase: 'activate',
    position: 'prone',
    regions: ['upperBack', 'shoulder'],
    targets: { roundShoulder: 1, kyphosis: 0.7, upperBackPain: 0.5, fhp: 0.3 },
    equipment: ['mat'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 3, holdSec: 2, rest: 20 },
    steps: {
      ko: ['엎드려 이마 아래 수건을 받치고 턱을 살짝 당겨요.', '엄지가 천장을 향하게 하고 팔을 Y자로 뻗어요.', '날개뼈를 아래·안쪽으로 모으며 팔을 바닥에서 살짝 들어요.', '2초 버티고 천천히 내려요. 익숙해지면 T·W 모양도 같은 방법으로 해요.'],
      en: ['Lie face down with a towel under your forehead and your chin gently tucked.', 'Stretch your arms into a “Y” with thumbs pointing up.', 'Draw your shoulder blades down and together and lift your arms slightly off the floor.', 'Hold 2 seconds and lower slowly. Progress to “T” and “W” shapes the same way.'],
    },
    cues: { ko: ['날개뼈를 아래로 모아요', '목은 길게', '천천히 내려요'], en: ['Blades down and in', 'Long neck', 'Lower slowly'] },
    mistakes: { ko: ['고개를 들어 올림', '허리를 젖혀 상체를 듦', '어깨를 으쓱'], en: ['Lifting the head', 'Arching the back to lift', 'Shrugging'] },
    why: { ko: '가장 약해지기 쉬운 하부 승모근을 정확히 강화해 어깨를 뒤·아래로 안정시켜요.', en: 'Precisely strengthens the lower trapezius — usually the weakest link — to hold the shoulders back and down.' },
    muscles: { ko: '하부·중부 승모근, 능형근', en: 'Lower & middle trapezius, rhomboids' },
    avoid: ['pregnant', 'shoulderSevere'],
    anim: {
      view: 90,
      elev: 14,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [merge(PRONE, both({ sh: { flex: 176, abd: 28, rot: 30 }, el: 0 })), merge(PRONE, both({ sh: { flex: 196, abd: 28, rot: 30 }, el: 0, scap: { prot: -2, elev: -1 } }), { thorax: { flex: -4 } })],
      durations: [1.3, 1.3],
      pauses: [0.4, 1.8],
    },
  },
  {
    id: 'scap-squeeze',
    name: { ko: '날개뼈 모으며 팔 벌리기', en: 'Scapular squeeze & external rotation' },
    phase: 'activate',
    position: 'standing',
    regions: ['upperBack', 'shoulder'],
    targets: { roundShoulder: 0.8, upperBackPain: 0.6, kyphosis: 0.4, fhp: 0.2 },
    equipment: [],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 12, tempo: 2.5, holdSec: 3, rest: 15 },
    desk: true,
    steps: {
      ko: ['팔꿈치를 90°로 굽혀 옆구리에 붙이고 손바닥은 위로 향해요.', '팔꿈치를 옆구리에 붙인 채 손을 바깥으로 벌려요.', '동시에 날개뼈를 뒤·아래로 모아요.', '3초 버티고 천천히 돌아와요. 어깨가 올라가지 않게.'],
      en: ['Bend your elbows 90° at your sides, palms up.', 'Keeping the elbows tucked, rotate your hands outward.', 'At the same time draw your shoulder blades back and down.', 'Hold 3 seconds and return slowly — no shrugging.'],
    },
    cues: { ko: ['팔꿈치는 옆구리에', '날개뼈를 뒤로 아래로', '가슴을 펴요'], en: ['Elbows stay tucked', 'Blades back and down', 'Open the chest'] },
    mistakes: { ko: ['팔꿈치가 옆구리에서 떨어짐', '허리를 젖힘'], en: ['Elbows drifting away', 'Arching the low back'] },
    why: { ko: '말린 어깨를 바깥으로 돌려 주는 회전근개와 날개뼈 안정근을 함께 깨워요. 틈날 때마다 하기 좋아요.', en: 'Wakes up the rotator cuff and shoulder-blade stabilisers that un-roll your shoulders. Great to sprinkle through the day.' },
    muscles: { ko: '극하근·소원근, 중부 승모근, 능형근', en: 'Infraspinatus, teres minor, middle trap, rhomboids' },
    anim: {
      view: 20,
      elev: 18,
      keys: [merge(STAND, both({ sh: { rot: -10, abd: 8 }, el: 90 })), merge(STAND, both({ sh: { rot: 62, abd: 8, flex: -6 }, el: 90, scap: { prot: -2.8, elev: -0.8 } }), { thorax: { flex: -3 } })],
      durations: [1.2, 1.2],
      pauses: [0.3, 1.8],
      zoom: 1.1,
    },
  },
  {
    id: 'band-pull-apart',
    name: { ko: '밴드 당겨 벌리기', en: 'Band pull-apart' },
    phase: 'activate',
    position: 'standing',
    regions: ['upperBack', 'shoulder'],
    targets: { roundShoulder: 0.9, kyphosis: 0.5, upperBackPain: 0.4 },
    equipment: ['band'],
    level: 2,
    dose: { kind: 'reps', sets: 2, value: 15, tempo: 2.5, holdSec: 1, rest: 20 },
    steps: {
      ko: ['밴드를 어깨너비로 잡고 팔을 가슴 높이로 앞으로 뻗어요.', '날개뼈를 모으며 밴드가 가슴에 닿을 듯 양옆으로 벌려요.', '1초 버티고 천천히 돌아와요.'],
      en: ['Hold a band shoulder-width apart with arms straight in front at chest height.', 'Squeeze your shoulder blades and pull the band apart toward your chest.', 'Pause 1 second and return slowly.'],
    },
    cues: { ko: ['날개뼈 먼저 모아요', '어깨는 아래로'], en: ['Blades first', 'Shoulders down'] },
    mistakes: { ko: ['어깨가 올라감', '허리를 젖힘'], en: ['Shrugging', 'Arching the back'] },
    why: { ko: '등 뒤쪽 근육을 저항을 이용해 확실히 강화해요. 벽 천사가 쉬워졌다면 다음 단계예요.', en: 'Strengthens the back of the shoulders against resistance — the next step once wall angels feel easy.' },
    muscles: { ko: '후면 삼각근, 능형근, 중부 승모근', en: 'Rear delts, rhomboids, middle trapezius' },
    anim: {
      view: 30,
      elev: 22,
      props: [{ kind: 'band', at: 'wrL', to: 'wrR' }],
      keys: [merge(STAND, both({ sh: { flex: 86, hab: -6 }, el: 4 })), merge(STAND, both({ sh: { flex: 86, hab: 78 }, el: 4, scap: { prot: -3 } }))],
      durations: [1.2, 1.3],
      pauses: [0.2, 0.8],
    },
  },
];
