/**
 * 운동 라이브러리 · 가슴·등(흉추)
 * 문구·용량·대상 이슈는 물리치료 임상 기준으로 작성되었으며, 전문가가 자유롭게 수정할 수 있습니다.
 * 작성 규칙: docs/CONTENT_GUIDE.md
 */
import { both } from '../../figure/rig';
import { HANDS_BEHIND_HEAD, HOOK, QUAD, SIDE_LYING, SIT, STAND, merge } from '../../figure/poses';
import type { Exercise } from '../exercise-types';

export const THORACIC: Exercise[] = [
  {
    id: 'chest-opener',
    name: { ko: '앉아서 가슴 열기', en: 'Seated chest opener' },
    phase: 'stretch',
    position: 'seated',
    regions: ['chest', 'shoulder'],
    targets: { roundShoulder: 0.8, kyphosis: 0.5, fhp: 0.3 },
    equipment: [],
    level: 1,
    dose: { kind: 'hold', sets: 3, value: 20, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자 앞쪽에 앉아 양손을 등 뒤에서 깍지 껴요.', '날개뼈를 모으며 팔을 뒤로 쭉 뻗어요.', '가슴을 앞으로 활짝 열고 턱은 살짝 당겨요.', '20초 유지하며 호흡해요.'],
      en: ['Sit near the front of the chair and clasp your hands behind your back.', 'Squeeze your shoulder blades together and straighten your arms back.', 'Open your chest forward while keeping your chin gently tucked.', 'Hold for 20 seconds and breathe.'],
    },
    cues: { ko: ['날개뼈를 모아요', '가슴은 앞으로', '턱은 살짝 당겨요'], en: ['Squeeze the shoulder blades', 'Chest forward', 'Chin gently in'] },
    mistakes: { ko: ['허리만 과하게 젖힘', '고개가 앞으로 빠짐'], en: ['Over-arching the low back', 'Head drifting forward'] },
    why: { ko: '말린 어깨의 원인인 짧아진 가슴 근육을 늘리고, 등 근육으로 어깨를 뒤로 모으는 감각을 동시에 익혀요.', en: 'Stretches the shortened chest muscles that round your shoulders while teaching your back muscles to hold them back.' },
    muscles: { ko: '대흉근, 소흉근, 삼각근 앞쪽', en: 'Pecs major & minor, front deltoids' },
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      keys: [merge(SIT, both({ sh: { flex: -20, abd: 8 }, el: 20 })), merge(SIT, both({ sh: { flex: -48, abd: 4 }, el: 0, scap: { prot: -3 } }), { thorax: { flex: -10 }, neck: { flex: 4 } })],
      durations: [1.4, 1.4],
      pauses: [0.4, 2.6],
      zoom: 1.2,
    },
  },
  {
    id: 'wall-pec-stretch',
    name: { ko: '벽 가슴 스트레칭', en: 'Wall pec stretch' },
    phase: 'stretch',
    position: 'wall',
    regions: ['chest', 'shoulder'],
    targets: { roundShoulder: 1, kyphosis: 0.5, fhp: 0.3, shoulderPain: 0.3 },
    equipment: ['wall'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, perSide: true, rest: 5 },
    steps: {
      ko: ['벽 옆에 서서 오른팔을 90°로 굽혀 팔꿈치와 손바닥을 벽에 대요.', '오른발을 반 걸음 앞으로 내딛으며 몸을 왼쪽으로 살짝 돌려요.', '가슴 앞쪽이 늘어나면 멈추고 30초 유지해요.', '어깨가 앞으로 튀어나오지 않게 날개뼈를 살짝 모아요.'],
      en: ['Stand beside a wall and place your right forearm on it with the elbow bent 90°.', 'Step your right foot half a step forward and gently turn your body to the left.', 'Stop when the front of your chest stretches and hold 30 seconds.', 'Keep the shoulder blade gently back so the shoulder doesn’t poke forward.'],
    },
    cues: { ko: ['몸을 천천히 반대로', '어깨는 뒤로', '숨을 길게'], en: ['Turn away slowly', 'Shoulder back', 'Long breaths'] },
    mistakes: { ko: ['어깨가 앞으로 쏠림', '팔을 너무 높이 올림'], en: ['Shoulder rolling forward', 'Arm placed too high'] },
    why: { ko: '라운드숄더의 핵심 원인인 대흉근·소흉근을 가장 효과적으로 늘리는 방법이에요.', en: 'The most effective way to lengthen the pecs — the key driver of rounded shoulders.' },
    muscles: { ko: '대흉근, 소흉근', en: 'Pectoralis major & minor' },
    caution: { ko: '어깨 앞이 찌릿하거나 저리면 팔 높이를 낮추세요.', en: 'Lower the arm if the front of the shoulder pinches or tingles.' },
    avoid: ['shoulderSevere'],
    anim: {
      view: -35,
      props: [{ kind: 'wall', wall: 'right', dist: 1 }],
      keys: [
        merge(STAND, { shR: { abd: 88, rot: 85, flex: -8 }, elR: 92, shL: { abd: 6 }, elL: 8 }),
        merge(STAND, { shR: { abd: 88, rot: 85, flex: -30 }, elR: 92, shL: { abd: 6 }, elL: 8, thorax: { twist: 16 }, lumbar: { twist: 8 }, hipR: { flex: 14 }, knR: 10, hipL: { flex: -8 } }),
      ],
      durations: [1.6, 1.6],
      pauses: [0.6, 3],
    },
  },
  {
    id: 'chair-tspine-extension',
    name: { ko: '의자 등받이 등 펴기', en: 'Chair thoracic extension' },
    phase: 'mobility',
    position: 'seated',
    regions: ['upperBack'],
    targets: { kyphosis: 1, roundShoulder: 0.6, fhp: 0.4, upperBackPain: 0.7, stiffness: 0.4 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 4, holdSec: 2, rest: 10 },
    desk: true,
    steps: {
      ko: ['등받이 윗부분이 날개뼈 아래에 오도록 깊숙이 앉아요.', '양손을 머리 뒤에 깍지 끼고 팔꿈치를 모아요.', '숨을 내쉬며 등받이를 받침 삼아 가슴을 천장 쪽으로 젖혀요.', '허리가 아닌 등 윗부분이 펴지는 느낌으로 2초 멈췄다 돌아와요.'],
      en: ['Sit back so the top of the chair meets your back just below the shoulder blades.', 'Clasp your hands behind your head, elbows together.', 'Exhale and extend your chest toward the ceiling over the chair back.', 'Feel it in the upper back, not the low back. Pause 2 seconds and return.'],
    },
    cues: { ko: ['가슴을 천장으로', '허리는 그대로', '숨을 내쉬며'], en: ['Chest to the ceiling', 'Low back stays put', 'Exhale as you go'] },
    mistakes: { ko: ['허리를 꺾음', '목만 뒤로 젖힘'], en: ['Arching the low back', 'Only tipping the head back'] },
    why: { ko: '둥글게 굳은 흉추(등뼈)를 펴 주면 어깨와 목이 따라서 제자리를 찾아요. 사무실에서 가장 효율 좋은 동작이에요.', en: 'Unlocking a stiff, rounded upper spine lets your neck and shoulders fall back into place — the best bang-for-buck desk move.' },
    muscles: { ko: '흉추 신전근, 흉추 관절 가동성', en: 'Thoracic extensors & joint mobility' },
    anim: {
      view: 90,
      props: [{ kind: 'chair' }],
      keys: [merge(SIT, HANDS_BEHIND_HEAD, { thorax: { flex: 6 } }), merge(SIT, HANDS_BEHIND_HEAD, { thorax: { flex: -22 }, lumbar: { flex: -4 }, neck: { flex: -6 } })],
      durations: [1.8, 1.8],
      pauses: [0.3, 1.2],
      zoom: 1.2,
    },
  },
  {
    id: 'open-book',
    name: { ko: '오픈북 (등 돌리기)', en: 'Open book' },
    phase: 'mobility',
    position: 'sideLying',
    regions: ['upperBack', 'chest'],
    targets: { kyphosis: 0.8, upperBackPain: 0.8, roundShoulder: 0.6, stiffness: 0.5 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 5, perSide: true, rest: 10 },
    steps: {
      ko: ['왼쪽으로 누워 무릎을 90°로 굽히고 양팔을 앞으로 모아요.', '위쪽 팔을 천장 → 반대쪽 바닥으로, 책을 펼치듯 열어요.', '시선은 손을 따라가고 무릎은 서로 붙인 채 유지해요.', '숨을 내쉬며 열고, 들이쉬며 돌아와요.'],
      en: ['Lie on your left side, knees bent 90°, arms together in front.', 'Open your top arm up and over to the floor behind you, like opening a book.', 'Follow your hand with your eyes and keep your knees together.', 'Exhale as you open, inhale as you return.'],
    },
    cues: { ko: ['무릎은 붙인 채', '시선은 손을 따라', '숨을 내쉬며 열어요'], en: ['Knees stay together', 'Eyes follow the hand', 'Exhale to open'] },
    mistakes: { ko: ['무릎이 같이 넘어감', '팔만 억지로 넘김'], en: ['Knees rolling open', 'Forcing just the arm'] },
    why: { ko: '앉아 있는 동안 굳는 흉추의 회전을 되살려 등 뻐근함을 풀고 호흡을 깊게 해요.', en: 'Restores rotation to a stiff upper spine, easing back tightness and deepening your breath.' },
    muscles: { ko: '흉추 회전 가동성, 대흉근', en: 'Thoracic rotation, pecs' },
    anim: {
      view: 0,
      elev: 62,
      props: [{ kind: 'mat' }],
      anchor: ['pelvis'],
      keys: [
        merge(SIDE_LYING, both({ hip: { flex: 90 }, kn: 90 }), both({ sh: { flex: 88 }, el: 0 }), { neck: { side: -6 } }),
        merge(SIDE_LYING, both({ hip: { flex: 90 }, kn: 90 }), { shL: { flex: 88 }, elL: 0, shR: { flex: 88, hab: 120 }, elR: 5, thorax: { twist: -55 }, lumbar: { twist: -10 }, neck: { twist: -40, side: -6 } }),
      ],
      durations: [2.2, 2.2],
      pauses: [0.3, 1.2],
    },
  },
  {
    id: 'thread-needle',
    name: { ko: '스레드 더 니들', en: 'Thread the needle' },
    phase: 'mobility',
    position: 'quadruped',
    regions: ['upperBack', 'shoulder'],
    targets: { upperBackPain: 0.7, kyphosis: 0.6, stiffness: 0.5, roundShoulder: 0.3 },
    equipment: ['mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 6, tempo: 5, perSide: true, rest: 10 },
    steps: {
      ko: ['네발 자세에서 오른팔을 천장으로 뻗으며 가슴을 오른쪽으로 열어요.', '이번엔 오른팔을 왼팔 아래로 실을 꿰듯 깊숙이 넣어요.', '오른쪽 어깨와 귀를 바닥 가까이 내려 등 윗부분을 비틀어요.', '천천히 열고 닫기를 반복해요.'],
      en: ['From all fours, reach your right arm to the ceiling, opening your chest to the right.', 'Then thread the right arm under your left arm, deep across the floor.', 'Let your right shoulder and ear sink toward the floor to twist the upper back.', 'Open and close slowly.'],
    },
    cues: { ko: ['시선은 손끝을 따라', '골반은 가운데 고정'], en: ['Eyes follow your hand', 'Keep the hips centred'] },
    mistakes: { ko: ['골반이 옆으로 빠짐', '허리로 비틈'], en: ['Hips swaying sideways', 'Twisting from the low back'] },
    why: { ko: '어깨뼈 사이 뻐근함을 풀고 흉추 회전을 되찾아 줘요.', en: 'Releases tension between the shoulder blades and restores upper-back rotation.' },
    muscles: { ko: '능형근, 흉추 회전근', en: 'Rhomboids, thoracic rotators' },
    avoid: ['wristPain', 'kneePain'],
    anim: {
      view: 90,
      elev: 20,
      props: [{ kind: 'mat' }],
      anchor: ['knL', 'knR'],
      keys: [
        merge(QUAD, { shR: { flex: 60, abd: 110 }, elR: 5, thorax: { twist: -42 }, neck: { twist: -30 } }),
        merge(QUAD, { shR: { flex: 95, abd: -70, rot: -20 }, elR: 5, thorax: { twist: 32, flex: 6 }, shL: { flex: 88 }, elL: 20, neck: { twist: 20 } }),
      ],
      durations: [2.4, 2.4],
      pauses: [0.6, 1.2],
    },
  },
  {
    id: 'foam-roller-tspine',
    name: { ko: '폼롤러 등 펴기', en: 'Foam roller thoracic extension' },
    phase: 'mobility',
    position: 'supine',
    regions: ['upperBack'],
    targets: { kyphosis: 1, roundShoulder: 0.6, upperBackPain: 0.7, fhp: 0.3 },
    equipment: ['foamRoller', 'mat'],
    level: 1,
    dose: { kind: 'reps', sets: 2, value: 8, tempo: 4, holdSec: 2, rest: 15 },
    steps: {
      ko: ['폼롤러를 날개뼈 아래에 가로로 두고 무릎을 세워 누워요.', '양손으로 머리를 받쳐 목에 힘을 빼요.', '숨을 내쉬며 폼롤러를 받침 삼아 등 윗부분을 뒤로 젖혀요.', '2초 멈췄다 돌아와요. 폼롤러를 한 칸씩 위로 옮겨 가며 반복해요.'],
      en: ['Lie with a foam roller across your back just below the shoulder blades, knees bent.', 'Support your head with your hands and relax your neck.', 'Exhale and extend your upper back over the roller.', 'Pause 2 seconds and return. Move the roller up one notch at a time.'],
    },
    cues: { ko: ['엉덩이는 바닥에', '숨을 내쉬며 젖혀요'], en: ['Hips stay down', 'Exhale and extend'] },
    mistakes: { ko: ['허리 아래(요추)에서 굴림', '엉덩이를 듦'], en: ['Rolling under the low back', 'Lifting the hips'] },
    why: { ko: '굳은 흉추 관절을 한 마디씩 펴 주는 가장 확실한 도구 운동이에요.', en: 'The most effective tool-based way to extend the stiff upper spine, segment by segment.' },
    muscles: { ko: '흉추 신전 가동성', en: 'Thoracic extension mobility' },
    caution: { ko: '골다공증이 있거나 등에 날카로운 통증이 있으면 생략하세요.', en: 'Skip if you have osteoporosis or sharp back pain.' },
    avoid: ['pregnant'],
    anim: {
      view: 90,
      elev: 10,
      props: [{ kind: 'mat' }, { kind: 'roller', at: 'backTop', off: [0, -7, 1] }],
      anchor: ['pelvis'],
      keys: [merge(HOOK, HANDS_BEHIND_HEAD, { root: { pitch: -72 }, thorax: { flex: 8 }, neck: { flex: 8 } }), merge(HOOK, HANDS_BEHIND_HEAD, { root: { pitch: -72 }, thorax: { flex: -26 }, neck: { flex: 2 } })],
      durations: [1.8, 1.8],
      pauses: [0.3, 1.2],
    },
  },
  {
    id: 'seated-twist',
    name: { ko: '앉아서 척추 비틀기', en: 'Seated spinal twist' },
    phase: 'mobility',
    position: 'seated',
    regions: ['upperBack', 'lowBack'],
    targets: { stiffness: 0.7, upperBackPain: 0.5, lowBackPain: 0.3, kyphosis: 0.3 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 15, perSide: true, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자에 곧게 앉아 발을 바닥에 붙여요.', '숨을 들이쉬며 정수리를 위로 늘이고,', '내쉬며 상체를 왼쪽으로 돌려 오른손은 왼무릎, 왼손은 등받이를 잡아요.', '골반은 정면에 둔 채 15초 유지해요.'],
      en: ['Sit tall with feet flat.', 'Inhale and grow tall through the crown,', 'exhale and turn your upper body left, right hand on the left knee, left hand on the chair back.', 'Keep your pelvis facing forward and hold 15 seconds.'],
    },
    cues: { ko: ['위로 길게, 그리고 돌려요', '골반은 정면'], en: ['Grow tall, then turn', 'Pelvis faces forward'] },
    mistakes: { ko: ['등을 말고 비틈', '목만 돌림'], en: ['Twisting while slumped', 'Turning only the neck'] },
    why: { ko: '앉아서 굳은 척추의 회전을 풀어 등·허리 뻐근함을 줄여요.', en: 'Unlocks spinal rotation stiffened by sitting to ease back tightness.' },
    muscles: { ko: '척추 회전근, 복사근', en: 'Spinal rotators, obliques' },
    anim: {
      view: 0,
      props: [{ kind: 'chair' }],
      keys: [SIT, merge(SIT, { thorax: { twist: 34 }, lumbar: { twist: 10 }, neck: { twist: 18 }, shR: { flex: 40, abd: -30 }, elR: 50, shL: { flex: -10, abd: 30 }, elL: 40 })],
      durations: [1.6, 1.6],
      pauses: [0.4, 2.6],
    },
  },
  {
    id: 'chair-lat-stretch',
    name: { ko: '의자 잡고 등·겨드랑이 늘리기', en: 'Chair lat stretch' },
    phase: 'stretch',
    position: 'standing',
    regions: ['upperBack', 'shoulder'],
    targets: { kyphosis: 0.6, roundShoulder: 0.5, lordosis: 0.3, upperBackPain: 0.4 },
    equipment: ['chair'],
    level: 1,
    dose: { kind: 'hold', sets: 2, value: 30, rest: 5 },
    desk: true,
    steps: {
      ko: ['의자 등받이(또는 책상)를 양손으로 잡고 뒤로 물러나요.', '엉덩이를 뒤로 빼며 상체를 숙여 팔과 몸통이 일직선이 되게 해요.', '가슴을 바닥 쪽으로 지그시 눌러 겨드랑이~등이 늘어나면 30초.'],
      en: ['Hold the back of a chair (or a desk) and step back.', 'Push your hips back and fold until your arms and trunk form a line.', 'Let your chest sink toward the floor and hold 30 seconds as your armpits and back stretch.'],
    },
    cues: { ko: ['엉덩이는 뒤로', '가슴은 아래로'], en: ['Hips back', 'Chest down'] },
    mistakes: { ko: ['허리를 과하게 꺾음', '고개를 떨어뜨림'], en: ['Over-arching the low back', 'Dropping the head'] },
    why: { ko: '짧아진 광배근은 어깨를 말고 허리를 휘게 만들어요. 팔을 머리 위로 들 때 걸리는 느낌도 줄여 줘요.', en: 'Tight lats round the shoulders and arch the back; stretching them also frees overhead reaching.' },
    muscles: { ko: '광배근, 대원근, 흉추', en: 'Latissimus dorsi, teres major, thoracic spine' },
    anim: {
      view: 90,
      keys: [
        merge(STAND, both({ sh: { flex: 70 }, el: 20 }), { root: { pitch: 20 } }, both({ hip: { flex: 20 } })),
        merge(both({ sh: { flex: 168 }, el: 4, hip: { flex: 86 }, kn: 12, an: 6 }), { root: { pitch: 82 }, thorax: { flex: -8 }, neck: { flex: -4 } }),
      ],
      durations: [2, 2],
      pauses: [0.4, 3],
    },
  },
];
